-- src/meta/itemMeta.lua
--
-- Initially generated by `lua generate.lua meta` from Questie's itemKeys and
-- itemCompilerTypes in Database/itemDB.lua.
-- Last migration reference: Questie/Questie@454b9d072965ee8f1a881429260fcf1fac8d60f7.
-- See PROVENANCE.md for import history and the retired derivation tool.
--
-- Now maintained here: update field keys, storage behavior, and LuaLS declarations together.
-- compilerTypes preserves the original type names for provenance and public API compatibility.

local _, LibQuestieDB = ...

local meta = {
  entity = 'Item',
  metaPrefix = 'Item-',
  fieldCount = 16,

  --- fieldName -> fieldIndex. The Database Key Enum.
  keys = {
    -- Localized item name.
    ['name'] = 1,
    -- NPC IDs that can drop this item.
    ['npcDrops'] = 2,
    -- Object IDs that can drop this item.
    ['objectDrops'] = 3,
    -- Item IDs for containers that can contain this item.
    ['itemDrops'] = 4,
    -- ID of the quest started by this item.
    ['startQuest'] = 5,
    -- Quest IDs that reward this item.
    ['questRewards'] = 6,
    -- Item flag bitmask; see https://github.com/cmangos/issues/wiki/Item_template#flags
    ['flags'] = 7,
    -- Food category; see https://github.com/cmangos/issues/wiki/Item_template#foodtype
    ['foodType'] = 8,
    -- Item level.
    ['itemLevel'] = 9,
    -- Player level required to equip or use this item.
    ['requiredLevel'] = 10,
    -- Ammo category used by projectile items.
    ['ammoType'] = 11,
    -- Item class ID.
    ['class'] = 12,
    -- Item subclass ID within the item class.
    ['subClass'] = 13,
    -- NPC IDs for vendors that sell this item.
    ['vendors'] = 14,
    -- IDs of quests related to this item.
    ['relatedQuests'] = 15,
    -- Spell ID taught when this item is used.
    ['teachesSpell'] = 16,
  },

  --- fieldIndex -> fieldName
  names = {
[1]='name', [2]='npcDrops', [3]='objectDrops', [4]='itemDrops', [5]='startQuest', [6]='questRewards', [7]='flags', [8]='foodType', [9]='itemLevel', [10]='requiredLevel', [11]='ammoType', [12]='class', [13]='subClass', [14]='vendors', [15]='relatedQuests', [16]='teachesSpell'
  },

  --- fieldIndex -> storage type: number | string | table
  types = {
[1]='string', [2]='table', [3]='table', [4]='table', [5]='number', [6]='table', [7]='number', [8]='number', [9]='number', [10]='number', [11]='number', [12]='number', [13]='number', [14]='table', [15]='table', [16]='number'
  },

  --- fieldIndex -> structural shape, for validators. nil for scalars.
  structures = {
[2]='idarray', [3]='idarray', [4]='idarray', [6]='idarray', [14]='idarray', [15]='idarray'
  },

  --- fieldIndex -> Questie compiler type. Materialized provenance.
  compilerTypes = {
[1]='u8string', [2]='u16u24array', [3]='u8u24array', [4]='u8u24array', [5]='u24', [6]='u8u24array', [7]='u32', [8]='u8', [9]='u16', [10]='u8', [11]='u8', [12]='u8', [13]='u8', [14]='u16u24array', [15]='u8u24array', [16]='u24'
  },

  --- fieldIndex -> true when an empty table must read back as nil
  emptyIsNil = {
[2]=true, [3]=true, [4]=true, [6]=true, [14]=true, [15]=true
  },

  --- fieldIndex -> true when {0,0} must read back as nil
  zeroPairIsNil = {

  },

  --- fieldIndex -> named normalizer
  normalize = {

  },

  --- field indices carrying translations
  l10nFields = {1},
}

if LibQuestieDB then
  LibQuestieDB.Meta = LibQuestieDB.Meta or {}
  LibQuestieDB.Meta['Item'] = meta
end

return meta
