-- src/meta/npcMeta.lua
--
-- Initially generated by `lua generate.lua meta` from Questie's npcKeys and
-- npcCompilerTypes in Database/npcDB.lua.
-- Last migration reference: Questie/Questie@454b9d072965ee8f1a881429260fcf1fac8d60f7.
-- See PROVENANCE.md for import history and the retired derivation tool.
--
-- Now maintained here: update field keys, storage behavior, and LuaLS declarations together.
-- compilerTypes preserves the original type names for provenance and public API compatibility.

local _, LibQuestieDB = ...

local meta = {
  entity = 'Npc',
  metaPrefix = 'Npc-',
  fieldCount = 15,

  --- fieldName -> fieldIndex. The Database Key Enum.
  keys = {
    -- Localized NPC name.
    ['name'] = 1,
    -- Deprecated health field; known NPCs return the compatibility placeholder 0.
    ['minLevelHealth'] = 2,
    -- Deprecated health field; known NPCs return the compatibility placeholder 1.
    ['maxLevelHealth'] = 3,
    -- Minimum NPC level.
    ['minLevel'] = 4,
    -- Maximum NPC level.
    ['maxLevel'] = 5,
    -- NPC rank; see https://github.com/cmangos/issues/wiki/creature_template#rank
    ['rank'] = 6,
    -- Spawn coordinates grouped by zone: {[zoneId] = {{x, y, phase?}, ...}}.
    ['spawns'] = 7,
    -- Movement paths grouped by zone: {[zoneId] = {{{x, y}, ...}, ...}}.
    ['waypoints'] = 8,
    -- Best estimate of the zone where this NPC is most common.
    ['zoneID'] = 9,
    -- IDs of quests started by this NPC.
    ['questStarts'] = 10,
    -- IDs of quests finished at this NPC.
    ['questEnds'] = 11,
    -- FactionTemplate ID; see https://github.com/cmangos/issues/wiki/FactionTemplate.dbc
    ['factionID'] = 12,
    -- Player factions this NPC is friendly to: A, H, AH, or nil when hostile to both.
    ['friendlyToFaction'] = 13,
    -- Localized NPC title or function, such as Weapon Vendor.
    ['subName'] = 14,
    -- Bitmask describing NPC functions such as vendor, trainer, or flight master.
    ['npcFlags'] = 15,
  },

  --- fieldIndex -> fieldName
  names = {
[1]='name', [2]='minLevelHealth', [3]='maxLevelHealth', [4]='minLevel', [5]='maxLevel', [6]='rank', [7]='spawns', [8]='waypoints', [9]='zoneID', [10]='questStarts', [11]='questEnds', [12]='factionID', [13]='friendlyToFaction', [14]='subName', [15]='npcFlags'
  },

  --- fieldIndex -> storage type: number | string | table
  types = {
[1]='string', [2]='number', [3]='number', [4]='number', [5]='number', [6]='number', [7]='table', [8]='table', [9]='number', [10]='table', [11]='table', [12]='number', [13]='string', [14]='string', [15]='number'
  },

  --- fieldIndex -> structural shape, for validators. nil for scalars.
  structures = {
[7]='spawnlist', [8]='waypointlist', [10]='idarray', [11]='idarray'
  },

  --- fieldIndex -> Questie compiler type. Materialized provenance.
  compilerTypes = {
[1]='u8string', [2]='u32', [3]='u32', [4]='u8', [5]='u8', [6]='u8', [7]='spawnlist', [8]='waypointlist', [9]='u16', [10]='u8u24array', [11]='u8u24array', [12]='u16', [13]='faction', [14]='u8string', [15]='u32'
  },

  --- fieldIndex -> true when an empty table must read back as nil
  emptyIsNil = {
[7]=true, [8]=true, [10]=true, [11]=true
  },

  --- fieldIndex -> true when {0,0} must read back as nil
  zeroPairIsNil = {

  },

  --- fieldIndex -> named normalizer
  normalize = {
[13]='faction'
  },

  --- fieldIndex -> placeholder returned without storing per-entity metadata
  constantValues = {
[2]=0, [3]=1
  },

  --- field indices carrying translations
  l10nFields = {1,14},
}

if LibQuestieDB then
  LibQuestieDB.Meta = LibQuestieDB.Meta or {}
  LibQuestieDB.Meta['Npc'] = meta
end

return meta
