-- src/meta/objectMeta.lua
--
-- Initially generated by `lua generate.lua meta` from Questie's objectKeys and
-- objectCompilerTypes in Database/objectDB.lua.
-- Last migration reference: Questie/Questie@454b9d072965ee8f1a881429260fcf1fac8d60f7.
-- See PROVENANCE.md for import history and the retired derivation tool.
--
-- Now maintained here: update field keys, storage behavior, and LuaLS declarations together.
-- compilerTypes preserves the original type names for provenance and public API compatibility.

local _, LibQuestieDB = ...

local meta = {
  entity = 'Object',
  metaPrefix = 'Object-',
  fieldCount = 7,

  --- fieldName -> fieldIndex. The Database Key Enum.
  keys = {
    -- Localized object name.
    ['name'] = 1,
    -- IDs of quests started by this object.
    ['questStarts'] = 2,
    -- IDs of quests finished at this object.
    ['questEnds'] = 3,
    -- Spawn coordinates grouped by zone: {[zoneId] = {{x, y, phase?}, ...}}.
    ['spawns'] = 4,
    -- Best estimate of the zone where this object is most common.
    ['zoneID'] = 5,
    -- Faction restriction mask used by spawn data.
    ['factionID'] = 6,
    -- Movement paths for objects attached to transports such as ships or zeppelins.
    ['waypoints'] = 7,
  },

  --- fieldIndex -> fieldName
  names = {
[1]='name', [2]='questStarts', [3]='questEnds', [4]='spawns', [5]='zoneID', [6]='factionID', [7]='waypoints'
  },

  --- fieldIndex -> storage type: number | string | table
  types = {
[1]='string', [2]='table', [3]='table', [4]='table', [5]='number', [6]='number', [7]='table'
  },

  --- fieldIndex -> structural shape, for validators. nil for scalars.
  structures = {
[2]='idarray', [3]='idarray', [4]='spawnlist', [7]='waypointlist'
  },

  --- fieldIndex -> Questie compiler type. Materialized provenance.
  compilerTypes = {
[1]='u8string', [2]='u8u24array', [3]='u8u24array', [4]='spawnlist', [5]='u16', [6]='u16', [7]='waypointlist'
  },

  --- fieldIndex -> true when an empty table must read back as nil
  emptyIsNil = {
[2]=true, [3]=true, [4]=true, [7]=true
  },

  --- fieldIndex -> true when {0,0} must read back as nil
  zeroPairIsNil = {

  },

  --- fieldIndex -> named normalizer
  normalize = {

  },

  --- field indices carrying translations
  l10nFields = {1},
}

if LibQuestieDB then
  LibQuestieDB.Meta = LibQuestieDB.Meta or {}
  LibQuestieDB.Meta['Object'] = meta
end

return meta
