-- src/meta/questMeta.lua
--
-- Initially generated by `lua generate.lua meta` from Questie's questKeys and
-- questCompilerTypes in Database/questDB.lua.
-- Last migration reference: Questie/Questie@454b9d072965ee8f1a881429260fcf1fac8d60f7.
-- See PROVENANCE.md for import history and the retired derivation tool.
--
-- Now maintained here: update field keys, storage behavior, and LuaLS declarations together.
-- compilerTypes preserves the original type names for provenance and public API compatibility.

local _, LibQuestieDB = ...

local meta = {
  entity = 'Quest',
  metaPrefix = 'Quest-',
  fieldCount = 36,

  --- fieldName -> fieldIndex. The Database Key Enum.
  keys = {
    -- Localized quest name.
    ['name'] = 1,
    -- Quest starters: {npcIds?, objectIds?, itemIds?}; known quests always return a table.
    ['startedBy'] = 2,
    -- Quest finishers: {npcIds?, objectIds?}; known quests always return a table.
    ['finishedBy'] = 3,
    -- Minimum player level.
    ['requiredLevel'] = 4,
    -- Quest level.
    ['questLevel'] = 5,
    -- Allowed-race bitmask.
    ['requiredRaces'] = 6,
    -- Allowed-class bitmask.
    ['requiredClasses'] = 7,
    -- Localized quest objective text lines.
    ['objectivesText'] = 8,
    -- Completion trigger: {text, spawn coordinates grouped by zone}.
    ['triggerEnd'] = 9,
    -- Six positional groups: creature, object, item, reputation, kill-credit, and spell; known quests always return a table.
    ['objectives'] = 10,
    -- ID of the item provided by the quest starter.
    ['sourceItemId'] = 11,
    -- IDs of grouped prerequisite quests.
    ['preQuestGroup'] = 12,
    -- IDs of alternative single prerequisite quests.
    ['preQuestSingle'] = 13,
    -- IDs of quests unlocked by this quest.
    ['childQuests'] = 14,
    -- IDs of quests in the same quest group.
    ['inGroupWith'] = 15,
    -- IDs of mutually exclusive quests.
    ['exclusiveTo'] = 16,
    -- Positive AreaTable ID or negative QuestSort ID.
    ['zoneOrSort'] = 17,
    -- Required profession pair: {skillId, value}.
    ['requiredSkill'] = 18,
    -- Minimum reputation pair: {factionId, value}.
    ['requiredMinRep'] = 19,
    -- Maximum reputation pair: {factionId, value}.
    ['requiredMaxRep'] = 20,
    -- Item IDs that are not objectives but are still needed for the quest.
    ['requiredSourceItems'] = 21,
    -- Quest that makes this quest unavailable once active or completed.
    ['nextQuestInChain'] = 22,
    -- Quest flag bitmask; see https://github.com/cmangos/issues/wiki/Quest_template#questflags
    ['questFlags'] = 23,
    -- Special flag bitmask: repeatable, event-gated, and monthly-reset flags.
    ['specialFlags'] = 24,
    -- Quest that must be active for this quest to be available.
    ['parentQuest'] = 25,
    -- Reputation rewards as {{factionId, value}, ...}.
    ['reputationReward'] = 26,
    -- ID of the quest this optional breadcrumb leads to.
    ['breadcrumbForQuestId'] = 27,
    -- IDs of breadcrumb quests that lead to this quest.
    ['breadcrumbs'] = 28,
    -- Hidden-objective rows: {{spawnList?, iconType, text?, objectiveIndex, references?}, ...}.
    ['extraObjectives'] = 29,
    -- Spell ID the character must know.
    ['requiredSpell'] = 30,
    -- Profession or specialization requirement ID.
    ['requiredSpecialization'] = 31,
    -- Maximum player level at which this quest is available.
    ['requiredMaxLevel'] = 32,
    -- Quest that must remain uncompleted for this quest to stay available.
    ['availableUntilCompleted'] = 33,
    -- Quest that must be active or completed for this quest to become available.
    ['availableStartingWith'] = 34,
    -- Alternative profession rank requirements as {{skillId, value}, ...}.
    ['requiredRanks'] = 35,
    -- Quest that temporarily disables this quest while active.
    ['disabledByQuest'] = 36,
  },

  --- fieldIndex -> fieldName
  names = {
[1]='name', [2]='startedBy', [3]='finishedBy', [4]='requiredLevel', [5]='questLevel', [6]='requiredRaces', [7]='requiredClasses', [8]='objectivesText', [9]='triggerEnd', [10]='objectives', [11]='sourceItemId', [12]='preQuestGroup', [13]='preQuestSingle', [14]='childQuests', [15]='inGroupWith', [16]='exclusiveTo', [17]='zoneOrSort', [18]='requiredSkill', [19]='requiredMinRep', [20]='requiredMaxRep', [21]='requiredSourceItems', [22]='nextQuestInChain', [23]='questFlags', [24]='specialFlags', [25]='parentQuest', [26]='reputationReward', [27]='breadcrumbForQuestId', [28]='breadcrumbs', [29]='extraObjectives', [30]='requiredSpell', [31]='requiredSpecialization', [32]='requiredMaxLevel', [33]='availableUntilCompleted', [34]='availableStartingWith', [35]='requiredRanks', [36]='disabledByQuest'
  },

  --- fieldIndex -> storage type: number | string | table
  types = {
[1]='string', [2]='table', [3]='table', [4]='number', [5]='number', [6]='number', [7]='number', [8]='table', [9]='table', [10]='table', [11]='number', [12]='table', [13]='table', [14]='table', [15]='table', [16]='table', [17]='number', [18]='table', [19]='table', [20]='table', [21]='table', [22]='number', [23]='number', [24]='number', [25]='number', [26]='table', [27]='number', [28]='table', [29]='table', [30]='number', [31]='number', [32]='number', [33]='number', [34]='number', [35]='table', [36]='number'
  },

  --- fieldIndex -> structural shape, for validators. nil for scalars.
  structures = {
[2]='questgivers', [3]='questgivers', [8]='stringarray', [9]='trigger', [10]='objectives', [12]='idarray', [13]='idarray', [14]='idarray', [15]='idarray', [16]='idarray', [18]='pair', [19]='pair', [20]='pair', [21]='idarray', [26]='pairs', [28]='idarray', [29]='extraobjectives', [35]='pairs'
  },

  --- fieldIndex -> Questie compiler type. Materialized provenance.
  compilerTypes = {
[1]='u8string', [2]='questgivers', [3]='questgivers', [4]='u8', [5]='s16', [6]='u32', [7]='u16', [8]='u8u16stringarray', [9]='trigger', [10]='objectives', [11]='u24', [12]='u8s24array', [13]='u8u24array', [14]='u8u24array', [15]='u8u24array', [16]='u8u24array', [17]='s16', [18]='u12pair', [19]='s24pair', [20]='s24pair', [21]='u8u24array', [22]='u24', [23]='u24', [24]='u16', [25]='u24', [26]='u8s24pairs', [27]='u24', [28]='u8u24array', [29]='extraobjectives', [30]='s24', [31]='u24', [32]='u8', [33]='u24', [34]='u24', [35]='u8s24pairs', [36]='u24'
  },

  --- fieldIndex -> true when an empty table must read back as nil
  emptyIsNil = {
[2]=true, [3]=true, [8]=true, [9]=true, [10]=true, [12]=true, [13]=true, [14]=true, [15]=true, [16]=true, [18]=true, [19]=true, [20]=true, [21]=true, [26]=true, [28]=true, [29]=true, [35]=true
  },

  --- fieldIndex -> true when {0,0} must read back as nil
  zeroPairIsNil = {
[18]=true, [19]=true, [20]=true
  },

  --- fieldIndex -> named normalizer
  normalize = {

  },

  --- field indices carrying translations
  l10nFields = {1,8},
}

if LibQuestieDB then
  LibQuestieDB.Meta = LibQuestieDB.Meta or {}
  LibQuestieDB.Meta['Quest'] = meta
end

return meta
