#!/usr/bin/env lua
-- generate.lua
--
-- Turns raw entity data plus Static Corrections into a TOC metadata store.
--
-- Usage:
--   lua generate.lua all                  every flavor
--   lua generate.lua Vanilla [TBC ...]    named flavors
--
-- Options:
--   --types=Quest,Npc      restrict entity types
--   --fields=name,zoneOrSort   restrict fields (tracer-bullet slices only)
--   --no-l10n              explicitly generate without localization
--   --no-base-toc          skip rewriting the committed base TOC (parallel-safe)
--   --quiet
--
-- QUESTIEDB_RELEASE=true uses the Source TOC's X.X.X version unchanged. Otherwise Baked
-- versions include -dev.<short commit>; Source TOC regeneration always preserves X.X.X.
--
-- Runs on a plain Lua 5.1 interpreter. No `lfs`, no other C dependency — inputs are
-- enumerated in src/config.lua rather than discovered by scanning directories, which keeps
-- the option of shipping a bare `lua` binary for contributors.

local config = dofile("src/config.lua")
local lib = dofile("generator/lib.lua")
local encode = dofile("generator/encode.lua")
local rows = dofile("generator/rows.lua")
local flavorLoader = dofile("generator/flavor.lua")
local l10nGen = dofile("generator/l10n.lua")
local version = dofile("generator/version.lua")

-- The correction manifest drives which files each TOC lists. It is optional: a bare data
-- round-trip works before any corrections are ported.
if lib.fileExists("src/corrections/manifest.lua") then
  config.correctionManifest = dofile("src/corrections/manifest.lua")
end

local generate = {}

--------------------------------------------------------------------------------------------
-- Arguments
--------------------------------------------------------------------------------------------

local function parseArgs(argv)
  local opts = { flavors = {}, types = nil, fields = nil, quiet = false, target = nil }
  for _, value in ipairs(argv) do
    local key, val = value:match("^%-%-([%w%-]+)=(.*)$")
    if value == "--help" or value == "-h" then
      lib.printUsage(arg[0])
    elseif key == "types" then
      opts.types = {}
      for name in val:gmatch("[^,]+") do opts.types[name] = true end
    elseif key == "fields" then
      opts.fields = {}
      for name in val:gmatch("[^,]+") do opts.fields[name] = true end
    elseif value == "--no-l10n" then
      opts.noL10n = true
    elseif value == "--no-base-toc" then
      opts.noBaseToc = true
    elseif value == "--quiet" then
      opts.quiet = true
    elseif value:sub(1, 2) == "--" then
      error("Unknown option: " .. value, 0)
    elseif value == "all" or value == "toc" then
      opts.target = value
    else
      opts.flavors[#opts.flavors + 1] = value
    end
  end
  return opts
end

local QUIET = false
local function say(...)
  if not QUIET then print(...) end
end

--------------------------------------------------------------------------------------------
-- TOC emission
--------------------------------------------------------------------------------------------

local BUILD

local function writeHeader(out, flavor, fileList)
  out:write("# GENERATED by `lua generate.lua ", flavor.name, "`. Do not edit, do not commit.\n")
  out:write("# Baked mode: entity reads resolve from the TOC metadata store below.\n")
  out:write("## Interface: ", flavor.interface, "\n")
  out:write("## Title: QuestieDB\n")
  out:write("## Notes: The database Questie consumes.\n")
  out:write("## Author: Code: Logonz Data: Muehe/TheCrux(BreakBB)/Drejjmit/Dyaxler/Cheeq/TechnoHunter/Yttrium/Everyone else\n")
  -- Rolling previews keep a commit in their visible version even though the release tag moves.
  out:write("## Version: ", BUILD.version, "\n")
  out:write("## Category: Quests\n")
  out:write("## Category-deDE: Quests\n")
  out:write("## Category-esES: Misiones\n")
  out:write("## Category-esMX: Misiones\n")
  out:write("## Category-frFR: Quêtes\n")
  out:write("## Category-itIT: Missioni\n")
  out:write("## Category-koKR: 퀘스트\n")
  out:write("## Category-ptBR: Missões\n") 
  out:write("## Category-ruRU: Задания\n") 
  out:write("## Category-zhCN: 任务\n")
  out:write("## Category-zhTW: 任務\n")
  out:write("## IconTexture: Interface\\AddOns\\QuestieDB\\icons\\QuestieTDB_64x64.png\n")
  out:write("## X-Contract-Version: ", tostring(config.contractVersion), "\n")
  out:write("## X-Flavor: ", flavor.name, "\n")
  out:write("## X-Mode: baked\n")
  out:write("## X-BUILD-COMMIT: ", BUILD.commit, "\n")
  out:write("## X-BUILD-TIME: ", BUILD.time, "\n")
  out:write("\n")
  for _, file in ipairs(fileList) do
    out:write(file:gsub("/", "\\"), "\n")
  end
  out:write("\n")
end

---@class SourceTocHeading
---@field category string? Start a top-level loading phase.
---@field subcategory string
---@field note string? Explain an ownership or ordering constraint.

---Presentation only: headings attach to existing paths without changing selection or order.
---@return table<string, SourceTocHeading>
local function sourceTocHeadings()
  local headings = {
    ["src/config.lua"] = { category = "Runtime foundation", subcategory = "Configuration, schema and codecs" },
    ["src/flavors/Vanilla.lua"] = { subcategory = "Native client selection",
      note = "Forever excludes legacy game types: an all-unknown allow list would also load on older clients." },
    [config.runtimeFiles.sourceReader] = { category = "Entity data", subcategory = "Loader setup",
      note = "Capture the selected flavor's deferred payloads; materialize them on first use." },
    ["data/_end.lua"] = { subcategory = "Loader teardown" },
    ["src/corrections/enum/constants.lua"] = { category = "Support data", subcategory = "Constants and loader setup" },
    ["support/Zones/dungeons.lua"] = { subcategory = "Shared legacy reference data" },
    ["support/Zones/areaIdToUiMapId.lua"] = { subcategory = "Zone maps: Vanilla through Cata" },
    ["support/QuestXP/xpDB-classic.lua"] = { subcategory = "Vanilla: quest XP, factions and drops" },
    ["support/QuestXP/xpDB-tbc.lua"] = { subcategory = "TBC: quest XP, factions and drops" },
    ["support/QuestXP/xpDB-wotlk.lua"] = { subcategory = "Wrath: quest XP, factions and drops" },
    ["support/Zones/MoP/areaIdToUiMapId.lua"] = { subcategory = "Mists: zone maps, quest XP, factions and drops" },
    ["support/DropTables/cataItemDrops.lua"] = { subcategory = "Cata drops, also used by Mists",
      note = "Mists loads its own drop table first, then the Cata table." },
    ["support/QuestXP/xpDB-cata.lua"] = { subcategory = "Cata: quest XP and factions" },
    ["support/Forever/Zones/dungeons.lua"] = { subcategory = "Forever: independently owned support inputs" },
    ["src/support/_end.lua"] = { subcategory = "Loader teardown" },
    ["src/read/shared.lua"] = { category = "Corrections", subcategory = "Shared readers and Correction registry" },
    ["src/corrections/compat.lua"] = { subcategory = "Provider loader setup" },
    ["src/corrections/Era/classicQuestFixes.lua"] = { subcategory = "Era providers",
      note = "Base Corrections are cumulative across legacy flavors; reputation applies only to Vanilla." },
    ["src/corrections/Tbc/tbcQuestFixes.lua"] = { subcategory = "TBC providers: TBC and later legacy flavors" },
    ["src/corrections/Wotlk/wotlkQuestFixes.lua"] = { subcategory = "Wrath providers: Wrath and later legacy flavors" },
    ["src/corrections/scopes/Titan.lua"] = { subcategory = "Titan Reforged: Wrath season 109",
      note = "Scope markers retain the runtime season gate for load-time objective hints." },
    ["src/corrections/Cata/cataQuestFixes.lua"] = { subcategory = "Cata providers: Cata and Mists" },
    ["src/corrections/MoP/mopQuestFixes.lua"] = { subcategory = "Mists providers" },
    ["src/corrections/scopes/Sod.lua"] = { subcategory = "Season of Discovery: Vanilla season 2",
      note = "Never applied to Forever. The season gate remains in Lua." },
    ["src/corrections/Shared/itemStartFixes.lua"] = { subcategory = "Shared legacy Item-start Corrections" },
    ["src/corrections/Forever/legacy/classicQuestFixes.lua"] = { subcategory = "Forever: inherited baseline",
      note = "Owned copies, not live Era or Shared providers. Add new work in forever*Fixes.lua." },
    ["src/corrections/Forever/foreverQuestFixes.lua"] = { subcategory = "Forever: authored corrections",
      note = "Apply after the baseline within each Static/Dynamic category." },
    ["src/corrections/manifest.lua"] = { subcategory = "Provider registration and loader teardown" },
    ["src/corrections/Sod/sodRequiredRaces.lua"] = { subcategory = "Season of Discovery: required-race overlay" },
    ["src/derived/registry.lua"] = { category = "Derived passes", subcategory = "Registry and loader setup" },
    ["src/derived/RamerDouglasPeucker.lua"] = { subcategory = "Shared algorithms",
      note = "Run over corrected data, using the selected flavor's owned support inputs." },
    ["src/derived/_end.lua"] = { subcategory = "Loader teardown" },
    ["src/l10n/overlay.lua"] = { category = "Localization and public API", subcategory = "Localization overlay and Titan translations",
      note = "Do not filter by client locale: SetLocale() can select another locale." },
    ["src/ui/modeIndicator.lua"] = { subcategory = "Source-mode indicator" },
    ["src/api.lua"] = { subcategory = "Public API" },
  }
  for _, flavor in ipairs(config.flavors) do
    headings[config.dataPath(flavor, config.entityTypes[1])] = { subcategory = flavor.name }
  end
  return headings
end

--- Write the committed base TOC, which is what the client falls back to when no suffixed TOC
--- matches — and therefore what selects Source mode, at no cost.
---@return nil
function generate.baseToc()
  local path = config.addonName .. ".toc"
  -- The version is maintained in this file, not regenerated. Read it before truncation.
  local sourceVersion = version.read(path)
  local out = assert(io.open(path, "wb"), "Cannot write " .. path)
  out:write("# GENERATED by `lua generate.lua toc`, and COMMITTED.\n")
  out:write("# Source mode: entity reads resolve from raw entity data in data/.\n")
  out:write("#\n")
  out:write("# The client searches for flavour-suffixed TOCs first and uses this one only if\n")
  out:write("# none are found, so a generated artifact wins simply by existing. A fresh clone\n")
  out:write("# has no suffixed TOC, which is what makes it a working dev environment.\n")
  out:write("\n# =============================================================================\n")
  out:write("# Addon metadata\n")
  out:write("# =============================================================================\n\n")
  out:write("## Interface: ", config.allInterfaceVersions(), "\n")
  out:write("## Title: QuestieDB\n")
  out:write("## Notes: |cFFFFD100(source mode)|r The database Questie consumes. No generated artifact present.\n")
  out:write("## Author: Code: Logonz Data: Muehe/TheCrux(BreakBB)/Drejjmit/Dyaxler/Cheeq/TechnoHunter/Yttrium/Everyone else\n")
  -- Rolling previews keep a commit in their visible version even though the release tag moves.
  out:write("## Version: ", sourceVersion, "\n")
  out:write("## Category: Quests\n")
  out:write("## Category-deDE: Quests\n")
  out:write("## Category-esES: Misiones\n")
  out:write("## Category-esMX: Misiones\n")
  out:write("## Category-frFR: Quêtes\n")
  out:write("## Category-itIT: Missioni\n")
  out:write("## Category-koKR: 퀘스트\n")
  out:write("## Category-ptBR: Missões\n") 
  out:write("## Category-ruRU: Задания\n") 
  out:write("## Category-zhCN: 任务\n")
  out:write("## Category-zhTW: 任務\n")
  out:write("## IconTexture: Interface\\AddOns\\QuestieDB\\icons\\QuestieTDB_64x64.png\n")
  out:write("## X-Contract-Version: ", tostring(config.contractVersion), "\n")
  out:write("## X-Mode: source\n")
  local files, entries, headings = config.sourceFileList(), config.sourceFileEntries(), sourceTocHeadings()
  for index, file in ipairs(files) do
    local heading = headings[entries[index].path]
    if heading then
      if heading.category then
        out:write("\n# =============================================================================\n")
        out:write("# ", heading.category, "\n")
        out:write("# =============================================================================\n")
      end
      out:write("\n# --- ", heading.subcategory, " ---\n")
      if heading.note then out:write("# ", heading.note, "\n") end
    end
    out:write(file:gsub("/", "\\"), "\n")
  end
  out:close()
  say(string.format("Generated %s (%d files, source mode)", path, #files))
end

---Emit every metadata line for one entity type.
---@param out file* Open artifact handle.
---@param meta table Entity metadata.
---@param entities table<number, table> Composed Generation rows by entity ID.
---@param fieldFilter table<string, boolean>? Optional tracer-bullet field selection.
---@return number entityCount
---@return table stats Scalar-row, table-field, byte, and line counts.
local function writeEntityMetadata(out, meta, entities, fieldFilter)
  local ids = lib.sortedIds(entities)
  local stats = { rows = 0, tableFields = 0, rowBytes = 0, tableBytes = 0, lines = 0 }
  local prefix = "X-" .. meta.metaPrefix

  for _, id in ipairs(ids) do
    local sourceRow = entities[id]
    local key = prefix .. id .. "-"

    -- Table fields retain one metadata key each. Write them before the scalar row so the
    -- artifact's entity records have a stable, easy-to-scan order.
    for fieldIndex = 1, meta.fieldCount do
      if meta.types[fieldIndex] == "table" and
         (not fieldFilter or fieldFilter[meta.names[fieldIndex]]) then
        local ok, encoded = pcall(encode.field, meta, fieldIndex, sourceRow[fieldIndex])
        if not ok then
          error(string.format("%s id %d: %s", meta.entity, id, tostring(encoded)), 0)
        end
        if encoded ~= nil then
          stats.lines = stats.lines +
            lib.writeMetadata(out, key .. fieldIndex, encoded, config.maxValueLength)
          stats.tableFields = stats.tableFields + 1
          stats.tableBytes = stats.tableBytes + #encoded
        end
      end
    end

    local ok, scalarRow = pcall(rows.build, meta, sourceRow, fieldFilter)
    if not ok then error(string.format("%s id %d: %s", meta.entity, id, tostring(scalarRow)), 0) end
    if scalarRow then
      local encoded = encode.row(scalarRow)
      stats.lines = stats.lines + lib.writeMetadata(out, key .. "S", encoded, config.maxValueLength)
      stats.rows = stats.rows + 1
      stats.rowBytes = stats.rowBytes + #encoded
    end
  end

  local encodedIds = encode.idList(ids)
  stats.lines = stats.lines +
    lib.writeMetadata(out, prefix .. "IDS", encodedIds, config.maxValueLength)
  stats.idBytes = #encodedIds
  return #ids, stats
end

--------------------------------------------------------------------------------------------
-- Driver
--------------------------------------------------------------------------------------------

--- Load every entity type for one flavor, apply Static Corrections, and return the tables.
--- Shared with verify.lua so both see identical corrected data.
function generate.loadFlavor(flavor, typeFilter, applyCorrections)
  return flavorLoader.load(flavor, typeFilter, applyCorrections)
end

function generate.flavor(flavor, opts)
  local started = os.clock()
  local loaded, stats = generate.loadFlavor(flavor, opts.types)
  if stats.applied > 0 then
    say(string.format("  corrections: %d values from %d registered functions across %d files",
      stats.applied, stats.corrections and stats.corrections.registered or 0,
      stats.corrections and stats.corrections.files or 0))
  end

  -- A Lua number represents every possible Presence mask through field 52 exactly.
  -- Reject a wider schema before opening the artifact so a failed run leaves no partial TOC.
  for _, entry in pairs(loaded) do
    if entry.meta.fieldCount > 52 then
      error(("%s schema has %d fields; the presence mask supports at most 52")
        :format(entry.meta.entity, entry.meta.fieldCount), 0)
    end
  end

  local tocPath = config.tocPath(flavor)
  local out = assert(io.open(tocPath, "wb"), "Cannot write " .. tocPath)
  writeHeader(out, flavor, config.bakedFileList(flavor))

  local totals = { entities = 0, fields = 0, rows = 0, lines = 0, entityBytes = 0 }
  for _, entityType in ipairs(config.entityTypes) do
    local entry = loaded[entityType.name]
    if entry then
      local entityCount, typeStats =
        writeEntityMetadata(out, entry.meta, entry.entities, opts.fields)
      totals.entities = totals.entities + entityCount
      totals.fields = totals.fields + typeStats.tableFields + typeStats.rows
      totals.rows = totals.rows + typeStats.rows
      totals.lines = totals.lines + typeStats.lines
      totals.entityBytes = totals.entityBytes + typeStats.rowBytes +
        typeStats.tableBytes + typeStats.idBytes
      say(string.format(
        "  %-7s %6d entities  %6d rows  %7.1f KB rows+ids  %7.1f KB tables",
        entityType.name, entityCount, typeStats.rows,
        (typeStats.rowBytes + typeStats.idBytes) / 1024, typeStats.tableBytes / 1024))
    elseif opts.types and not opts.types[entityType.name] then
      -- The runtime always constructs all four Entity globals. A type-filtered tracer artifact
      -- therefore carries an empty header for each omitted backend rather than looking corrupt.
      local encodedIds = encode.idList({})
      totals.lines = totals.lines + lib.writeMetadata(out,
        "X-" .. entityType.metaPrefix .. "IDS", encodedIds, config.maxValueLength)
      totals.entityBytes = totals.entityBytes + #encodedIds
      say(string.format("  %-7s %6d entities  %6d rows  (omitted)", entityType.name, 0, 0))
    else
      error("Generation loaded no " .. entityType.name .. " data for " .. flavor.name, 0)
    end
  end

  out:close()

  -- Localization follows entity data as compressed CBOR columns. A non-enUS client eagerly
  -- decodes its available type blocks; enUS keeps localization out of the Lua heap.
  if not opts.noL10n then
    out = assert(io.open(tocPath, "ab"), "Cannot append to " .. tocPath)
    totals.lines = totals.lines + l10nGen.writeHeader(out)
    for _, entityType in ipairs(config.entityTypes) do
      local entry = loaded[entityType.name]
      if entry then
        local ids = lib.sortedIds(entry.entities)
        local knownIds = {}
        for _, id in ipairs(ids) do knownIds[id] = true end
        local values, extractStats = l10nGen.extract(
          config.paths.l10n, flavor, entityType.name, knownIds)
        local blockStats = l10nGen.writeMetadata(out, entityType.name, values, ids)
        totals.lines = totals.lines + blockStats.lines
        totals.l10nBytes = (totals.l10nBytes or 0) + blockStats.bytes
        say(string.format(
          "  l10n %-7s %6d entities  %2d blocks  %7.1f KB  (%d locales, %d filtered)",
          entityType.name, extractStats.entries, blockStats.blocks,
          blockStats.bytes / 1024, extractStats.locales, extractStats.filtered))
        values = nil
        collectgarbage()
      end
    end
    out:close()
  end

  -- Compatibility names are byte copies of the finished artifact, including Localization.
  for _, suffix in ipairs(flavor.aliases or {}) do
    lib.writeAll(config.addonName .. suffix .. ".toc", lib.readAll(tocPath))
  end

  local size = lib.fileSize(tocPath)
  say(string.format("Generated %s — %d entities, %d rows, %.1f MB entity data, %.1f MB total, %.1fs",
    tocPath, totals.entities, totals.rows, totals.entityBytes / 1048576,
    size / 1048576, os.clock() - started))
  return totals
end

--------------------------------------------------------------------------------------------
-- Entry point
--------------------------------------------------------------------------------------------

local opts = parseArgs(arg or {})
QUIET = opts.quiet
BUILD = {
  commit = lib.gitCommit(),
  time = lib.buildTime(),
}
BUILD.version = version.baked(version.read(config.addonName .. ".toc"),
  BUILD.commit, os.getenv("QUESTIEDB_RELEASE"))

if opts.target == "toc" then
  generate.baseToc()
  os.exit(0)
end

local flavors = {}
if opts.target == "all" or #opts.flavors == 0 then
  flavors = config.flavors
else
  for _, name in ipairs(opts.flavors) do
    local flavor = config.flavorByName[name]
    if not flavor then
      error("Unknown flavor: " .. name .. ". Known: Vanilla, TBC, Wrath, Cata, Mists, Forever", 0)
    end
    flavors[#flavors + 1] = flavor
  end
end

-- Missing localization input must fail before either TOC is opened. `--no-l10n` is the only
-- supported way to request a partial artifact.
if not opts.noL10n then
  l10nGen.assertInputs(config.paths.l10n, flavors, opts.types)
end

-- The base TOC is not flavour-scoped, so every invocation would rewrite the same file. That is
-- harmless sequentially and a race when flavours are generated in parallel (tools/cli/questiedb.py),
-- which writes it once up front and then passes --no-base-toc.
if not opts.noBaseToc then
  generate.baseToc()
end

for _, flavor in ipairs(flavors) do
  generate.flavor(flavor, opts)
end
