---@class LibQuestieDB
local LibQuestieDB = select(2, ...)

--- Imports
local Corrections = LibQuestieDB.Corrections
local Meta = LibQuestieDB.Meta
local ItemMeta = Meta.ItemMeta

---@class ItemFixesEra
local ItemFixes = {}

C_Timer.After(0, function()
  Corrections.RegisterCorrectionStatic("item",
                                       "ItemFixes-QuestStarts-Era-Automatic",
                                       ItemFixes.LoadItemQuestStarts,
                                       Corrections.EraBaseStaticOrder + 9)

  -- Clear the table to save memory
  ItemFixes = wipe(ItemFixes)
end)

---@return table<ItemId, Correction[]>>
function ItemFixes.LoadItemQuestStarts()
  local itemKeys = ItemMeta.itemKeys

  --! This file is automatically generated from wowhead data by looking at all items that starts a quest and correcting it.
  return {
    --* Item 1307 https://classic.wowhead.com/classic/item=1307
    --* Starts: The Collector(123)(https://classic.wowhead.com/classic/quest=123)
    [1307] = {
      [itemKeys.startQuest] = 123,
    },
    --* Item 1357 https://classic.wowhead.com/classic/item=1357
    --* Starts: Captain Sanders' Hidden Treasure(136)(https://classic.wowhead.com/classic/quest=136)
    [1357] = {
      [itemKeys.startQuest] = 136,
    },
    --* Item 1962 https://classic.wowhead.com/classic/item=1962
    --* Starts: Theocritus' Retrieval(178)(https://classic.wowhead.com/classic/quest=178)
    [1962] = {
      [itemKeys.startQuest] = 178,
    },
    --* Item 1972 https://classic.wowhead.com/classic/item=1972
    --* Starts: Furlbrow's Deed(184)(https://classic.wowhead.com/classic/quest=184)
    [1972] = {
      [itemKeys.startQuest] = 184,
    },
    --* Item 2794 https://classic.wowhead.com/classic/item=2794
    --* Starts: An Old History Book(337)(https://classic.wowhead.com/classic/quest=337)
    [2794] = {
      [itemKeys.startQuest] = 337,
    },
    --* Item 2839 https://classic.wowhead.com/classic/item=2839
    --* Starts: A Letter Undelivered(361)(https://classic.wowhead.com/classic/quest=361)
    [2839] = {
      [itemKeys.startQuest] = 361,
    },
    --* Item 2874 https://classic.wowhead.com/classic/item=2874
    --* Starts: The Unsent Letter(373)(https://classic.wowhead.com/classic/quest=373)
    [2874] = {
      [itemKeys.startQuest] = 373,
    },
    --* Item 3317 https://classic.wowhead.com/classic/item=3317
    --* Starts: Resting in Pieces(460)(https://classic.wowhead.com/classic/quest=460)
    [3317] = {
      [itemKeys.startQuest] = 460,
    },
    --* Item 3668 https://classic.wowhead.com/classic/item=3668
    --* Starts: Assassin's Contract(522)(https://classic.wowhead.com/classic/quest=522)
    [3668] = {
      [itemKeys.startQuest] = 522,
    },
    --* Item 3706 https://classic.wowhead.com/classic/item=3706
    --* Starts: The Ensorcelled Parchment(551)(https://classic.wowhead.com/classic/quest=551)
    [3706] = {
      [itemKeys.startQuest] = 551,
    },
    --* Item 3985 https://classic.wowhead.com/classic/item=3985
    --* Starts: The Monogrammed Sash(8552)(https://classic.wowhead.com/classic/quest=8552)
    [3985] = {
      [itemKeys.startQuest] = 8552,
    },
    --* Item 4056 https://classic.wowhead.com/classic/item=4056
    --* Starts: Cortello's Riddle(624)(https://classic.wowhead.com/classic/quest=624)
    [4056] = {
      [itemKeys.startQuest] = 624,
    },
    --* Item 4098 https://classic.wowhead.com/classic/item=4098
    --* Starts: Message in a Bottle(594)(https://classic.wowhead.com/classic/quest=594)
    [4098] = {
      [itemKeys.startQuest] = 594,
    },
    --* Item 4433 https://classic.wowhead.com/classic/item=4433
    --* Starts: Sully Balloo's Letter(637)(https://classic.wowhead.com/classic/quest=637)
    [4433] = {
      [itemKeys.startQuest] = 637,
    },
    --* Item 4613 https://classic.wowhead.com/classic/item=4613
    --* Starts: The Black Box(708)(https://classic.wowhead.com/classic/quest=708)
    [4613] = {
      [itemKeys.startQuest] = 708,
    },
    --* Item 4614 https://classic.wowhead.com/classic/item=4614
    --* Starts: Crystal in the Mountains(635)(https://classic.wowhead.com/classic/quest=635)
    [4614] = {
      [itemKeys.startQuest] = 635,
    },
    --* Item 4854 https://classic.wowhead.com/classic/item=4854
    --* Starts: The Demon Scarred Cloak(770)(https://classic.wowhead.com/classic/quest=770)
    [4854] = {
      [itemKeys.startQuest] = 770,
    },
    --* Item 4881 https://classic.wowhead.com/classic/item=4881
    --* Starts: The Admiral's Orders(830)(https://classic.wowhead.com/classic/quest=830)
    [4881] = {
      [itemKeys.startQuest] = 830,
    },
    --* Item 4903 https://classic.wowhead.com/classic/item=4903
    --* Starts: Burning Shadows(832)(https://classic.wowhead.com/classic/quest=832)
    [4903] = {
      [itemKeys.startQuest] = 832,
    },
    --* Item 4926 https://classic.wowhead.com/classic/item=4926
    --* Starts: Chen's Empty Keg(819)(https://classic.wowhead.com/classic/quest=819)
    [4926] = {
      [itemKeys.startQuest] = 819,
    },
    --* Item 5099 https://classic.wowhead.com/classic/item=5099
    --* Starts: Lakota'mani(883)(https://classic.wowhead.com/classic/quest=883)
    [5099] = {
      [itemKeys.startQuest] = 883,
    },
    --* Item 5102 https://classic.wowhead.com/classic/item=5102
    --* Starts: Owatanka(884)(https://classic.wowhead.com/classic/quest=884)
    [5102] = {
      [itemKeys.startQuest] = 884,
    },
    --* Item 5103 https://classic.wowhead.com/classic/item=5103
    --* Starts: Washte Pawne(885)(https://classic.wowhead.com/classic/quest=885)
    [5103] = {
      [itemKeys.startQuest] = 885,
    },
    --* Item 5138 https://classic.wowhead.com/classic/item=5138
    --* Starts: The Harvester(897)(https://classic.wowhead.com/classic/quest=897)
    [5138] = {
      [itemKeys.startQuest] = 897,
    },
    --* Item 5179 https://classic.wowhead.com/classic/item=5179
    --* Starts: The Moss-twined Heart(927)(https://classic.wowhead.com/classic/quest=927)
    [5179] = {
      [itemKeys.startQuest] = 927,
    },
    --* Item 5352 https://classic.wowhead.com/classic/item=5352
    --* Starts: The Powers Below(968)(https://classic.wowhead.com/classic/quest=968)
    [5352] = {
      [itemKeys.startQuest] = 968,
    },
    --* Item 5791 https://classic.wowhead.com/classic/item=5791
    --* Starts: Lonebrow's Journal(1100)(https://classic.wowhead.com/classic/quest=1100)
    [5791] = {
      [itemKeys.startQuest] = 1100,
    },
    --* Item 5877 https://classic.wowhead.com/classic/item=5877
    --* Starts: Parts of the Swarm(1148)(https://classic.wowhead.com/classic/quest=1148)
    [5877] = {
      [itemKeys.startQuest] = 1148,
    },
    --* Item 6172 https://classic.wowhead.com/classic/item=6172
    --* Starts: The Lost Supplies(1423)(https://classic.wowhead.com/classic/quest=1423)
    [6172] = {
      [itemKeys.startQuest] = 1423,
    },
    --* Item 6196 https://classic.wowhead.com/classic/item=6196
    --* Starts: Noboru the Cudgel(1392)(https://classic.wowhead.com/classic/quest=1392)
    [6196] = {
      [itemKeys.startQuest] = 1392,
    },
    --* Item 6497 https://classic.wowhead.com/classic/item=6497
    --* Starts: Kanrethad's Quest(1)(https://classic.wowhead.com/classic/quest=1)
    [6497] = {
      [itemKeys.startQuest] = 1,
    },
    --* Item 6766 https://classic.wowhead.com/classic/item=6766
    --* Starts: The Corrupter(1480)(https://classic.wowhead.com/classic/quest=1480)
    [6766] = {
      [itemKeys.startQuest] = 1480,
    },
    --* Item 6775 https://classic.wowhead.com/classic/item=6775
    --* Starts: The Tome of Divinity(1642)(https://classic.wowhead.com/classic/quest=1642)
    [6775] = {
      [itemKeys.startQuest] = 1642,
    },
    --* Item 6776 https://classic.wowhead.com/classic/item=6776
    --* Starts: The Tome of Valor(1649)(https://classic.wowhead.com/classic/quest=1649)
    [6776] = {
      [itemKeys.startQuest] = 1649,
    },
    --* Item 6916 https://classic.wowhead.com/classic/item=6916
    --* Starts: The Tome of Divinity(1646)(https://classic.wowhead.com/classic/quest=1646)
    [6916] = {
      [itemKeys.startQuest] = 1646,
    },
    --* Item 7666 https://classic.wowhead.com/classic/item=7666
    --* Starts: The Shattered Necklace(2198)(https://classic.wowhead.com/classic/quest=2198)
    [7666] = {
      [itemKeys.startQuest] = 2198,
    },
    --* Item 8524 https://classic.wowhead.com/classic/item=8524
    --* Starts: Tanaris Field Sampling(654)(https://classic.wowhead.com/classic/quest=654)
    [8524] = {
      [itemKeys.startQuest] = 654,
    },
    --* Item 8623 https://classic.wowhead.com/classic/item=8623
    --* Starts: Find OOX-17/TN!(351)(https://classic.wowhead.com/classic/quest=351)
    [8623] = {
      [itemKeys.startQuest] = 351,
    },
    --* Item 8704 https://classic.wowhead.com/classic/item=8704
    --* Starts: Find OOX-09/HL!(485)(https://classic.wowhead.com/classic/quest=485)
    [8704] = {
      [itemKeys.startQuest] = 485,
    },
    --* Item 8705 https://classic.wowhead.com/classic/item=8705
    --* Starts: Find OOX-22/FE!(2766)(https://classic.wowhead.com/classic/quest=2766)
    [8705] = {
      [itemKeys.startQuest] = 2766,
    },
    --* Item 9250 https://classic.wowhead.com/classic/item=9250
    --* Starts: Ship Schedules(2876)(https://classic.wowhead.com/classic/quest=2876)
    [9250] = {
      [itemKeys.startQuest] = 2876,
    },
    --* Item 9254 https://classic.wowhead.com/classic/item=9254
    --* Starts: Cuergo's Gold(2882)(https://classic.wowhead.com/classic/quest=2882)
    [9254] = {
      [itemKeys.startQuest] = 2882,
    },
    --* Item 9326 https://classic.wowhead.com/classic/item=9326
    --* Starts: Grime-Encrusted Ring(2945)(https://classic.wowhead.com/classic/quest=2945)
    [9326] = {
      [itemKeys.startQuest] = 2945,
    },
    --* Item 9370 https://classic.wowhead.com/classic/item=9370
    --* Starts: The Gordunni Scroll(2978)(https://classic.wowhead.com/classic/quest=2978)
    [9370] = {
      [itemKeys.startQuest] = 2978,
    },
    --* Item 10000 https://classic.wowhead.com/classic/item=10000
    --* Starts: The Horn of the Beast(3181)(https://classic.wowhead.com/classic/quest=3181)
    [10000] = {
      [itemKeys.startQuest] = 3181,
    },
    --* Item 10441 https://classic.wowhead.com/classic/item=10441
    --* Starts: The Glowing Shard(6981)(https://classic.wowhead.com/classic/quest=6981)
    [10441] = {
      [itemKeys.startQuest] = 6981,
    },
    --* Item 10454 https://classic.wowhead.com/classic/item=10454
    --* Starts: The Essence of Eranikus(3373)(https://classic.wowhead.com/classic/quest=3373)
    [10454] = {
      [itemKeys.startQuest] = 3373,
    },
    --* Item 10589 https://classic.wowhead.com/classic/item=10589
    --* Starts: The Essence of Eranikus(3374)(https://classic.wowhead.com/classic/quest=3374)
    [10589] = {
      [itemKeys.startQuest] = 3374,
    },
    --* Item 10590 https://classic.wowhead.com/classic/item=10590
    --* Starts: <NYI> <TXT> The Pocked Black Box(3482)(https://classic.wowhead.com/classic/quest=3482)
    [10590] = {
      [itemKeys.startQuest] = 3482,
    },
    --* Item 10621 https://classic.wowhead.com/classic/item=10621
    --* Starts: The Runed Scroll(3513)(https://classic.wowhead.com/classic/quest=3513)
    [10621] = {
      [itemKeys.startQuest] = 3513,
    },
    --* Item 11116 https://classic.wowhead.com/classic/item=11116
    --* Starts: Williden's Journal(3884)(https://classic.wowhead.com/classic/quest=3884)
    [11116] = {
      [itemKeys.startQuest] = 3884,
    },
    --* Item 11463 https://classic.wowhead.com/classic/item=11463
    --* Starts: Thalanaar Delivery(4281)(https://classic.wowhead.com/classic/quest=4281)
    [11463] = {
      [itemKeys.startQuest] = 4281,
    },
    --* Item 11668 https://classic.wowhead.com/classic/item=11668
    --* Starts: Flute of Xavaric(939)(https://classic.wowhead.com/classic/quest=939)
    [11668] = {
      [itemKeys.startQuest] = 939,
    },
    --* Item 11818 https://classic.wowhead.com/classic/item=11818
    --* Starts: The Key to Freedom(4451)(https://classic.wowhead.com/classic/quest=4451)
    [11818] = {
      [itemKeys.startQuest] = 4451,
    },
    --* Item 12558 https://classic.wowhead.com/classic/item=12558
    --* Starts: Guarding Secrets(4882)(https://classic.wowhead.com/classic/quest=4882)
    [12558] = {
      [itemKeys.startQuest] = 4882,
    },
    --* Item 12563 https://classic.wowhead.com/classic/item=12563
    --* Starts: Warlord's Command(4903)(https://classic.wowhead.com/classic/quest=4903)
    [12563] = {
      [itemKeys.startQuest] = 4903,
    },
    --* Item 12564 https://classic.wowhead.com/classic/item=12564
    --* Starts: Assassination Plot(4881)(https://classic.wowhead.com/classic/quest=4881)
    [12564] = {
      [itemKeys.startQuest] = 4881,
    },
    --* Item 12771 https://classic.wowhead.com/classic/item=12771
    --* Starts: Winterfall Firewater(5083)(https://classic.wowhead.com/classic/quest=5083)
    [12771] = {
      [itemKeys.startQuest] = 5083,
    },
    --* Item 12780 https://classic.wowhead.com/classic/item=12780
    --* Starts: General Drakkisath's Command(5089)(https://classic.wowhead.com/classic/quest=5089)
    [12780] = {
      [itemKeys.startQuest] = 5089,
    },
    --* Item 12842 https://classic.wowhead.com/classic/item=12842
    --* Starts: The Final Piece(5123)(https://classic.wowhead.com/classic/quest=5123)
    [12842] = {
      [itemKeys.startQuest] = 5123,
    },
    --* Item 13140 https://classic.wowhead.com/classic/item=13140
    --* Starts: A Strange Red Key(5202)(https://classic.wowhead.com/classic/quest=5202)
    [13140] = {
      [itemKeys.startQuest] = 5202,
    },
    --* Item 13250 https://classic.wowhead.com/classic/item=13250
    --* Starts: The Truth Comes Crashing Down(5262)(https://classic.wowhead.com/classic/quest=5262)
    [13250] = {
      [itemKeys.startQuest] = 5262,
    },
    --* Item 13920 https://classic.wowhead.com/classic/item=13920
    --* Starts: Healthy Dragon Scale(5582)(https://classic.wowhead.com/classic/quest=5582)
    [13920] = {
      [itemKeys.startQuest] = 5582,
    },
    --* Item 14646 https://classic.wowhead.com/classic/item=14646
    --* Starts: Welcome!(5805)(https://classic.wowhead.com/classic/quest=5805)
    [14646] = {
      [itemKeys.startQuest] = 5805,
    },
    --* Item 14647 https://classic.wowhead.com/classic/item=14647
    --* Starts: Welcome!(5841)(https://classic.wowhead.com/classic/quest=5841)
    [14647] = {
      [itemKeys.startQuest] = 5841,
    },
    --* Item 14648 https://classic.wowhead.com/classic/item=14648
    --* Starts: Welcome!(5842)(https://classic.wowhead.com/classic/quest=5842)
    [14648] = {
      [itemKeys.startQuest] = 5842,
    },
    --* Item 14649 https://classic.wowhead.com/classic/item=14649
    --* Starts: Welcome!(5843)(https://classic.wowhead.com/classic/quest=5843)
    [14649] = {
      [itemKeys.startQuest] = 5843,
    },
    --* Item 14650 https://classic.wowhead.com/classic/item=14650
    --* Starts: Welcome!(5844)(https://classic.wowhead.com/classic/quest=5844)
    [14650] = {
      [itemKeys.startQuest] = 5844,
    },
    --* Item 14651 https://classic.wowhead.com/classic/item=14651
    --* Starts: Welcome!(5847)(https://classic.wowhead.com/classic/quest=5847)
    [14651] = {
      [itemKeys.startQuest] = 5847,
    },
    --* Item 16303 https://classic.wowhead.com/classic/item=16303
    --* Starts: Ursangous's Paw(23)(https://classic.wowhead.com/classic/quest=23)
    [16303] = {
      [itemKeys.startQuest] = 23,
    },
    --* Item 16304 https://classic.wowhead.com/classic/item=16304
    --* Starts: Shadumbra's Head(24)(https://classic.wowhead.com/classic/quest=24)
    [16304] = {
      [itemKeys.startQuest] = 24,
    },
    --* Item 16305 https://classic.wowhead.com/classic/item=16305
    --* Starts: Sharptalon's Claw(2)(https://classic.wowhead.com/classic/quest=2)
    [16305] = {
      [itemKeys.startQuest] = 2,
    },
    --* Item 16408 https://classic.wowhead.com/classic/item=16408
    --* Starts: The Befouled Element(1918)(https://classic.wowhead.com/classic/quest=1918)
    [16408] = {
      [itemKeys.startQuest] = 1918,
    },
    --* Item 16782 https://classic.wowhead.com/classic/item=16782
    --* Starts: Baron Aquanis(6922)(https://classic.wowhead.com/classic/quest=6922)
    [16782] = {
      [itemKeys.startQuest] = 6922,
    },
    --* Item 16790 https://classic.wowhead.com/classic/item=16790
    --* Starts: Allegiance to the Old Gods(6564)(https://classic.wowhead.com/classic/quest=6564)
    [16790] = {
      [itemKeys.startQuest] = 6564,
    },
    --* Item 17008 https://classic.wowhead.com/classic/item=17008
    --* Starts: An Unholy Alliance(6522)(https://classic.wowhead.com/classic/quest=6522)
    [17008] = {
      [itemKeys.startQuest] = 6522,
    },
    --* Item 17115 https://classic.wowhead.com/classic/item=17115
    --* Starts: Deeprun Rat Roundup(6661)(https://classic.wowhead.com/classic/quest=6661)
    [17115] = {
      [itemKeys.startQuest] = 6661,
    },
    --* Item 17116 https://classic.wowhead.com/classic/item=17116
    --* Starts: Me Brother, Nipsy(6662)(https://classic.wowhead.com/classic/quest=6662)
    [17116] = {
      [itemKeys.startQuest] = 6662,
    },
    --* Item 17126 https://classic.wowhead.com/classic/item=17126
    --* Starts: The Manor, Ravenholdt(6681)(https://classic.wowhead.com/classic/quest=6681)
    [17126] = {
      [itemKeys.startQuest] = 6681,
    },
    --* Item 17409 https://classic.wowhead.com/classic/item=17409
    --* Starts: <NYI> <TXT> bug crystal side quest(1155)(https://classic.wowhead.com/classic/quest=1155)
    [17409] = {
      [itemKeys.startQuest] = 1155,
    },
    --* Item 18356 https://classic.wowhead.com/classic/item=18356
    --* Starts: Garona: A Study on Stealth and Treachery(7498)(https://classic.wowhead.com/classic/quest=7498)
    [18356] = {
      [itemKeys.startQuest] = 7498,
    },
    --* Item 18357 https://classic.wowhead.com/classic/item=18357
    --* Starts: Codex of Defense(7499)(https://classic.wowhead.com/classic/quest=7499)
    [18357] = {
      [itemKeys.startQuest] = 7499,
    },
    --* Item 18358 https://classic.wowhead.com/classic/item=18358
    --* Starts: The Arcanist's Cookbook(7500)(https://classic.wowhead.com/classic/quest=7500)
    [18358] = {
      [itemKeys.startQuest] = 7500,
    },
    --* Item 18359 https://classic.wowhead.com/classic/item=18359
    --* Starts: The Light and How To Swing It(7501)(https://classic.wowhead.com/classic/quest=7501)
    [18359] = {
      [itemKeys.startQuest] = 7501,
    },
    --* Item 18360 https://classic.wowhead.com/classic/item=18360
    --* Starts: Harnessing Shadows(7502)(https://classic.wowhead.com/classic/quest=7502)
    [18360] = {
      [itemKeys.startQuest] = 7502,
    },
    --* Item 18361 https://classic.wowhead.com/classic/item=18361
    --* Starts: The Greatest Race of Hunters(7503)(https://classic.wowhead.com/classic/quest=7503)
    [18361] = {
      [itemKeys.startQuest] = 7503,
    },
    --* Item 18362 https://classic.wowhead.com/classic/item=18362
    --* Starts: Holy Bologna: What the Light Won't Tell You(7504)(https://classic.wowhead.com/classic/quest=7504)
    [18362] = {
      [itemKeys.startQuest] = 7504,
    },
    --* Item 18363 https://classic.wowhead.com/classic/item=18363
    --* Starts: Frost Shock and You(7505)(https://classic.wowhead.com/classic/quest=7505)
    [18363] = {
      [itemKeys.startQuest] = 7505,
    },
    --* Item 18364 https://classic.wowhead.com/classic/item=18364
    --* Starts: The Emerald Dream...(7506)(https://classic.wowhead.com/classic/quest=7506)
    [18364] = {
      [itemKeys.startQuest] = 7506,
    },
    --* Item 18422 https://classic.wowhead.com/classic/item=18422
    --* Starts: Victory for the Horde(7490)(https://classic.wowhead.com/classic/quest=7490)
    [18422] = {
      [itemKeys.startQuest] = 7490,
    },
    --* Item 18423 https://classic.wowhead.com/classic/item=18423
    --* Starts: Victory for the Alliance(7495)(https://classic.wowhead.com/classic/quest=7495)
    [18423] = {
      [itemKeys.startQuest] = 7495,
    },
    --* Item 18628 https://classic.wowhead.com/classic/item=18628
    --* Starts: A Binding Contract(7604)(https://classic.wowhead.com/classic/quest=7604)
    [18628] = {
      [itemKeys.startQuest] = 7604,
    },
    --* Item 18703 https://classic.wowhead.com/classic/item=18703
    --* Starts: The Ancient Leaf(7632)(https://classic.wowhead.com/classic/quest=7632)
    [18703] = {
      [itemKeys.startQuest] = 7632,
    },
    --* Item 18706 https://classic.wowhead.com/classic/item=18706
    --* Starts: Arena Master(7810)(https://classic.wowhead.com/classic/quest=7810)
    [18706] = {
      [itemKeys.startQuest] = 7810,
    },
    --* Item 18769 https://classic.wowhead.com/classic/item=18769
    --* Starts: Enchanted Thorium Platemail: Volume I(7649)(https://classic.wowhead.com/classic/quest=7649)
    [18769] = {
      [itemKeys.startQuest] = 7649,
    },
    --* Item 18770 https://classic.wowhead.com/classic/item=18770
    --* Starts: Enchanted Thorium Platemail: Volume II(7650)(https://classic.wowhead.com/classic/quest=7650)
    [18770] = {
      [itemKeys.startQuest] = 7650,
    },
    --* Item 18771 https://classic.wowhead.com/classic/item=18771
    --* Starts: Enchanted Thorium Platemail: Volume III(7651)(https://classic.wowhead.com/classic/quest=7651)
    [18771] = {
      [itemKeys.startQuest] = 7651,
    },
    --* Item 18950 https://classic.wowhead.com/classic/item=18950
    --* Starts: Look at the Size of It!(7704)(https://classic.wowhead.com/classic/quest=7704)
    [18950] = {
      [itemKeys.startQuest] = 7704,
    },
    --* Item 18969 https://classic.wowhead.com/classic/item=18969
    --* Starts: Pristine Yeti Hide(7735)(https://classic.wowhead.com/classic/quest=7735)
    [18969] = {
      [itemKeys.startQuest] = 7735,
    },
    --* Item 18972 https://classic.wowhead.com/classic/item=18972
    --* Starts: Perfect Yeti Hide(7738)(https://classic.wowhead.com/classic/quest=7738)
    [18972] = {
      [itemKeys.startQuest] = 7738,
    },
    --* Item 18987 https://classic.wowhead.com/classic/item=18987
    --* Starts: Blackhand's Command(7761)(https://classic.wowhead.com/classic/quest=7761)
    [18987] = {
      [itemKeys.startQuest] = 7761,
    },
    --* Item 19002 https://classic.wowhead.com/classic/item=19002
    --* Starts: The Lord of Blackrock(7783)(https://classic.wowhead.com/classic/quest=7783)
    [19002] = {
      [itemKeys.startQuest] = 7783,
    },
    --* Item 19003 https://classic.wowhead.com/classic/item=19003
    --* Starts: The Lord of Blackrock(7781)(https://classic.wowhead.com/classic/quest=7781)
    [19003] = {
      [itemKeys.startQuest] = 7781,
    },
    --* Item 19016 https://classic.wowhead.com/classic/item=19016
    --* Starts: Examine the Vessel(7785)(https://classic.wowhead.com/classic/quest=7785)
    [19016] = {
      [itemKeys.startQuest] = 7785,
    },
    --* Item 19018 https://classic.wowhead.com/classic/item=19018
    --* Starts: Rise, Thunderfury!(7787)(https://classic.wowhead.com/classic/quest=7787)
    [19018] = {
      [itemKeys.startQuest] = 7787,
    },
    --* Item 19228 https://classic.wowhead.com/classic/item=19228
    --* Starts: Darkmoon Beast Deck(7907)(https://classic.wowhead.com/classic/quest=7907)
    [19228] = {
      [itemKeys.startQuest] = 7907,
    },
    --* Item 19257 https://classic.wowhead.com/classic/item=19257
    --* Starts: Darkmoon Warlords Deck(7928)(https://classic.wowhead.com/classic/quest=7928)
    [19257] = {
      [itemKeys.startQuest] = 7928,
    },
    --* Item 19267 https://classic.wowhead.com/classic/item=19267
    --* Starts: Darkmoon Elementals Deck(7929)(https://classic.wowhead.com/classic/quest=7929)
    [19267] = {
      [itemKeys.startQuest] = 7929,
    },
    --* Item 19277 https://classic.wowhead.com/classic/item=19277
    --* Starts: Darkmoon Portals Deck(7927)(https://classic.wowhead.com/classic/quest=7927)
    [19277] = {
      [itemKeys.startQuest] = 7927,
    },
    --* Item 19423 https://classic.wowhead.com/classic/item=19423
    --* Starts: Your Fortune Awaits You...(7937)(https://classic.wowhead.com/classic/quest=7937)
    [19423] = {
      [itemKeys.startQuest] = 7937,
    },
    --* Item 19424 https://classic.wowhead.com/classic/item=19424
    --* Starts: Your Fortune Awaits You...(7938)(https://classic.wowhead.com/classic/quest=7938)
    [19424] = {
      [itemKeys.startQuest] = 7938,
    },
    --* Item 19443 https://classic.wowhead.com/classic/item=19443
    --* Starts: Your Fortune Awaits You...(7944)(https://classic.wowhead.com/classic/quest=7944)
    [19443] = {
      [itemKeys.startQuest] = 7944,
    },
    --* Item 19452 https://classic.wowhead.com/classic/item=19452
    --* Starts: Your Fortune Awaits You...(7945)(https://classic.wowhead.com/classic/quest=7945)
    [19452] = {
      [itemKeys.startQuest] = 7945,
    },
    --* Item 19802 https://classic.wowhead.com/classic/item=19802
    --* Starts: The Heart of Hakkar(8183)(https://classic.wowhead.com/classic/quest=8183)
    [19802] = {
      [itemKeys.startQuest] = 8183,
    },
    --* Item 20310 https://classic.wowhead.com/classic/item=20310
    --* Starts: The Corrupter(1480)(https://classic.wowhead.com/classic/quest=1480)
    [20310] = {
      [itemKeys.startQuest] = 1480,
    },
    --* Item 20460 https://classic.wowhead.com/classic/item=20460
    --* Starts: Brann Bronzebeard's Lost Letter(8308)(https://classic.wowhead.com/classic/quest=8308)
    [20460] = {
      [itemKeys.startQuest] = 8308,
    },
    --* Item 20461 https://classic.wowhead.com/classic/item=20461
    --* Starts: Brann Bronzebeard's Lost Letter(8308)(https://classic.wowhead.com/classic/quest=8308)
    [20461] = {
      [itemKeys.startQuest] = 8308,
    },
    --* Item 20644 https://classic.wowhead.com/classic/item=20644
    --* Starts: Shrouded in Nightmare(8446)(https://classic.wowhead.com/classic/quest=8446)
    [20644] = {
      [itemKeys.startQuest] = 8446,
    },
    --* Item 20741 https://classic.wowhead.com/classic/item=20741
    --* Starts: Deadwood Ritual Totem(8470)(https://classic.wowhead.com/classic/quest=8470)
    [20741] = {
      [itemKeys.startQuest] = 8470,
    },
    --* Item 20742 https://classic.wowhead.com/classic/item=20742
    --* Starts: Winterfall Ritual Totem(8471)(https://classic.wowhead.com/classic/quest=8471)
    [20742] = {
      [itemKeys.startQuest] = 8471,
    },
    --* Item 20806 https://classic.wowhead.com/classic/item=20806
    --* Starts: Bandages for the Field(8496)(https://classic.wowhead.com/classic/quest=8496)
    [20806] = {
      [itemKeys.startQuest] = 8496,
    },
    --* Item 20807 https://classic.wowhead.com/classic/item=20807
    --* Starts: Desert Survival Kits(8497)(https://classic.wowhead.com/classic/quest=8497)
    [20807] = {
      [itemKeys.startQuest] = 8497,
    },
    --* Item 20939 https://classic.wowhead.com/classic/item=20939
    --* Starts: Boots for the Guard(8540)(https://classic.wowhead.com/classic/quest=8540)
    [20939] = {
      [itemKeys.startQuest] = 8540,
    },
    --* Item 20940 https://classic.wowhead.com/classic/item=20940
    --* Starts: Grinding Stones for the Guard(8541)(https://classic.wowhead.com/classic/quest=8541)
    [20940] = {
      [itemKeys.startQuest] = 8541,
    },
    --* Item 20941 https://classic.wowhead.com/classic/item=20941
    --* Starts: Target: Hive'Ashi Stingers(8501)(https://classic.wowhead.com/classic/quest=8501)
    [20941] = {
      [itemKeys.startQuest] = 8501,
    },
    --* Item 20942 https://classic.wowhead.com/classic/item=20942
    --* Starts: Target: Hive'Ashi Workers(8502)(https://classic.wowhead.com/classic/quest=8502)
    [20942] = {
      [itemKeys.startQuest] = 8502,
    },
    --* Item 20943 https://classic.wowhead.com/classic/item=20943
    --* Starts: Twilight Battle Orders(8498)(https://classic.wowhead.com/classic/quest=8498)
    [20943] = {
      [itemKeys.startQuest] = 8498,
    },
    --* Item 20944 https://classic.wowhead.com/classic/item=20944
    --* Starts: Twilight Marauders(8740)(https://classic.wowhead.com/classic/quest=8740)
    [20944] = {
      [itemKeys.startQuest] = 8740,
    },
    --* Item 20945 https://classic.wowhead.com/classic/item=20945
    --* Starts: Crimson Templar(8537)(https://classic.wowhead.com/classic/quest=8537)
    [20945] = {
      [itemKeys.startQuest] = 8537,
    },
    --* Item 20946 https://classic.wowhead.com/classic/item=20946
    --* Starts: Earthen Templar(8536)(https://classic.wowhead.com/classic/quest=8536)
    [20946] = {
      [itemKeys.startQuest] = 8536,
    },
    --* Item 20947 https://classic.wowhead.com/classic/item=20947
    --* Starts: Hoary Templar(8535)(https://classic.wowhead.com/classic/quest=8535)
    [20947] = {
      [itemKeys.startQuest] = 8535,
    },
    --* Item 20948 https://classic.wowhead.com/classic/item=20948
    --* Starts: The Four Dukes(8538)(https://classic.wowhead.com/classic/quest=8538)
    [20948] = {
      [itemKeys.startQuest] = 8538,
    },
    --* Item 20949 https://classic.wowhead.com/classic/item=20949
    --* Starts: Azuregos's Magical Ledger(8575)(https://classic.wowhead.com/classic/quest=8575)
    [20949] = {
      [itemKeys.startQuest] = 8575,
    },
    --* Item 21165 https://classic.wowhead.com/classic/item=21165
    --* Starts: Hive'Zora Scout Report(8534)(https://classic.wowhead.com/classic/quest=8534)
    [21165] = {
      [itemKeys.startQuest] = 8534,
    },
    --* Item 21166 https://classic.wowhead.com/classic/item=21166
    --* Starts: Hive'Regal Scout Report(8738)(https://classic.wowhead.com/classic/quest=8738)
    [21166] = {
      [itemKeys.startQuest] = 8738,
    },
    --* Item 21167 https://classic.wowhead.com/classic/item=21167
    --* Starts: Hive'Ashi Scout Report(8739)(https://classic.wowhead.com/classic/quest=8739)
    [21167] = {
      [itemKeys.startQuest] = 8739,
    },
    --* Item 21220 https://classic.wowhead.com/classic/item=21220
    --* Starts: The Fall of Ossirian(8791)(https://classic.wowhead.com/classic/quest=8791)
    [21220] = {
      [itemKeys.startQuest] = 8791,
    },
    --* Item 21221 https://classic.wowhead.com/classic/item=21221
    --* Starts: C'Thun's Legacy(8801)(https://classic.wowhead.com/classic/quest=8801)
    [21221] = {
      [itemKeys.startQuest] = 8801,
    },
    --* Item 21230 https://classic.wowhead.com/classic/item=21230
    --* Starts: Secrets of the Qiraji(8784)(https://classic.wowhead.com/classic/quest=8784)
    [21230] = {
      [itemKeys.startQuest] = 8784,
    },
    --* Item 21245 https://classic.wowhead.com/classic/item=21245
    --* Starts: Azure Templar(8737)(https://classic.wowhead.com/classic/quest=8737)
    [21245] = {
      [itemKeys.startQuest] = 8737,
    },
    --* Item 21246 https://classic.wowhead.com/classic/item=21246
    --* Starts: Target: Hive'Ashi Defenders(8770)(https://classic.wowhead.com/classic/quest=8770)
    [21246] = {
      [itemKeys.startQuest] = 8770,
    },
    --* Item 21247 https://classic.wowhead.com/classic/item=21247
    --* Starts: Target: Hive'Ashi Sandstalkers(8771)(https://classic.wowhead.com/classic/quest=8771)
    [21247] = {
      [itemKeys.startQuest] = 8771,
    },
    --* Item 21248 https://classic.wowhead.com/classic/item=21248
    --* Starts: Target: Hive'Zora Reavers(8773)(https://classic.wowhead.com/classic/quest=8773)
    [21248] = {
      [itemKeys.startQuest] = 8773,
    },
    --* Item 21249 https://classic.wowhead.com/classic/item=21249
    --* Starts: Target: Hive'Zora Hive Sisters(8539)(https://classic.wowhead.com/classic/quest=8539)
    [21249] = {
      [itemKeys.startQuest] = 8539,
    },
    --* Item 21250 https://classic.wowhead.com/classic/item=21250
    --* Starts: Target: Hive'Zora Waywatchers(8772)(https://classic.wowhead.com/classic/quest=8772)
    [21250] = {
      [itemKeys.startQuest] = 8772,
    },
    --* Item 21251 https://classic.wowhead.com/classic/item=21251
    --* Starts: Target: Hive'Zora Tunnelers(8687)(https://classic.wowhead.com/classic/quest=8687)
    [21251] = {
      [itemKeys.startQuest] = 8687,
    },
    --* Item 21252 https://classic.wowhead.com/classic/item=21252
    --* Starts: Target: Hive'Regal Ambushers(8774)(https://classic.wowhead.com/classic/quest=8774)
    [21252] = {
      [itemKeys.startQuest] = 8774,
    },
    --* Item 21253 https://classic.wowhead.com/classic/item=21253
    --* Starts: Target: Hive'Regal Spitfires(8775)(https://classic.wowhead.com/classic/quest=8775)
    [21253] = {
      [itemKeys.startQuest] = 8775,
    },
    --* Item 21255 https://classic.wowhead.com/classic/item=21255
    --* Starts: Target: Hive'Regal Slavemakers(8776)(https://classic.wowhead.com/classic/quest=8776)
    [21255] = {
      [itemKeys.startQuest] = 8776,
    },
    --* Item 21256 https://classic.wowhead.com/classic/item=21256
    --* Starts: Target: Hive'Regal Burrowers(8777)(https://classic.wowhead.com/classic/quest=8777)
    [21256] = {
      [itemKeys.startQuest] = 8777,
    },
    --* Item 21257 https://classic.wowhead.com/classic/item=21257
    --* Starts: The Ironforge Brigade Needs Explosives!(8778)(https://classic.wowhead.com/classic/quest=8778)
    [21257] = {
      [itemKeys.startQuest] = 8778,
    },
    --* Item 21258 https://classic.wowhead.com/classic/item=21258
    --* Starts: The Orgrimmar Legion Needs Mojo!(8785)(https://classic.wowhead.com/classic/quest=8785)
    [21258] = {
      [itemKeys.startQuest] = 8785,
    },
    --* Item 21259 https://classic.wowhead.com/classic/item=21259
    --* Starts: Scrying Materials(8779)(https://classic.wowhead.com/classic/quest=8779)
    [21259] = {
      [itemKeys.startQuest] = 8779,
    },
    --* Item 21260 https://classic.wowhead.com/classic/item=21260
    --* Starts: Arms for the Field(8781)(https://classic.wowhead.com/classic/quest=8781)
    [21260] = {
      [itemKeys.startQuest] = 8781,
    },
    --* Item 21261 https://classic.wowhead.com/classic/item=21261
    --* Starts: Arms for the Field(8786)(https://classic.wowhead.com/classic/quest=8786)
    [21261] = {
      [itemKeys.startQuest] = 8786,
    },
    --* Item 21262 https://classic.wowhead.com/classic/item=21262
    --* Starts: Uniform Supplies(8782)(https://classic.wowhead.com/classic/quest=8782)
    [21262] = {
      [itemKeys.startQuest] = 8782,
    },
    --* Item 21263 https://classic.wowhead.com/classic/item=21263
    --* Starts: Armor Kits for the Field(8780)(https://classic.wowhead.com/classic/quest=8780)
    [21263] = {
      [itemKeys.startQuest] = 8780,
    },
    --* Item 21264 https://classic.wowhead.com/classic/item=21264
    --* Starts: Armor Kits for the Field(8787)(https://classic.wowhead.com/classic/quest=8787)
    [21264] = {
      [itemKeys.startQuest] = 8787,
    },
    --* Item 21265 https://classic.wowhead.com/classic/item=21265
    --* Starts: Extraordinary Materials(8783)(https://classic.wowhead.com/classic/quest=8783)
    [21265] = {
      [itemKeys.startQuest] = 8783,
    },
    --* Item 21378 https://classic.wowhead.com/classic/item=21378
    --* Starts: Desert Survival Kits(8804)(https://classic.wowhead.com/classic/quest=8804)
    [21378] = {
      [itemKeys.startQuest] = 8804,
    },
    --* Item 21379 https://classic.wowhead.com/classic/item=21379
    --* Starts: Boots for the Guard(8805)(https://classic.wowhead.com/classic/quest=8805)
    [21379] = {
      [itemKeys.startQuest] = 8805,
    },
    --* Item 21380 https://classic.wowhead.com/classic/item=21380
    --* Starts: Grinding Stones for the Guard(8806)(https://classic.wowhead.com/classic/quest=8806)
    [21380] = {
      [itemKeys.startQuest] = 8806,
    },
    --* Item 21381 https://classic.wowhead.com/classic/item=21381
    --* Starts: Extraordinary Materials(8809)(https://classic.wowhead.com/classic/quest=8809)
    [21381] = {
      [itemKeys.startQuest] = 8809,
    },
    --* Item 21382 https://classic.wowhead.com/classic/item=21382
    --* Starts: Scrying Materials(8807)(https://classic.wowhead.com/classic/quest=8807)
    [21382] = {
      [itemKeys.startQuest] = 8807,
    },
    --* Item 21384 https://classic.wowhead.com/classic/item=21384
    --* Starts: Uniform Supplies(8808)(https://classic.wowhead.com/classic/quest=8808)
    [21384] = {
      [itemKeys.startQuest] = 8808,
    },
    --* Item 21385 https://classic.wowhead.com/classic/item=21385
    --* Starts: Bandages for the Field(8810)(https://classic.wowhead.com/classic/quest=8810)
    [21385] = {
      [itemKeys.startQuest] = 8810,
    },
    --* Item 21514 https://classic.wowhead.com/classic/item=21514
    --* Starts: The Ultimate Deception(8829)(https://classic.wowhead.com/classic/quest=8829)
    [21514] = {
      [itemKeys.startQuest] = 8829,
    },
    --* Item 21749 https://classic.wowhead.com/classic/item=21749
    --* Starts: Target: Hive'Ashi Defenders(8770)(https://classic.wowhead.com/classic/quest=8770)
    [21749] = {
      [itemKeys.startQuest] = 8770,
    },
    --* Item 21750 https://classic.wowhead.com/classic/item=21750
    --* Starts: Target: Hive'Ashi Sandstalkers(8771)(https://classic.wowhead.com/classic/quest=8771)
    [21750] = {
      [itemKeys.startQuest] = 8771,
    },
    --* Item 21751 https://classic.wowhead.com/classic/item=21751
    --* Starts: Earthen Templar(8536)(https://classic.wowhead.com/classic/quest=8536)
    [21751] = {
      [itemKeys.startQuest] = 8536,
    },
    --* Item 22520 https://classic.wowhead.com/classic/item=22520
    --* Starts: The Fall of Kel'Thuzad(9120)(https://classic.wowhead.com/classic/quest=9120)
    [22520] = {
      [itemKeys.startQuest] = 9120,
    },
    --* Item 22600 https://classic.wowhead.com/classic/item=22600
    --* Starts: Craftsman's Writ - Dense Weightstone(9178)(https://classic.wowhead.com/classic/quest=9178)
    [22600] = {
      [itemKeys.startQuest] = 9178,
    },
    --* Item 22601 https://classic.wowhead.com/classic/item=22601
    --* Starts: Craftsman's Writ - Imperial Plate Chest(9179)(https://classic.wowhead.com/classic/quest=9179)
    [22601] = {
      [itemKeys.startQuest] = 9179,
    },
    --* Item 22602 https://classic.wowhead.com/classic/item=22602
    --* Starts: Craftsman's Writ - Volcanic Hammer(9181)(https://classic.wowhead.com/classic/quest=9181)
    [22602] = {
      [itemKeys.startQuest] = 9181,
    },
    --* Item 22603 https://classic.wowhead.com/classic/item=22603
    --* Starts: Craftsman's Writ - Huge Thorium Battleaxe(9182)(https://classic.wowhead.com/classic/quest=9182)
    [22603] = {
      [itemKeys.startQuest] = 9182,
    },
    --* Item 22604 https://classic.wowhead.com/classic/item=22604
    --* Starts: Craftsman's Writ - Radiant Circlet(9183)(https://classic.wowhead.com/classic/quest=9183)
    [22604] = {
      [itemKeys.startQuest] = 9183,
    },
    --* Item 22605 https://classic.wowhead.com/classic/item=22605
    --* Starts: Craftsman's Writ - Wicked Leather Headband(9184)(https://classic.wowhead.com/classic/quest=9184)
    [22605] = {
      [itemKeys.startQuest] = 9184,
    },
    --* Item 22606 https://classic.wowhead.com/classic/item=22606
    --* Starts: Craftsman's Writ - Rugged Armor Kit(9185)(https://classic.wowhead.com/classic/quest=9185)
    [22606] = {
      [itemKeys.startQuest] = 9185,
    },
    --* Item 22607 https://classic.wowhead.com/classic/item=22607
    --* Starts: Craftsman's Writ - Wicked Leather Belt(9186)(https://classic.wowhead.com/classic/quest=9186)
    [22607] = {
      [itemKeys.startQuest] = 9186,
    },
    --* Item 22608 https://classic.wowhead.com/classic/item=22608
    --* Starts: Craftsman's Writ - Runic Leather Pants(9187)(https://classic.wowhead.com/classic/quest=9187)
    [22608] = {
      [itemKeys.startQuest] = 9187,
    },
    --* Item 22609 https://classic.wowhead.com/classic/item=22609
    --* Starts: Craftsman's Writ - Brightcloth Pants(9188)(https://classic.wowhead.com/classic/quest=9188)
    [22609] = {
      [itemKeys.startQuest] = 9188,
    },
    --* Item 22610 https://classic.wowhead.com/classic/item=22610
    --* Starts: Craftsman's Writ - Runecloth Boots(9190)(https://classic.wowhead.com/classic/quest=9190)
    [22610] = {
      [itemKeys.startQuest] = 9190,
    },
    --* Item 22611 https://classic.wowhead.com/classic/item=22611
    --* Starts: Craftsman's Writ - Runecloth Bag(9191)(https://classic.wowhead.com/classic/quest=9191)
    [22611] = {
      [itemKeys.startQuest] = 9191,
    },
    --* Item 22612 https://classic.wowhead.com/classic/item=22612
    --* Starts: Craftsman's Writ - Runecloth Robe(9194)(https://classic.wowhead.com/classic/quest=9194)
    [22612] = {
      [itemKeys.startQuest] = 9194,
    },
    --* Item 22613 https://classic.wowhead.com/classic/item=22613
    --* Starts: Craftsman's Writ - Goblin Sapper Charge(9195)(https://classic.wowhead.com/classic/quest=9195)
    [22613] = {
      [itemKeys.startQuest] = 9195,
    },
    --* Item 22614 https://classic.wowhead.com/classic/item=22614
    --* Starts: Craftsman's Writ - Thorium Grenade(9196)(https://classic.wowhead.com/classic/quest=9196)
    [22614] = {
      [itemKeys.startQuest] = 9196,
    },
    --* Item 22615 https://classic.wowhead.com/classic/item=22615
    --* Starts: Craftsman's Writ - Gnomish Battle Chicken(9197)(https://classic.wowhead.com/classic/quest=9197)
    [22615] = {
      [itemKeys.startQuest] = 9197,
    },
    --* Item 22616 https://classic.wowhead.com/classic/item=22616
    --* Starts: Craftsman's Writ - Thorium Tube(9198)(https://classic.wowhead.com/classic/quest=9198)
    [22616] = {
      [itemKeys.startQuest] = 9198,
    },
    --* Item 22617 https://classic.wowhead.com/classic/item=22617
    --* Starts: Craftsman's Writ - Major Mana Potion(9200)(https://classic.wowhead.com/classic/quest=9200)
    [22617] = {
      [itemKeys.startQuest] = 9200,
    },
    --* Item 22618 https://classic.wowhead.com/classic/item=22618
    --* Starts: Craftsman's Writ - Major Healing Potion(9202)(https://classic.wowhead.com/classic/quest=9202)
    [22618] = {
      [itemKeys.startQuest] = 9202,
    },
    --* Item 22620 https://classic.wowhead.com/classic/item=22620
    --* Starts: Craftsman's Writ - Greater Arcane Protection Potion(9201)(https://classic.wowhead.com/classic/quest=9201)
    [22620] = {
      [itemKeys.startQuest] = 9201,
    },
    --* Item 22621 https://classic.wowhead.com/classic/item=22621
    --* Starts: Craftsman's Writ - Potion of Petrification(9203)(https://classic.wowhead.com/classic/quest=9203)
    [22621] = {
      [itemKeys.startQuest] = 9203,
    },
    --* Item 22622 https://classic.wowhead.com/classic/item=22622
    --* Starts: Craftsman's Writ - Stonescale Eel(9204)(https://classic.wowhead.com/classic/quest=9204)
    [22622] = {
      [itemKeys.startQuest] = 9204,
    },
    --* Item 22623 https://classic.wowhead.com/classic/item=22623
    --* Starts: Craftsman's Writ - Plated Armorfish(9205)(https://classic.wowhead.com/classic/quest=9205)
    [22623] = {
      [itemKeys.startQuest] = 9205,
    },
    --* Item 22624 https://classic.wowhead.com/classic/item=22624
    --* Starts: Craftsman's Writ - Lightning Eel(9206)(https://classic.wowhead.com/classic/quest=9206)
    [22624] = {
      [itemKeys.startQuest] = 9206,
    },
    --* Item 22719 https://classic.wowhead.com/classic/item=22719
    --* Starts: Omarion's Handbook(9233)(https://classic.wowhead.com/classic/quest=9233)
    [22719] = {
      [itemKeys.startQuest] = 9233,
    },
    --* Item 22723 https://classic.wowhead.com/classic/item=22723
    --* Starts: The Keeper's Call(9247)(https://classic.wowhead.com/classic/quest=9247)
    [22723] = {
      [itemKeys.startQuest] = 9247,
    },
    --* Item 22727 https://classic.wowhead.com/classic/item=22727
    --* Starts: Frame of Atiesh(9250)(https://classic.wowhead.com/classic/quest=9250)
    [22727] = {
      [itemKeys.startQuest] = 9250,
    },
    --* Item 22970 https://classic.wowhead.com/classic/item=22970
    --* Starts: Envelope from the Front(9301)(https://classic.wowhead.com/classic/quest=9301)
    [22970] = {
      [itemKeys.startQuest] = 9301,
    },
    --* Item 22972 https://classic.wowhead.com/classic/item=22972
    --* Starts: Note from the Front(9299)(https://classic.wowhead.com/classic/quest=9299)
    [22972] = {
      [itemKeys.startQuest] = 9299,
    },
    --* Item 22973 https://classic.wowhead.com/classic/item=22973
    --* Starts: Missive from the Front(9302)(https://classic.wowhead.com/classic/quest=9302)
    [22973] = {
      [itemKeys.startQuest] = 9302,
    },
    --* Item 22974 https://classic.wowhead.com/classic/item=22974
    --* Starts: Page from the Front(9300)(https://classic.wowhead.com/classic/quest=9300)
    [22974] = {
      [itemKeys.startQuest] = 9300,
    },
    --* Item 22975 https://classic.wowhead.com/classic/item=22975
    --* Starts: Document from the Front(9304)(https://classic.wowhead.com/classic/quest=9304)
    [22975] = {
      [itemKeys.startQuest] = 9304,
    },
    --* Item 22977 https://classic.wowhead.com/classic/item=22977
    --* Starts: Letter from the Front(9295)(https://classic.wowhead.com/classic/quest=9295)
    [22977] = {
      [itemKeys.startQuest] = 9295,
    },
    --* Item 23179 https://classic.wowhead.com/classic/item=23179
    --* Starts: Stealing Orgrimmar's Flame(9324)(https://classic.wowhead.com/classic/quest=9324)
    [23179] = {
      [itemKeys.startQuest] = 9324,
    },
    --* Item 23180 https://classic.wowhead.com/classic/item=23180
    --* Starts: Stealing Thunder Bluff's Flame(9325)(https://classic.wowhead.com/classic/quest=9325)
    [23180] = {
      [itemKeys.startQuest] = 9325,
    },
    --* Item 23181 https://classic.wowhead.com/classic/item=23181
    --* Starts: Stealing the Undercity's Flame(9326)(https://classic.wowhead.com/classic/quest=9326)
    [23181] = {
      [itemKeys.startQuest] = 9326,
    },
    --* Item 23182 https://classic.wowhead.com/classic/item=23182
    --* Starts: Stealing Stormwind's Flame(9330)(https://classic.wowhead.com/classic/quest=9330)
    [23182] = {
      [itemKeys.startQuest] = 9330,
    },
    --* Item 23183 https://classic.wowhead.com/classic/item=23183
    --* Starts: Stealing Ironforge's Flame(9331)(https://classic.wowhead.com/classic/quest=9331)
    [23183] = {
      [itemKeys.startQuest] = 9331,
    },
    --* Item 23184 https://classic.wowhead.com/classic/item=23184
    --* Starts: Stealing Darnassus's Flame(9332)(https://classic.wowhead.com/classic/quest=9332)
    [23184] = {
      [itemKeys.startQuest] = 9332,
    },
  }
end
