-- GENERATED by dbc-coordinates --write-runtime-helper. Do not edit; change this tool's template instead.
-- DBC bounds: @SOURCE_BUILD@ -> @TARGET_BUILD@. Assumes unchanged world positions.
-- Explicit projection only; never applied automatically to database reads.
local _, LibQuestieDB = ...

-- GENERATED by dbc-coordinates --write-runtime-helper. Do not edit; change this tool's template instead.
-- AreaID -> scaleX, offsetX, scaleY, offsetY. Only non-identity transforms are stored.
local transforms = {
@TRANSFORMS@
}
-- GENERATED by dbc-coordinates --write-runtime-helper. Do not edit; change this tool's template instead.
local uiMapToArea = {
@UI_MAPS@
}
-- GENERATED by dbc-coordinates --write-runtime-helper. Do not edit; change this tool's template instead.

-- GENERATED by dbc-coordinates --write-runtime-helper. Do not edit; change this tool's template instead.
---Convert Era percentages (0-100) to Forever without rounding or clamping.
---Other AreaIDs pass through unchanged; no subzone/parent frame is inferred.
---Preserves (-1,-1) instance presence; rejects partial sentinels.
---Use the point's zone AreaID, not a dungeon ID. Do not convert Forever data again.
---@param areaId integer
---@param x number
---@param y number
---@return number foreverX
---@return number foreverY
function LibQuestieDB.EraToForever(areaId, x, y)
  if x == -1 or y == -1 then
    assert(x == -1 and y == -1, "QuestieDB: partial instance sentinel")
    return x, y
  end
  local transform = transforms[areaId]
  if not transform then return x, y end
  return x * transform[1] + transform[2], y * transform[3] + transform[4]
end

-- GENERATED by dbc-coordinates --write-runtime-helper. Do not edit; change this tool's template instead.
---Same conversion using the point's Era UiMapID, not an AreaID or world MapID.
---Other UiMapIDs pass through unchanged, including unknown IDs.
---@param uiMapId integer
---@param x number Era percentage (0-100).
---@param y number Era percentage (0-100).
---@return number foreverX
---@return number foreverY
function LibQuestieDB.EraToForeverByUiMapId(uiMapId, x, y)
  return LibQuestieDB.EraToForever(uiMapToArea[uiMapId] or 0, x, y)
end

-- WoW ignores chunk returns; the offline checker uses these keys to detect obsolete entries.
return transforms, uiMapToArea
