-- Offline inventory of every copied support dataset. Applicability is checked against
-- pinned Questie's TOCs, independently of config.supportData's runtime file selection.
---@class SupportInput
---@field file string Provider-relative source path.
---@field questie string Pinned Questie-relative source path.
---@field fields string[] Published module fields, including embedded Lua table sources.
---@field luaFields string[]? Fields authored as Lua source strings; compare their decoded values and original types.

---@type SupportInput[]
return {
  { file = "support/Zones/dungeons.lua",
    questie = "Database/Zones/data/dungeons.lua",
    fields = { "ZoneDB.private.dungeons" } },
  { file = "support/Zones/subZoneToParentZone.lua",
    questie = "Database/Zones/data/subZoneToParentZone.lua",
    fields = { "ZoneDB.private.subZoneToParentZone", "ZoneDB.private.subZoneToParentZoneOverride" },
    luaFields = { "ZoneDB.private.subZoneToParentZone", "ZoneDB.private.subZoneToParentZoneOverride" } },
  { file = "support/Zones/zoneIds.lua",
    questie = "Database/Zones/data/zoneIds.lua",
    fields = { "ZoneDB.zoneIDs" } },
  { file = "support/Zones/instanceIdToAreaId.lua",
    questie = "Database/Zones/data/instanceIdToAreaId.lua",
    fields = { "ZoneDB.instanceIdToAreaId" } },
  { file = "support/Zones/areaIdToUiMapId.lua",
    questie = "Database/Zones/data/areaIdToUiMapId.lua",
    fields = { "ZoneDB.private.areaIdToUiMapId", "ZoneDB.private.areaIdToUiMapIdOverride" },
    luaFields = { "ZoneDB.private.areaIdToUiMapId", "ZoneDB.private.areaIdToUiMapIdOverride" } },
  { file = "support/Zones/uiMapIdToAreaId.lua",
    questie = "Database/Zones/data/uiMapIdToAreaId.lua",
    fields = { "ZoneDB.private.uiMapIdToAreaId", "ZoneDB.private.uiMapIdToAreaIdOverride" },
    luaFields = { "ZoneDB.private.uiMapIdToAreaId", "ZoneDB.private.uiMapIdToAreaIdOverride" } },
  { file = "support/Zones/MoP/areaIdToUiMapId.lua",
    questie = "Database/Zones/data/MoP/areaIdToUiMapId.lua",
    fields = { "ZoneDB.private.areaIdToUiMapId", "ZoneDB.private.areaIdToUiMapIdOverride" },
    luaFields = { "ZoneDB.private.areaIdToUiMapId", "ZoneDB.private.areaIdToUiMapIdOverride" } },
  { file = "support/Zones/MoP/uiMapIdToAreaId.lua",
    questie = "Database/Zones/data/MoP/uiMapIdToAreaId.lua",
    fields = { "ZoneDB.private.uiMapIdToAreaId", "ZoneDB.private.uiMapIdToAreaIdOverride" },
    luaFields = { "ZoneDB.private.uiMapIdToAreaId", "ZoneDB.private.uiMapIdToAreaIdOverride" } },
  { file = "support/QuestXP/xpDB-classic.lua",
    questie = "Database/QuestXP/DB/xpDB-classic.lua",
    fields = { "QuestXP.db" } },
  { file = "support/QuestXP/xpDB-tbc.lua",
    questie = "Database/QuestXP/DB/xpDB-tbc.lua",
    fields = { "QuestXP.db" } },
  { file = "support/QuestXP/xpDB-wotlk.lua",
    questie = "Database/QuestXP/DB/xpDB-wotlk.lua",
    fields = { "QuestXP.db" } },
  { file = "support/QuestXP/xpDB-cata.lua",
    questie = "Database/QuestXP/DB/xpDB-cata.lua",
    fields = { "QuestXP.db" } },
  { file = "support/QuestXP/xpDB-mop.lua",
    questie = "Database/QuestXP/DB/xpDB-mop.lua",
    fields = { "QuestXP.db" } },
  { file = "support/FactionTemplates/factionTemplateClassic.lua",
    questie = "Database/FactionTemplates/factionTemplateClassic.lua",
    fields = { "QuestieDB.factionTemplate" } },
  { file = "support/FactionTemplates/factionTemplateTBC.lua",
    questie = "Database/FactionTemplates/factionTemplateTBC.lua",
    fields = { "QuestieDB.factionTemplate" } },
  { file = "support/FactionTemplates/factionTemplateWotlk.lua",
    questie = "Database/FactionTemplates/factionTemplateWotlk.lua",
    fields = { "QuestieDB.factionTemplate" } },
  { file = "support/FactionTemplates/factionTemplateCata.lua",
    questie = "Database/FactionTemplates/factionTemplateCata.lua",
    fields = { "QuestieDB.factionTemplate" } },
  { file = "support/FactionTemplates/factionTemplateMoP.lua",
    questie = "Database/FactionTemplates/factionTemplateMoP.lua",
    fields = { "QuestieDB.factionTemplate" } },
  { file = "support/DropTables/itemDropCorrections.lua",
    questie = "Database/DropTables/data/itemDropCorrections.lua",
    fields = { "QuestieItemDropCorrections.Era", "QuestieItemDropCorrections.Tbc", "QuestieItemDropCorrections.Wotlk", "QuestieItemDropCorrections.Cata", "QuestieItemDropCorrections.MoP" } },
  { file = "support/DropTables/classicItemDrops.lua",
    questie = "Database/DropTables/data/classicItemDrops.lua",
    fields = { "QuestieClassicItemDrops.wowheadData", "QuestieClassicItemDrops.cmangosData" },
    luaFields = { "QuestieClassicItemDrops.wowheadData", "QuestieClassicItemDrops.cmangosData" } },
  { file = "support/DropTables/tbcItemDrops.lua",
    questie = "Database/DropTables/data/tbcItemDrops.lua",
    fields = { "QuestieTBCItemDrops.wowheadData", "QuestieTBCItemDrops.cmangosData" },
    luaFields = { "QuestieTBCItemDrops.wowheadData", "QuestieTBCItemDrops.cmangosData" } },
  { file = "support/DropTables/wotlkItemDrops.lua",
    questie = "Database/DropTables/data/wotlkItemDrops.lua",
    fields = { "QuestieWotlkItemDrops.wowheadData", "QuestieWotlkItemDrops.cmangosData" },
    luaFields = { "QuestieWotlkItemDrops.wowheadData", "QuestieWotlkItemDrops.cmangosData" } },
  { file = "support/DropTables/cataItemDrops.lua",
    questie = "Database/DropTables/data/cataItemDrops.lua",
    fields = { "QuestieCataItemDrops.wowheadData", "QuestieCataItemDrops.mangos3Data" },
    luaFields = { "QuestieCataItemDrops.wowheadData", "QuestieCataItemDrops.mangos3Data" } },
  { file = "support/DropTables/mopItemDrops.lua",
    questie = "Database/DropTables/data/mopItemDrops.lua",
    fields = { "QuestieMopItemDrops.wowheadData", "QuestieMopItemDrops.cmangosData" },
    luaFields = { "QuestieMopItemDrops.wowheadData", "QuestieMopItemDrops.cmangosData" } },
}
