-- Fixed examples extracted from QuestieDB f844724. IDs describe origins, not live lookups.
-- Shortened lists/text retain the original shape. Synthetic cases cover unobserved boundaries.
-- Expected reads are authored independently; never regenerate them from the normalizer.
return {
  -- All six objective groups. Era/SoD sources are src/corrections/<Expansion>/*QuestFixes.lua.
  { name = "creature ID only (Classic quest 7)", field = "objectives",
    input = {{{6}}}, expected = {{{6,nil,0}}} },
  { name = "creature text (Classic quest 974)", field = "objectives",
    input = {{{10541,"Find the hottest area"}}}, expected = {{{10541,"Find the hottest area",0}}} },
  { name = "creature icon and item (Era quest 503)", field = "objectives",
    input = {{{2316,nil,3}},nil,{{3704}}}, expected = {{{2316,nil,3}},nil,{{3704,nil,0}}} },
  { name = "multiple object objectives (Classic quest 498)", field = "objectives",
    input = {nil,{{1721,"Rescue Drull"},{1722,"Rescue Tog'thar"}}},
    expected = {nil,{{1721,"Rescue Drull",0},{1722,"Rescue Tog'thar",0}}} },
  { name = "item-only sparse group (Classic quest 6)", field = "objectives",
    input = {nil,nil,{{182}}}, expected = {nil,nil,{{182,nil,0}}} },
  { name = "reputation objective (Classic quest 1036)", field = "objectives",
    input = {[4]={87,3000}}, expected = {[4]={87,3000}} },
  { name = "multiple kill credits (Era quest 452, shortened)", field = "objectives",
    input = {[5]={{{2060,2061,2062},2060}}}, expected = {[5]={{{2060,2061,2062},2060,nil,0}}} },
  { name = "explicit kill-credit icon (Era quest 4022)", field = "objectives",
    input = {[3]={{10575}},[5]={{{9459},9459,nil,5}}},
    expected = {[3]={{10575,nil,0}},[5]={{{9459},9459,nil,5}}} },
  { name = "spell-only sixth group (SoD base quest 77568)", field = "objectives",
    input = {[6]={{410121}}}, expected = {[6]={{410121,nil,0}}} },
  { name = "spell with item (SoD quest 77568)", field = "objectives",
    input = {[6]={{410121,nil,206168}}}, expected = {[6]={{410121,nil,206168}}} },
  { name = "explicit zero and empty text (synthetic)", field = "objectives",
    input = {{{6,"",0}},nil,nil,nil,{{{7},7,"",0}},{{8,"",0}}},
    expected = {{{6,"",0}},nil,nil,nil,{{{7},7,"",0}},{{8,"",0}}} },
  { name = "absent objectives (Classic quest 2)", field = "objectives", expected = {} },
  { name = "empty objectives (SoD quest 78561)", field = "objectives", input = {}, expected = {} },

  -- Starter group positions remain meaningful even when earlier groups are absent.
  { name = "NPC starter (synthetic singleton)", field = "startedBy", input = {{6}}, expected = {{6}} },
  { name = "item starter (Classic quest 2)", field = "startedBy", input = {nil,nil,{16305}}, expected = {nil,nil,{16305}} },
  { name = "object starter (Classic quest 45)", field = "startedBy", input = {nil,{55}}, expected = {nil,{55}} },
  { name = "NPC and item starters (Classic quest 4903)", field = "startedBy",
    input = {{9077},nil,{12563}}, expected = {{9077},nil,{12563}} },
  { name = "object and item starters (Classic quest 8227)", field = "startedBy",
    input = {nil,{180366},{19973}}, expected = {nil,{180366},{19973}} },
  { name = "NPC and object starters (synthetic)", field = "startedBy",
    input = {{6},{55}}, expected = {{6},{55}} },
  { name = "all starter groups (Era quest 7632)", field = "startedBy",
    input = {{12018},{179703},{18703}}, expected = {{12018},{179703},{18703}} },
  { name = "multiple objects (Era quest 510)", field = "startedBy",
    input = {nil,{1738,1739,1740}}, expected = {nil,{1738,1739,1740}} },
  { name = "NPC and object finishers (Classic quest 3525)", field = "finishedBy",
    input = {{8516},{152097}}, expected = {{8516},{152097}} },
  { name = "absent starters", field = "startedBy", expected = {} },
  { name = "empty finishers", field = "finishedBy", input = {}, expected = {} },

  -- Extra-objective tuples have independent optional coordinates, indices and references.
  { name = "reference-only extra objective (Era quest 667)", field = "extraObjectives",
    input = {{nil,4,"Use the cannon",0,{{"object",113531}}}},
    expected = {{nil,4,"Use the cannon",0,{{"object",113531}}}} },
  { name = "coordinate-only extra objective (Era quest 1141)", field = "extraObjectives",
    input = {{{[148]={{35.71,44.68}}},20,"Fish for Darkshore Groupers"}},
    expected = {{{[148]={{35.71,44.68}}},20,"Fish for Darkshore Groupers",0}} },
  { name = "explicit extra-objective index (TBC quest 4021)", field = "extraObjectives",
    input = {{{[17]={{44.7,28.1}}},3,"Defeat Centaur",0}},
    expected = {{{[17]={{44.7,28.1}}},3,"Defeat Centaur",0}} },
  { name = "coordinates and references (Wrath quest 11529)", field = "extraObjectives",
    input = {{{[495]={{37.2,74.8}}},4,"Use The Big Gun",0,{{"monster",24992}}}},
    expected = {{{[495]={{37.2,74.8}}},4,"Use The Big Gun",0,{{"monster",24992}}}} },
  { name = "multiple extra objectives and nonzero index (synthetic)", field = "extraObjectives",
    input = {{nil,3,"First"},{nil,4,"Second",2}}, expected = {{nil,3,"First",0},{nil,4,"Second",2}} },
  { name = "text-only trigger (Classic quest 2240)", field = "triggerEnd",
    input = {"Explore the Hidden Chamber"}, expected = {"Explore the Hidden Chamber"} },
  { name = "coordinate trigger (Era quest 25)", field = "triggerEnd",
    input = {"Scout the gazebo",{[331]={{48.92,69.56}}}}, expected = {"Scout the gazebo",{[331]={{48.92,69.56}}}} },

  -- Ordinary arrays and pairs preserve cardinality, signed values and empty string elements.
  { name = "multiple IDs (Classic quest 2)", field = "inGroupWith", input = {23,24}, expected = {23,24} },
  { name = "single reputation reward (Classic quest 2)", field = "reputationReward", input = {{81,250}}, expected = {{81,250}} },
  { name = "multiple reputation rewards (Classic quest 32)", field = "reputationReward",
    input = {{76,350},{81,350},{369,350},{530,350}}, expected = {{76,350},{81,350},{369,350},{530,350}} },
  { name = "empty text elements (Classic quest 25, shortened)", field = "objectivesText",
    input = {"Explore","","Return"}, expected = {"Explore","","Return"} },
  { name = "skill with zero value (Classic quest 715)", field = "requiredSkill", input = {171,0}, expected = {171,0} },
  { name = "negative reputation (Era quest 1036)", field = "requiredMaxRep", input = {21,-6000}, expected = {21,-6000} },
  { name = "zero pair (synthetic)", field = "requiredSkill", input = {0,0} },
  { name = "empty ordinary array", field = "inGroupWith", input = {} },
  { name = "absent ordinary array", field = "inGroupWith" },
  { name = "zero numeric value", field = "requiredLevel", input = 0, expected = 0 },
  { name = "absent numeric value", field = "requiredLevel", expected = 0 },
  { name = "empty scalar string", field = "name", input = "", expected = "" },
  { name = "absent scalar string", field = "name" },

  { name = "phased NPC spawn (Cata NPC 6180)", entity = "Npc", field = "spawns",
    input = {[40]={{50.62,47.39,226}}}, expected = {[40]={{50.62,47.39,226}}} },
  { name = "instance sentinel (Classic NPC 598)", entity = "Npc", field = "spawns",
    input = {[1581]={{-1,-1}}}, expected = {[1581]={{-1,-1}}} },
  { name = "zero phase and sub-grid coordinates (synthetic)", entity = "Npc", field = "spawns",
    input = {[12]={{0,0,0},{0.001,0.002}}}, expected = {[12]={{0,0},{0.001,0.002}}} },
  { name = "multiple waypoint paths (synthetic)", entity = "Npc", field = "waypoints",
    input = {[12]={{{1,2,99},{3,4}},{{5,6}}}}, expected = {[12]={{{1,2},{3,4}},{{5,6}}}} },
  { name = "Alliance faction", entity = "Npc", field = "friendlyToFaction", input = "A", expected = "A" },
  { name = "Horde faction", entity = "Npc", field = "friendlyToFaction", input = "H", expected = "H" },
  { name = "both factions", entity = "Npc", field = "friendlyToFaction", input = "AH", expected = "AH" },
  { name = "empty faction", entity = "Npc", field = "friendlyToFaction", input = "" },
  { name = "single item drop (synthetic)", entity = "Item", field = "npcDrops", input = {6}, expected = {6} },
  { name = "object quest starts (synthetic)", entity = "Object", field = "questStarts", input = {2,7}, expected = {2,7} },
}
