---@class LibQuestieDB
local LibQuestieDB = select(2, ...)

--- Imports
local Corrections = LibQuestieDB.Corrections
local ItemMeta = Corrections.ItemMeta

---@class ItemFixesWotlk
local ItemFixes = {}


C_Timer.After(0, function()
  Corrections.RegisterCorrectionStatic("item",
                                       "ItemFixes-QuestStarts-Wotlk-Automatic",
                                       ItemFixes.LoadItemQuestStarts,
                                       49)

  -- Clear the table to save memory
  ItemFixes = wipe(ItemFixes)
end)

---@return table<ItemId, Correction[]>>
function ItemFixes.LoadItemQuestStarts()
  local itemKeys = ItemMeta.itemKeys

  --! This file is automatically generated from wowhead data by looking at all items that starts a quest and correcting it.
  return {
    --* Item 23904 https://wotlk.wowhead.com/wotlk/item=23904
    --* Starts: Deprecated: Keanna's Will(9613)(https://wotlk.wowhead.com/wotlk/quest=9613)
    [23904] = {
      [itemKeys.startQuest] = 9613,
    },
    --* Item 33121 https://wotlk.wowhead.com/wotlk/item=33121
    --* Starts: One Last Time(11189)(https://wotlk.wowhead.com/wotlk/quest=11189)
    [33121] = {
      [itemKeys.startQuest] = 11189,
    },
    --* Item 33289 https://wotlk.wowhead.com/wotlk/item=33289
    --* Starts: Gjalerbron Attack Plans(11237)(https://wotlk.wowhead.com/wotlk/quest=11237)
    [33289] = {
      [itemKeys.startQuest] = 11237,
    },
    --* Item 33314 https://wotlk.wowhead.com/wotlk/item=33314
    --* Starts: Stop the Ascension!(11249)(https://wotlk.wowhead.com/wotlk/quest=11249)
    [33314] = {
      [itemKeys.startQuest] = 11249,
    },
    --* Item 33345 https://wotlk.wowhead.com/wotlk/item=33345
    --* Starts: Stop the Ascension!(11260)(https://wotlk.wowhead.com/wotlk/quest=11260)
    [33345] = {
      [itemKeys.startQuest] = 11260,
    },
    --* Item 33347 https://wotlk.wowhead.com/wotlk/item=33347
    --* Starts: Gjalerbron Attack Plans(11266)(https://wotlk.wowhead.com/wotlk/quest=11266)
    [33347] = {
      [itemKeys.startQuest] = 11266,
    },
    --* Item 33961 https://wotlk.wowhead.com/wotlk/item=33961
    --* Starts: It's a Scourge Device(11395)(https://wotlk.wowhead.com/wotlk/quest=11395)
    [33961] = {
      [itemKeys.startQuest] = 11395,
    },
    --* Item 33962 https://wotlk.wowhead.com/wotlk/item=33962
    --* Starts: It's a Scourge Device(11398)(https://wotlk.wowhead.com/wotlk/quest=11398)
    [33962] = {
      [itemKeys.startQuest] = 11398,
    },
    --* Item 34090 https://wotlk.wowhead.com/wotlk/item=34090
    --* Starts: The Slumbering King(11452)(https://wotlk.wowhead.com/wotlk/quest=11452)
    [34090] = {
      [itemKeys.startQuest] = 11452,
    },
    --* Item 34091 https://wotlk.wowhead.com/wotlk/item=34091
    --* Starts: The Slumbering King(11453)(https://wotlk.wowhead.com/wotlk/quest=11453)
    [34091] = {
      [itemKeys.startQuest] = 11453,
    },
    --* Item 34777 https://wotlk.wowhead.com/wotlk/item=34777
    --* Starts: What the Cold Wind Brings...(11632)(https://wotlk.wowhead.com/wotlk/quest=11632)
    [34777] = {
      [itemKeys.startQuest] = 11632,
    },
    --* Item 34815 https://wotlk.wowhead.com/wotlk/item=34815
    --* Starts: The Spire of Blood(11654)(https://wotlk.wowhead.com/wotlk/quest=11654)
    [34815] = {
      [itemKeys.startQuest] = 11654,
    },
    --* Item 34984 https://wotlk.wowhead.com/wotlk/item=34984
    --* Starts: The Ultrasonic Screwdriver(11729)(https://wotlk.wowhead.com/wotlk/quest=11729)
    [34984] = {
      [itemKeys.startQuest] = 11729,
    },
    --* Item 35120 https://wotlk.wowhead.com/wotlk/item=35120
    --* Starts: Cultists Among Us(11790)(https://wotlk.wowhead.com/wotlk/quest=11790)
    [35120] = {
      [itemKeys.startQuest] = 11790,
    },
    --* Item 35648 https://wotlk.wowhead.com/wotlk/item=35648
    --* Starts: Puzzling...(11941)(https://wotlk.wowhead.com/wotlk/quest=11941)
    [35648] = {
      [itemKeys.startQuest] = 11941,
    },
    --* Item 35744 https://wotlk.wowhead.com/wotlk/item=35744
    --* Starts: zzOLDFortune Card: Silver(11987)(https://wotlk.wowhead.com/wotlk/quest=11987)
    [35744] = {
      [itemKeys.startQuest] = 11987,
    },
    --* Item 35855 https://wotlk.wowhead.com/wotlk/item=35855
    --* Starts: A Letter Home(12021)(https://wotlk.wowhead.com/wotlk/quest=12021)
    [35855] = {
      [itemKeys.startQuest] = 12021,
    },
    --* Item 36742 https://wotlk.wowhead.com/wotlk/item=36742
    --* Starts: A Strange Device(12055)(https://wotlk.wowhead.com/wotlk/quest=12055)
    [36742] = {
      [itemKeys.startQuest] = 12055,
    },
    --* Item 36744 https://wotlk.wowhead.com/wotlk/item=36744
    --* Starts: The Flesh-Bound Tome(12057)(https://wotlk.wowhead.com/wotlk/quest=12057)
    [36744] = {
      [itemKeys.startQuest] = 12057,
    },
    --* Item 36746 https://wotlk.wowhead.com/wotlk/item=36746
    --* Starts: A Strange Device(12059)(https://wotlk.wowhead.com/wotlk/quest=12059)
    [36746] = {
      [itemKeys.startQuest] = 12059,
    },
    --* Item 36756 https://wotlk.wowhead.com/wotlk/item=36756
    --* Starts: A Letter for Home(12067)(https://wotlk.wowhead.com/wotlk/quest=12067)
    [36756] = {
      [itemKeys.startQuest] = 12067,
    },
    --* Item 36780 https://wotlk.wowhead.com/wotlk/item=36780
    --* Starts: A Letter for Home(12085)(https://wotlk.wowhead.com/wotlk/quest=12085)
    [36780] = {
      [itemKeys.startQuest] = 12085,
    },
    --* Item 36855 https://wotlk.wowhead.com/wotlk/item=36855
    --* Starts: Disturbing Implications(12146)(https://wotlk.wowhead.com/wotlk/quest=12146)
    [36855] = {
      [itemKeys.startQuest] = 12146,
    },
    --* Item 36856 https://wotlk.wowhead.com/wotlk/item=36856
    --* Starts: Disturbing Implications(12147)(https://wotlk.wowhead.com/wotlk/quest=12147)
    [36856] = {
      [itemKeys.startQuest] = 12147,
    },
    --* Item 36940 https://wotlk.wowhead.com/wotlk/item=36940
    --* Starts: Descent into Darkness(12105)(https://wotlk.wowhead.com/wotlk/quest=12105)
    [36940] = {
      [itemKeys.startQuest] = 12105,
    },
    --* Item 36958 https://wotlk.wowhead.com/wotlk/item=36958
    --* Starts: The Favor of Zangus(12168)(https://wotlk.wowhead.com/wotlk/quest=12168)
    [36958] = {
      [itemKeys.startQuest] = 12168,
    },
    --* Item 37163 https://wotlk.wowhead.com/wotlk/item=37163
    --* Starts: Rogues Deck(12517)(https://wotlk.wowhead.com/wotlk/quest=12517)
    [37163] = {
      [itemKeys.startQuest] = 12517,
    },
    --* Item 37164 https://wotlk.wowhead.com/wotlk/item=37164
    --* Starts: Swords Deck(12798)(https://wotlk.wowhead.com/wotlk/quest=12798)
    [37164] = {
      [itemKeys.startQuest] = 12798,
    },
    --* Item 37432 https://wotlk.wowhead.com/wotlk/item=37432
    --* Starts: The Rod of Compulsion(12271)(https://wotlk.wowhead.com/wotlk/quest=12271)
    [37432] = {
      [itemKeys.startQuest] = 12271,
    },
    --* Item 37830 https://wotlk.wowhead.com/wotlk/item=37830
    --* Starts: Mikhail's Journal(12423)(https://wotlk.wowhead.com/wotlk/quest=12423)
    [37830] = {
      [itemKeys.startQuest] = 12423,
    },
    --* Item 37833 https://wotlk.wowhead.com/wotlk/item=37833
    --* Starts: The Fate of the Ruby Dragonshrine(12419)(https://wotlk.wowhead.com/wotlk/quest=12419)
    [37833] = {
      [itemKeys.startQuest] = 12419,
    },
    --* Item 38321 https://wotlk.wowhead.com/wotlk/item=38321
    --* Starts: Strange Mojo(12507)(https://wotlk.wowhead.com/wotlk/quest=12507)
    [38321] = {
      [itemKeys.startQuest] = 12507,
    },
    --* Item 38567 https://wotlk.wowhead.com/wotlk/item=38567
    --* Starts: Blahblah[PH](12590)(https://wotlk.wowhead.com/wotlk/quest=12590)
    [38567] = {
      [itemKeys.startQuest] = 12590,
    },
    --* Item 38660 https://wotlk.wowhead.com/wotlk/item=38660
    --* Starts: An Invitation, of Sorts...(12631)(https://wotlk.wowhead.com/wotlk/quest=12631)
    [38660] = {
      [itemKeys.startQuest] = 12631,
    },
    --* Item 38673 https://wotlk.wowhead.com/wotlk/item=38673
    --* Starts: Darkness Calling(12633)(https://wotlk.wowhead.com/wotlk/quest=12633)
    [38673] = {
      [itemKeys.startQuest] = 12633,
    },
    --* Item 39713 https://wotlk.wowhead.com/wotlk/item=39713
    --* Starts: Welcome!(12781)(https://wotlk.wowhead.com/wotlk/quest=12781)
    [39713] = {
      [itemKeys.startQuest] = 12781,
    },
    --* Item 40666 https://wotlk.wowhead.com/wotlk/item=40666
    --* Starts: The Grand (Admiral's) Plan(12839)(https://wotlk.wowhead.com/wotlk/quest=12839)
    [40666] = {
      [itemKeys.startQuest] = 12839,
    },
    --* Item 41267 https://wotlk.wowhead.com/wotlk/item=41267
    --* Starts: SCRAP-E(12888)(https://wotlk.wowhead.com/wotlk/quest=12888)
    [41267] = {
      [itemKeys.startQuest] = 12888,
    },
    --* Item 41556 https://wotlk.wowhead.com/wotlk/item=41556
    --* Starts: The Refiner's Fire(12922)(https://wotlk.wowhead.com/wotlk/quest=12922)
    [41556] = {
      [itemKeys.startQuest] = 12922,
    },
    --* Item 42203 https://wotlk.wowhead.com/wotlk/item=42203
    --* Starts: Armor of Darkness(12979)(https://wotlk.wowhead.com/wotlk/quest=12979)
    [42203] = {
      [itemKeys.startQuest] = 12979,
    },
    --* Item 42772 https://wotlk.wowhead.com/wotlk/item=42772
    --* Starts: The Sum is Greater than the Parts(13043)(https://wotlk.wowhead.com/wotlk/quest=13043)
    [42772] = {
      [itemKeys.startQuest] = 13043,
    },
    --* Item 43242 https://wotlk.wowhead.com/wotlk/item=43242
    --* Starts: Jagged Shards(13136)(https://wotlk.wowhead.com/wotlk/quest=13136)
    [43242] = {
      [itemKeys.startQuest] = 13136,
    },
    --* Item 43297 https://wotlk.wowhead.com/wotlk/item=43297
    --* Starts: Necklace Repair(13148)(https://wotlk.wowhead.com/wotlk/quest=13148)
    [43297] = {
      [itemKeys.startQuest] = 13148,
    },
    --* Item 43512 https://wotlk.wowhead.com/wotlk/item=43512
    --* Starts: Funky Fungi(13204)(https://wotlk.wowhead.com/wotlk/quest=13204)
    [43512] = {
      [itemKeys.startQuest] = 13204,
    },
    --* Item 44148 https://wotlk.wowhead.com/wotlk/item=44148
    --* Starts: Mages Deck(12518)(https://wotlk.wowhead.com/wotlk/quest=12518)
    [44148] = {
      [itemKeys.startQuest] = 12518,
    },
    --* Item 44158 https://wotlk.wowhead.com/wotlk/item=44158
    --* Starts: Demons Deck(13311)(https://wotlk.wowhead.com/wotlk/quest=13311)
    [44158] = {
      [itemKeys.startQuest] = 13311,
    },
    --* Item 44259 https://wotlk.wowhead.com/wotlk/item=44259
    --* Starts: Darkmoon Prisms Deck(13324)(https://wotlk.wowhead.com/wotlk/quest=13324)
    [44259] = {
      [itemKeys.startQuest] = 13324,
    },
    --* Item 44276 https://wotlk.wowhead.com/wotlk/item=44276
    --* Starts: Darkmoon Chaos Deck(13325)(https://wotlk.wowhead.com/wotlk/quest=13325)
    [44276] = {
      [itemKeys.startQuest] = 13325,
    },
    --* Item 44294 https://wotlk.wowhead.com/wotlk/item=44294
    --* Starts: Darkmoon Undeath Deck(13327)(https://wotlk.wowhead.com/wotlk/quest=13327)
    [44294] = {
      [itemKeys.startQuest] = 13327,
    },
    --* Item 44326 https://wotlk.wowhead.com/wotlk/item=44326
    --* Starts: Darkmoon Nobles Deck(13326)(https://wotlk.wowhead.com/wotlk/quest=13326)
    [44326] = {
      [itemKeys.startQuest] = 13326,
    },
    --* Item 44569 https://wotlk.wowhead.com/wotlk/item=44569
    --* Starts: The Key to the Focusing Iris(13372)(https://wotlk.wowhead.com/wotlk/quest=13372)
    [44569] = {
      [itemKeys.startQuest] = 13372,
    },
    --* Item 44577 https://wotlk.wowhead.com/wotlk/item=44577
    --* Starts: The Heroic Key to the Focusing Iris(13375)(https://wotlk.wowhead.com/wotlk/quest=13375)
    [44577] = {
      [itemKeys.startQuest] = 13375,
    },
    --* Item 44725 https://wotlk.wowhead.com/wotlk/item=44725
    --* Starts: Everfrost(13420)(https://wotlk.wowhead.com/wotlk/quest=13420)
    [44725] = {
      [itemKeys.startQuest] = 13420,
    },
    --* Item 45039 https://wotlk.wowhead.com/wotlk/item=45039
    --* Starts: Ancient History(13622)(https://wotlk.wowhead.com/wotlk/quest=13622)
    [45039] = {
      [itemKeys.startQuest] = 13622,
    },
    --* Item 45506 https://wotlk.wowhead.com/wotlk/item=45506
    --* Starts: Archivum Data Disc(13604)(https://wotlk.wowhead.com/wotlk/quest=13604)
    [45506] = {
      [itemKeys.startQuest] = 13604,
    },
    --* Item 45857 https://wotlk.wowhead.com/wotlk/item=45857
    --* Starts: Heroic: Archivum Data Disc(13817)(https://wotlk.wowhead.com/wotlk/quest=13817)
    [45857] = {
      [itemKeys.startQuest] = 13817,
    },
    --* Item 46004 https://wotlk.wowhead.com/wotlk/item=46004
    --* Starts: Sealed Vial of Poison(13845)(https://wotlk.wowhead.com/wotlk/quest=13845)
    [46004] = {
      [itemKeys.startQuest] = 13845,
    },
    --* Item 46052 https://wotlk.wowhead.com/wotlk/item=46052
    --* Starts: All Is Well That Ends Well(13631)(https://wotlk.wowhead.com/wotlk/quest=13631)
    [46052] = {
      [itemKeys.startQuest] = 13631,
    },
    --* Item 46053 https://wotlk.wowhead.com/wotlk/item=46053
    --* Starts: Heroic: All Is Well That Ends Well(13819)(https://wotlk.wowhead.com/wotlk/quest=13819)
    [46053] = {
      [itemKeys.startQuest] = 13819,
    },
    --* Item 46875 https://wotlk.wowhead.com/wotlk/item=46875
    --* Starts: Learn to Ride in Elwynn Forest(14079)(https://wotlk.wowhead.com/wotlk/quest=14079)
    [46875] = {
      [itemKeys.startQuest] = 14079,
    },
    --* Item 46876 https://wotlk.wowhead.com/wotlk/item=46876
    --* Starts: Learn to Ride in Darnassus(14085)(https://wotlk.wowhead.com/wotlk/quest=14085)
    [46876] = {
      [itemKeys.startQuest] = 14085,
    },
    --* Item 46877 https://wotlk.wowhead.com/wotlk/item=46877
    --* Starts: Learn to Ride in Dun Morogh(14083)(https://wotlk.wowhead.com/wotlk/quest=14083)
    [46877] = {
      [itemKeys.startQuest] = 14083,
    },
    --* Item 46878 https://wotlk.wowhead.com/wotlk/item=46878
    --* Starts: Learn to Ride in Dun Morogh(14084)(https://wotlk.wowhead.com/wotlk/quest=14084)
    [46878] = {
      [itemKeys.startQuest] = 14084,
    },
    --* Item 46879 https://wotlk.wowhead.com/wotlk/item=46879
    --* Starts: Learn to Ride at the Exodar(14082)(https://wotlk.wowhead.com/wotlk/quest=14082)
    [46879] = {
      [itemKeys.startQuest] = 14082,
    },
    --* Item 46880 https://wotlk.wowhead.com/wotlk/item=46880
    --* Starts: Learn to Ride in Orgrimmar(14086)(https://wotlk.wowhead.com/wotlk/quest=14086)
    [46880] = {
      [itemKeys.startQuest] = 14086,
    },
    --* Item 46881 https://wotlk.wowhead.com/wotlk/item=46881
    --* Starts: Learn to Ride in Tirisfal Glades(14089)(https://wotlk.wowhead.com/wotlk/quest=14089)
    [46881] = {
      [itemKeys.startQuest] = 14089,
    },
    --* Item 46882 https://wotlk.wowhead.com/wotlk/item=46882
    --* Starts: Learn to Ride in the Eversong Woods(14081)(https://wotlk.wowhead.com/wotlk/quest=14081)
    [46882] = {
      [itemKeys.startQuest] = 14081,
    },
    --* Item 46883 https://wotlk.wowhead.com/wotlk/item=46883
    --* Starts: Learn to Ride in Durotar(14088)(https://wotlk.wowhead.com/wotlk/quest=14088)
    [46883] = {
      [itemKeys.startQuest] = 14088,
    },
    --* Item 46884 https://wotlk.wowhead.com/wotlk/item=46884
    --* Starts: Learn to Ride in Mulgore(14087)(https://wotlk.wowhead.com/wotlk/quest=14087)
    [46884] = {
      [itemKeys.startQuest] = 14087,
    },
    --* Item 46955 https://wotlk.wowhead.com/wotlk/item=46955
    --* Starts: Identifying the Remains(14095)(https://wotlk.wowhead.com/wotlk/quest=14095)
    [46955] = {
      [itemKeys.startQuest] = 14095,
    },
    --* Item 47246 https://wotlk.wowhead.com/wotlk/item=47246
    --* Starts: Writ of Merit(14160)(https://wotlk.wowhead.com/wotlk/quest=14160)
    [47246] = {
      [itemKeys.startQuest] = 14160,
    },
    --* Item 48679 https://wotlk.wowhead.com/wotlk/item=48679
    --* Starts: Waterlogged Recipe(14203)(https://wotlk.wowhead.com/wotlk/quest=14203)
    [48679] = {
      [itemKeys.startQuest] = 14203,
    },
    --* Item 49205 https://wotlk.wowhead.com/wotlk/item=49205
    --* Starts: An Unholy Alliance(14352)(https://wotlk.wowhead.com/wotlk/quest=14352)
    [49205] = {
      [itemKeys.startQuest] = 14352,
    },
    --* Item 49641 https://wotlk.wowhead.com/wotlk/item=49641
    --* Starts: Something is in the Air (and it Ain't Love)(14483)(https://wotlk.wowhead.com/wotlk/quest=14483)
    [49641] = {
      [itemKeys.startQuest] = 14483,
    },
    --* Item 49643 https://wotlk.wowhead.com/wotlk/item=49643
    --* Starts: A Most Puzzling Circumstance(24429)(https://wotlk.wowhead.com/wotlk/quest=24429)
    [49643] = {
      [itemKeys.startQuest] = 24429,
    },
    --* Item 49644 https://wotlk.wowhead.com/wotlk/item=49644
    --* Starts: A Most Puzzling Circumstance(24428)(https://wotlk.wowhead.com/wotlk/quest=24428)
    [49644] = {
      [itemKeys.startQuest] = 24428,
    },
    --* Item 49667 https://wotlk.wowhead.com/wotlk/item=49667
    --* Starts: Waterlogged Recipe(24431)(https://wotlk.wowhead.com/wotlk/quest=24431)
    [49667] = {
      [itemKeys.startQuest] = 24431,
    },
    --* Item 49676 https://wotlk.wowhead.com/wotlk/item=49676
    --* Starts: Battle Plans Of The Kvaldir(24442)(https://wotlk.wowhead.com/wotlk/quest=24442)
    [49676] = {
      [itemKeys.startQuest] = 24442,
    },
    --* Item 50320 https://wotlk.wowhead.com/wotlk/item=50320
    --* Starts: Something is in the Air (and it Ain't Love)(24745)(https://wotlk.wowhead.com/wotlk/quest=24745)
    [50320] = {
      [itemKeys.startQuest] = 24745,
    },
    --* Item 50379 https://wotlk.wowhead.com/wotlk/item=50379
    --* Starts: The Battered Hilt(14443)(https://wotlk.wowhead.com/wotlk/quest=14443)
    [50379] = {
      [itemKeys.startQuest] = 14443,
    },
    --* Item 50380 https://wotlk.wowhead.com/wotlk/item=50380
    --* Starts: The Battered Hilt(24554)(https://wotlk.wowhead.com/wotlk/quest=24554)
    [50380] = {
      [itemKeys.startQuest] = 24554,
    },
    --* Item 51315 https://wotlk.wowhead.com/wotlk/item=51315
    --* Starts: Personal Property(24914)(https://wotlk.wowhead.com/wotlk/quest=24914)
    [51315] = {
      [itemKeys.startQuest] = 24914,
    },
  }
end
