---@class ForeverItemTraces
local ForeverItemTraces = QuestieLoader:CreateModule("ForeverItemTraces")

---@type QuestieDB
local QuestieDB = QuestieLoader:ImportModule("QuestieDB")

-- Generated by QuestieTrace extract (tools/trace-analyzer)
-- Source trace files: 1548
-- Sessions aggregated: 3405
-- Generated at: 2026-10-02T17:33:43.682Z
function ForeverItemTraces:Load()
    local itemKeys = QuestieDB.itemKeys

    return {
        [203754] = {
            [itemKeys.name] = "Archmage Antonidas: The Unabridged Autobiography",
            [itemKeys.objectDrops_add] = {386691},
        },
        [203755] = {
            [itemKeys.name] = "Archmage Theocritus' Research Journal",
            [itemKeys.objectDrops_add] = {386759},
        },
        [208185] = {
            [itemKeys.name] = "The Apothecary's Metaphysical Primer",
            [itemKeys.objectDrops_add] = {405879},
        },
        [208800] = {
            [itemKeys.name] = "Baxtan: On Destructive Magics",
            [itemKeys.objectDrops_add] = {407566},
        },
        [208860] = {
            [itemKeys.name] = "Rumi of Gnomeregan: The Collected Works",
            [itemKeys.objectDrops_add] = {408014},
        },
        [209843] = {
            [itemKeys.name] = "Nar'thalas Almanac, Vol. 74",
            [itemKeys.objectDrops_add] = {409496},
        },
        [209844] = {
            [itemKeys.name] = "The Dalaran Digest, Vol. 23",
            [itemKeys.objectDrops_add] = {409501},
        },
        [209845] = {
            [itemKeys.name] = "Bewitchments and Glamours",
            [itemKeys.objectDrops_add] = {409562},
        },
        [209846] = {
            [itemKeys.name] = "Secrets of the Dreamers",
            [itemKeys.objectDrops_add] = {409692},
        },
        [209847] = {
            [itemKeys.name] = "Arcanic Systems Manual",
            [itemKeys.objectDrops_add] = {409700},
        },
        [209848] = {
            [itemKeys.name] = "Goaz Scrolls",
            [itemKeys.objectDrops_add] = {409717},
        },
        [209849] = {
            [itemKeys.name] = "Crimes Against Anatomy",
            [itemKeys.objectDrops_add] = {409735},
        },
        [209850] = {
            [itemKeys.name] = "Runes of the Sorcerer-Kings",
            [itemKeys.objectDrops_add] = {409731},
        },
        [209851] = {
            [itemKeys.name] = "Fury of the Land",
            [itemKeys.objectDrops_add] = {409711},
        },
        [211780] = {
            [itemKeys.name] = "Scroll: KWYJIBO",
            [itemKeys.npcDrops_add] = {36,40,43,95,114,117,448,471,474,480,732,1162,1172,1236,1523,1526,1534,1537,1544,1545,1766,1767,1797,1867,1922,1941,2964,3116,3118,3197,3242,3265,3272,250282,251245,251284,251291,251622,251661,251676,251707,251918,252068,252664,252762,252765,252820,254588,254596,254626,256092,267006,270201,275437},
            [itemKeys.objectDrops_add] = {106318,106319,626752},
        },
        [211784] = {
            [itemKeys.name] = "Scroll: WUBBA WUBBA",
            [itemKeys.npcDrops_add] = {424,458,517,2339,3840,250622},
            [itemKeys.objectDrops_add] = {2850},
        },
        [211785] = {
            [itemKeys.name] = "Scroll: CWAL",
            [itemKeys.npcDrops_add] = {46,114,117,118,123,285,454,456,474,478,500,515,524,732,735,822,1121,1122,1166,1211,1236,1426,1537,1548,1674,1782,2009,2012,2069,2070,2959,2964,3099,3112,3119,3129,3131,3255,3273,12320,250283,251284,251291,251676,251707,251918,252068,252665,252764,252802,252820,253282,256092,260157,260430,267006,270201,271530,271712,275437},
            [itemKeys.objectDrops_add] = {106318,106319},
        },
        [211786] = {
            [itemKeys.name] = "Scroll: CHAP BALK WELLES",
            [itemKeys.npcDrops_add] = {40,46,95,97,114,116,117,118,157,454,474,478,500,504,590,732,735,1116,1121,1138,1172,1211,1526,1537,1548,1766,1778,1779,1912,1922,1934,1941,3130,3198,3207,3242,3255,3266,3276,6123,250283,251291,251661,251662,251676,252068,252664,252665,252762,252763,252802,253195,254626,256966,270201,271587},
            [itemKeys.objectDrops_add] = {106318,106319,626752},
        },
        [211787] = {
            [itemKeys.name] = "Scroll: LOWER PING WHOMEVER",
            [itemKeys.npcDrops_add] = {40,95,114,116,118,126,474,478,480,504,589,1126,1162,1175,1176,1522,1527,1536,1538,1544,1553,1555,1693,1922,1941,2008,2185,2321,3130,3198,3272,250282,251245,251676,251707,252664,252665,252764,252820,253195,254588,254596,254626,255534,256092,257532,267006,270201},
            [itemKeys.objectDrops_add] = {106318,106319,626752},
        },
        [211853] = {
            [itemKeys.name] = "Scroll: VOCE WELL",
            [itemKeys.npcDrops_add] = {121,548,1943},
            [itemKeys.objectDrops_add] = {2849},
        },
        [211854] = {
            [itemKeys.name] = "Scroll: OMIT KESA",
            [itemKeys.npcDrops_add] = {598,1205,1417,3250,3667,250622},
            [itemKeys.objectDrops_add] = {2849},
        },
        [211855] = {
            [itemKeys.name] = "Scroll: STHENIC LUNATE",
            [itemKeys.npcDrops_add] = {598,1179,3840},
        },
        [213165] = {
            [itemKeys.name] = "Basilisks: Should Petrification be Feared?",
            [itemKeys.objectDrops_add] = {421526},
        },
        [213564] = {
            [itemKeys.name] = "Scroll of Minor Evocation",
        },
        [215257] = {
            [itemKeys.name] = "Scroll of Comprehension",
        },
        [215815] = {
            [itemKeys.name] = "Defensive Magics 101",
            [itemKeys.objectDrops_add] = {423896},
        },
        [215816] = {
            [itemKeys.name] = "A Web of Lies: Debunking Myths and Legends",
            [itemKeys.objectDrops_add] = {423897},
        },
        [215820] = {
            [itemKeys.name] = "Mummies: A Guide to the Unsavory Undead",
            [itemKeys.objectDrops_add] = {423899},
        },
        [220349] = {
            [itemKeys.name] = "Stonewrought Design",
            [itemKeys.objectDrops_add] = {441251},
        },
        [220350] = {
            [itemKeys.name] = "Venomous Journeys",
            [itemKeys.objectDrops_add] = {441252},
        },
        [220352] = {
            [itemKeys.name] = "A Mind of Metal",
            [itemKeys.objectDrops_add] = {441253},
        },
        [228133] = {
            [itemKeys.name] = "Magma or Lava?",
            [itemKeys.objectDrops_add] = {463206},
        },
        [228134] = {
            [itemKeys.name] = "Northern Kalimdor - A Comprehensive Guide",
            [itemKeys.objectDrops_add] = {463209},
        },
        [228135] = {
            [itemKeys.name] = "A Study of the Light",
            [itemKeys.objectDrops_add] = {463207},
        },
        [228136] = {
            [itemKeys.name] = "Ka-Boom!",
            [itemKeys.objectDrops_add] = {463214},
        },
        [228141] = {
            [itemKeys.name] = "Necromancy 101",
            [itemKeys.objectDrops_add] = {463211},
        },
        [246213] = {
            [itemKeys.name] = "Sturdy Lumber",
            [itemKeys.objectDrops_add] = {554626},
        },
        [247805] = {
            [itemKeys.name] = "Stolen Enchanting Supplies",
            [itemKeys.objectDrops_add] = {561159},
        },
        [247813] = {
            [itemKeys.name] = "Waterlogged Saw",
            [itemKeys.objectDrops_add] = {562103},
        },
        [247816] = {
            [itemKeys.name] = "Mining Tools",
            [itemKeys.objectDrops_add] = {562114},
        },
        [247817] = {
            [itemKeys.name] = "Waterlogged Axe",
            [itemKeys.objectDrops_add] = {562105},
        },
        [247818] = {
            [itemKeys.name] = "Waterlogged Toolbox",
            [itemKeys.objectDrops_add] = {562106},
        },
        [247826] = {
            [itemKeys.name] = "Croaky's Head",
            [itemKeys.npcDrops_add] = {248278},
        },
        [247834] = {
            [itemKeys.name] = "Nibbled-On Book",
            [itemKeys.npcDrops_add] = {6},
        },
        [247839] = {
            [itemKeys.name] = "Stolen Book",
            [itemKeys.npcDrops_add] = {6,80,257},
        },
        [247862] = {
            [itemKeys.name] = "Elmpaw's Head",
            [itemKeys.npcDrops_add] = {248299},
        },
        [247877] = {
            [itemKeys.name] = "Rough Wolf Pelt",
            [itemKeys.npcDrops_add] = {1922},
        },
        [247883] = {
            [itemKeys.name] = "Crude Wax Effigy",
            [itemKeys.npcDrops_add] = {476},
        },
        [247884] = {
            [itemKeys.name] = "Luminous Residue",
        },
        [247886] = {
            [itemKeys.name] = "Sack of \"Picture\" Books",
            [itemKeys.npcDrops_add] = {248362},
        },
        [248001] = {
            [itemKeys.name] = "Lost Book",
            [itemKeys.npcDrops_add] = {40,475},
        },
        [248002] = {
            [itemKeys.name] = "Picture Book: Fun with Elementals",
            [itemKeys.npcDrops_add] = {248464},
        },
        [248003] = {
            [itemKeys.name] = "Geomancy for Curious Young Wizards",
            [itemKeys.npcDrops_add] = {248474},
        },
        [248004] = {
            [itemKeys.name] = "Arcane Explainer: Magical Stuff in Simple Words",
            [itemKeys.npcDrops_add] = {471},
        },
        [248682] = {
            [itemKeys.name] = "Waylaid Crate: Apprentice Herbs",
            [itemKeys.npcDrops_add] = {97,114,454,474,1781,2237,3244,4127},
        },
        [248683] = {
            [itemKeys.name] = "Waylaid Crate: Apprentice Ore",
            [itemKeys.npcDrops_add] = {424,1942,3242,3276},
        },
        [248684] = {
            [itemKeys.name] = "Waylaid Crate: Apprentice Textiles",
            [itemKeys.npcDrops_add] = {118,589,2338,3246,3277,3284,3394},
        },
        [248685] = {
            [itemKeys.name] = "Waylaid Crate: Apprentice Curiosities",
            [itemKeys.npcDrops_add] = {114,589,2012,3276,267006},
        },
        [248686] = {
            [itemKeys.name] = "Waylaid Crate: Journeyman Herbs",
            [itemKeys.npcDrops_add] = {1417},
        },
        [248687] = {
            [itemKeys.name] = "Waylaid Crate: Journeyman Ore",
            [itemKeys.npcDrops_add] = {590,1658,3272},
        },
        [248688] = {
            [itemKeys.name] = "Waylaid Crate: Journeyman Textiles",
            [itemKeys.npcDrops_add] = {122},
        },
        [248689] = {
            [itemKeys.name] = "Waylaid Crate: Journeyman Curiosities",
            [itemKeys.npcDrops_add] = {430,3459},
        },
        [248702] = {
            [itemKeys.name] = "Waylaid Crate: Apprentice Fabrics",
            [itemKeys.npcDrops_add] = {1197,1554,6124},
        },
        [248703] = {
            [itemKeys.name] = "Waylaid Crate: Apprentice Ingots",
            [itemKeys.npcDrops_add] = {117,589,590,1523,1532,3276,3386,6123,9336},
        },
        [248707] = {
            [itemKeys.name] = "Waylaid Crate: Journeyman Parts",
            [itemKeys.npcDrops_add] = {2183,3459},
        },
        [249391] = {
            [itemKeys.name] = "Pyrite",
            [itemKeys.objectDrops_add] = {1731,1732,1735,3763,3764},
        },
        [249399] = {
            [itemKeys.name] = "Frilled Lichen",
            [itemKeys.objectDrops_add] = {1619,1620,1621,1622,2045,657383},
        },
        [249427] = {
            [itemKeys.name] = "Pristine Leather",
            [itemKeys.npcDrops_add] = {454,565,833,1693,3242,3255,4127,4128},
        },
        [249865] = {
            [itemKeys.name] = "Peace Tea",
            [itemKeys.npcDrops_add] = {2962},
        },
        [249879] = {
            [itemKeys.name] = "Recipe: Peace Tea",
            [itemKeys.npcDrops_add] = {1397},
        },
        [250187] = {
            [itemKeys.name] = "Recipe: Tasty Raptor Bites",
            [itemKeys.npcDrops_add] = {1020,3255},
        },
        [250188] = {
            [itemKeys.name] = "Recipe: Breakfast Omelette",
            [itemKeys.npcDrops_add] = {428},
        },
        [250366] = {
            [itemKeys.name] = "Recipe: Minor Cleric's Elixir",
            [itemKeys.npcDrops_add] = {1545,250283},
        },
        [250375] = {
            [itemKeys.name] = "Recipe: Minor Mageblood Elixir",
            [itemKeys.npcDrops_add] = {1134},
        },
        [250380] = {
            [itemKeys.name] = "Recipe: Elixir of Minor Spirit",
            [itemKeys.npcDrops_add] = {3128},
        },
        [250976] = {
            [itemKeys.name] = "Recipe: Minor Spellblasting Potion",
            [itemKeys.npcDrops_add] = {476},
        },
        [250977] = {
            [itemKeys.name] = "Recipe: Lesser Spellblasting Potion",
            [itemKeys.npcDrops_add] = {2169},
        },
        [250982] = {
            [itemKeys.name] = "Recipe: Minor Frenzy Potion",
            [itemKeys.npcDrops_add] = {2015,2963},
        },
        [250983] = {
            [itemKeys.name] = "Recipe: Lesser Frenzy Potion",
            [itemKeys.npcDrops_add] = {1943},
        },
        [251360] = {
            [itemKeys.name] = "Plans: Veteran's Gloves",
            [itemKeys.npcDrops_add] = {3669},
        },
        [251362] = {
            [itemKeys.name] = "Plans: Protector's Gloves",
            [itemKeys.npcDrops_add] = {11517},
        },
        [251384] = {
            [itemKeys.name] = "Plans: Crusader's Silvered Chain Helm",
            [itemKeys.npcDrops_add] = {5775},
        },
        [251918] = {
            [itemKeys.name] = "Scrawny Ursera Claw",
            [itemKeys.npcDrops_add] = {250926},
        },
        [251924] = {
            [itemKeys.name] = "Signet of Akir",
            [itemKeys.npcDrops_add] = {251160},
        },
        [251925] = {
            [itemKeys.name] = "Tattered Ursera Feather",
            [itemKeys.npcDrops_add] = {250926,250937,251115},
        },
        [251927] = {
            [itemKeys.name] = "Chipped Cirrusfly Stinger",
            [itemKeys.npcDrops_add] = {251169,251402,251404},
        },
        [251928] = {
            [itemKeys.name] = "Torn Insect Wing",
            [itemKeys.npcDrops_add] = {251169,251402,251404},
        },
        [251930] = {
            [itemKeys.name] = "Minor Essence of the Four Winds",
            [itemKeys.npcDrops_add] = {251143},
        },
        [251931] = {
            [itemKeys.name] = "Depleted Windstone",
            [itemKeys.npcDrops_add] = {251143},
        },
        [251932] = {
            [itemKeys.name] = "Sharpened Cirrusfly Stinger",
            [itemKeys.npcDrops_add] = {251402},
        },
        [252022] = {
            [itemKeys.name] = "Galestrider Jerky",
            [itemKeys.npcDrops_add] = {251918,251966,252068,252664,252665,252762,252763,252764,252765,252767,252802,252820,253195,253511,253622,254596,254626,255534,256966,270201},
            [itemKeys.objectDrops_add] = {626718,626752},
        },
        [252023] = {
            [itemKeys.name] = "Zaalanarr Sharp",
            [itemKeys.objectDrops_add] = {626718},
        },
        [252028] = {
            [itemKeys.name] = "Fresh Gustberry Bread",
            [itemKeys.npcDrops_add] = {251918,251966,252068,252664,252665,252762,252763,252764,252765,252767,252802,252820,253195,253511,253622,254596,254626,255534,256966,270201},
            [itemKeys.objectDrops_add] = {626718,626752},
        },
        [252030] = {
            [itemKeys.name] = "Pungent Skycheddar",
            [itemKeys.npcDrops_add] = {251918,251966,252068,252664,252665,252762,252763,252764,252765,252767,252802,252820,253195,253511,253622,254596,254626,255534,270201},
            [itemKeys.objectDrops_add] = {626752},
        },
        [252031] = {
            [itemKeys.name] = "Crisp Spring Water",
            [itemKeys.npcDrops_add] = {251918,251966,252068,252664,252665,252762,252763,252764,252765,252767,252802,252820,253195,253511,253622,254596,254626,255534,256966,257196,270201},
            [itemKeys.objectDrops_add] = {626718,626752},
        },
        [252032] = {
            [itemKeys.name] = "Red Delicious Stormapple",
            [itemKeys.npcDrops_add] = {251918,252068,252664,252665,252762,252763,252764,252765,252767,252802,252820,253195,253511,253622,254596,254626,255534,256966,257196,270201},
            [itemKeys.objectDrops_add] = {626718,626752},
        },
        [252661] = {
            [itemKeys.name] = "Commander Cyclas's Head",
            [itemKeys.npcDrops_add] = {251966},
        },
        [252665] = {
            [itemKeys.name] = "Head of Urs'anah",
            [itemKeys.npcDrops_add] = {251115},
        },
        [252670] = {
            [itemKeys.name] = "Prideclaw Pelt",
            [itemKeys.npcDrops_add] = {251245},
        },
        [252671] = {
            [itemKeys.name] = "Hoarder's Foot",
            [itemKeys.npcDrops_add] = {251245,256092},
        },
        [252760] = {
            [itemKeys.name] = "Stolen Shen'dar Supplies",
            [itemKeys.npcDrops_add] = {252068},
            [itemKeys.objectDrops_add] = {576179},
        },
        [252777] = {
            [itemKeys.name] = "Pattern: Brawler's Leather Gloves",
            [itemKeys.npcDrops_add] = {647},
        },
        [252801] = {
            [itemKeys.name] = "Pattern: Totemic Leather Hood",
            [itemKeys.npcDrops_add] = {3670},
        },
        [253591] = {
            [itemKeys.name] = "Ripe Stormapple",
            [itemKeys.objectDrops_add] = {578937},
        },
        [253595] = {
            [itemKeys.name] = "Flutterfly Dust",
            [itemKeys.objectDrops_add] = {578959},
        },
        [253596] = {
            [itemKeys.name] = "Blood-Stained Bandit Mask",
            [itemKeys.npcDrops_add] = {252820},
        },
        [253597] = {
            [itemKeys.name] = "Lowlands Galestrider Tenderloin",
            [itemKeys.npcDrops_add] = {251707},
        },
        [253902] = {
            [itemKeys.name] = "Pattern: Filigreed Pristine Gown",
            [itemKeys.npcDrops_add] = {643},
        },
        [253904] = {
            [itemKeys.name] = "Pattern: Filigreed Silky Gown",
            [itemKeys.npcDrops_add] = {11518},
        },
        [253908] = {
            [itemKeys.name] = "Pattern: Filigreed Shadow Gown",
            [itemKeys.npcDrops_add] = {3914},
        },
        [253938] = {
            [itemKeys.name] = "Pattern: Filigreed Pristine Leggings",
            [itemKeys.npcDrops_add] = {639,3670},
        },
        [253940] = {
            [itemKeys.name] = "Pattern: Filigreed Silky Leggings",
            [itemKeys.npcDrops_add] = {4887},
        },
        [254378] = {
            [itemKeys.name] = "Shriekling Talons",
            [itemKeys.npcDrops_add] = {256092},
        },
        [254548] = {
            [itemKeys.name] = "Longshore Murloc Gill",
            [itemKeys.npcDrops_add] = {126,127,171,456,513,515,517},
        },
        [254676] = {
            [itemKeys.name] = "Suspicious Industrial Supplies",
            [itemKeys.objectDrops_add] = {581777},
        },
        [255007] = {
            [itemKeys.name] = "Golem Isospring",
            [itemKeys.npcDrops_add] = {36,114,480},
        },
        [255010] = {
            [itemKeys.name] = "Harvester Gyrostabilizer",
            [itemKeys.npcDrops_add] = {36,114},
        },
        [255154] = {
            [itemKeys.name] = "Ruined Gyrostabilizer",
            [itemKeys.npcDrops_add] = {480},
        },
        [255155] = {
            [itemKeys.name] = "Precessive Autocognition Assembly",
            [itemKeys.npcDrops_add] = {114},
        },
        [255658] = {
            [itemKeys.name] = "Al'Aketh Windstone Charm",
            [itemKeys.npcDrops_add] = {252664,252665,252762,252763,252765,253195,253511,270201},
        },
        [255663] = {
            [itemKeys.name] = "Windstone",
            [itemKeys.npcDrops_add] = {251662,251676,251918,251966,252068,252664,252665,252762,252763,252764,252765,252767,252802,252820,253195,253511,253622,254596,254626,255534,256935,256966,257521,257532,270201,276415},
            [itemKeys.objectDrops_add] = {616907,626718},
        },
        [257107] = {
            [itemKeys.name] = "Shriekling Matriarch's Head",
            [itemKeys.npcDrops_add] = {253283},
        },
        [257128] = {
            [itemKeys.name] = "Zephyrseed",
            [itemKeys.objectDrops_add] = {613238},
        },
        [257224] = {
            [itemKeys.name] = "Cracked Windstone",
            [itemKeys.npcDrops_add] = {251662,251676},
        },
        [257226] = {
            [itemKeys.name] = "Lesser Essence of the Four Winds",
            [itemKeys.npcDrops_add] = {251662,251676},
        },
        [257941] = {
            [itemKeys.name] = "Windsong Crawler Meat",
            [itemKeys.npcDrops_add] = {254588},
        },
        [257942] = {
            [itemKeys.name] = "Vulgara's Head",
            [itemKeys.npcDrops_add] = {254589},
        },
        [257945] = {
            [itemKeys.name] = "Pilfered Windstone",
            [itemKeys.npcDrops_add] = {251918,255534},
        },
        [258771] = {
            [itemKeys.name] = "Al'Alketh Cultist's Ear",
            [itemKeys.npcDrops_add] = {252664,252665,252762,252763,252764,252765,252767,253195,253511,253622,256966,270201},
        },
        [258772] = {
            [itemKeys.name] = "Windstone Cluster",
            [itemKeys.objectDrops_add] = {613286},
        },
        [260880] = {
            [itemKeys.name] = "Air Construct Core",
            [itemKeys.objectDrops_add] = {616467},
        },
        [260881] = {
            [itemKeys.name] = "Crystallized Lightning",
            [itemKeys.objectDrops_add] = {616468},
        },
        [260883] = {
            [itemKeys.name] = "Enchanted Gyrozephyr",
            [itemKeys.objectDrops_add] = {616466},
        },
        [260927] = {
            [itemKeys.name] = "Rusted Construct Parts",
            [itemKeys.objectDrops_add] = {616466,616467,616468},
        },
        [262357] = {
            [itemKeys.name] = "Wind Hollow Essence",
            [itemKeys.npcDrops_add] = {251676},
        },
        [262668] = {
            [itemKeys.name] = "Wind-Infused Bough",
            [itemKeys.objectDrops_add] = {616860},
        },
        [263006] = {
            [itemKeys.name] = "Scout Ranger's Tunic",
            [itemKeys.npcDrops_add] = {256028},
        },
        [263415] = {
            [itemKeys.name] = "Raani's Lucky Feather",
            [itemKeys.objectDrops_add] = {617675},
        },
        [263418] = {
            [itemKeys.name] = "Shadowsong Family Signet",
            [itemKeys.objectDrops_add] = {617674},
        },
        [263493] = {
            [itemKeys.name] = "Hippogryph Down",
            [itemKeys.objectDrops_add] = {617839},
        },
        [263935] = {
            [itemKeys.name] = "Elunar Longstaff",
            [itemKeys.npcDrops_add] = {250936},
        },
        [263993] = {
            [itemKeys.name] = "Skybreaker Bulwark",
            [itemKeys.npcDrops_add] = {257196},
        },
        [264356] = {
            [itemKeys.name] = "Iceclaw Bear Pendant",
            [itemKeys.npcDrops_add] = {706},
        },
        [264693] = {
            [itemKeys.name] = "Scarlet Crusade Attack Plans",
            [itemKeys.npcDrops_add] = {1537},
        },
        [265105] = {
            [itemKeys.name] = "Lady's Tear Moss",
            [itemKeys.objectDrops_add] = {619450},
        },
        [265140] = {
            [itemKeys.name] = "Pristine Shriekling Feather",
            [itemKeys.npcDrops_add] = {256092},
        },
        [265141] = {
            [itemKeys.name] = "Bloody Heirloom",
            [itemKeys.npcDrops_add] = {252664,252665},
        },
        [265475] = {
            [itemKeys.name] = "Commander Haalien's Severed Head",
            [itemKeys.npcDrops_add] = {253622},
        },
        [265476] = {
            [itemKeys.name] = "Ripped Missive",
            [itemKeys.npcDrops_add] = {253622},
        },
        [266433] = {
            [itemKeys.name] = "Abandoned Belongings",
            [itemKeys.objectDrops_add] = {623295},
        },
        [267413] = {
            [itemKeys.name] = "Gnomeregan Archival Data",
            [itemKeys.objectDrops_add] = {629596},
        },
        [267414] = {
            [itemKeys.name] = "Pristine Leopard Pelt",
            [itemKeys.npcDrops_add] = {260157},
        },
        [267415] = {
            [itemKeys.name] = "Stolen Blasting Powder",
            [itemKeys.npcDrops_add] = {1116},
        },
        [267474] = {
            [itemKeys.name] = "Galeswept Forestshroom",
            [itemKeys.npcDrops_add] = {251918,251966,252068,252664,252665,252762,252763,252764,252765,252767,252802,252820,253195,253511,253622,254596,254626,255534,256966,270201},
            [itemKeys.objectDrops_add] = {626752},
        },
        [268415] = {
            [itemKeys.name] = "Commonplace Herb Seeds",
            [itemKeys.objectDrops_add] = {1617,1618,1619},
        },
        [268518] = {
            [itemKeys.name] = "Head of the Baron",
            [itemKeys.npcDrops_add] = {250660},
        },
        [268535] = {
            [itemKeys.name] = "Bloodied Insignia",
            [itemKeys.npcDrops_add] = {250623,250626,250689},
        },
        [268540] = {
            [itemKeys.name] = "Bloodied Insignia",
            [itemKeys.npcDrops_add] = {250618,250622,250623,250624,250626,250656,255109,255964},
        },
        [268548] = {
            [itemKeys.name] = "Empty Powder Keg",
            [itemKeys.npcDrops_add] = {1116},
        },
        [268579] = {
            [itemKeys.name] = "Crest of Lordaeron",
            [itemKeys.objectDrops_add] = {614679},
        },
        [268580] = {
            [itemKeys.name] = "Intact Limbs",
            [itemKeys.npcDrops_add] = {250622,250623,250624,250626,250627,250656,250689,255109,255964},
        },
        [268801] = {
            [itemKeys.name] = "Bottle of Whispering Elixir",
            [itemKeys.objectDrops_add] = {630871,630885},
        },
        [268812] = {
            [itemKeys.name] = "Whispering Horror Residue",
            [itemKeys.npcDrops_add] = {260396},
        },
        [269715] = {
            [itemKeys.name] = "Savannah Lion Hide",
            [itemKeys.npcDrops_add] = {3241},
        },
        [269719] = {
            [itemKeys.name] = "Trapped Game",
            [itemKeys.objectDrops_add] = {640104},
        },
        [269739] = {
            [itemKeys.name] = "Bloody Tuft of Fur",
            [itemKeys.objectDrops_add] = {640104},
        },
        [270001] = {
            [itemKeys.name] = "Rusty Cutlass",
        },
        [270002] = {
            [itemKeys.name] = "Midshipman's Worn Boots",
        },
        [270151] = {
            [itemKeys.name] = "Benedict's Orders",
            [itemKeys.npcDrops_add] = {262119},
        },
        [270227] = {
            [itemKeys.name] = "Ephemeral Choker",
            [itemKeys.npcDrops_add] = {261306},
        },
        [270229] = {
            [itemKeys.name] = "Treads of the Protector Golem",
            [itemKeys.npcDrops_add] = {261311},
        },
        [270230] = {
            [itemKeys.name] = "Kindlegem Girdle",
            [itemKeys.npcDrops_add] = {261316},
        },
        [270231] = {
            [itemKeys.name] = "Flamefist Grips",
            [itemKeys.npcDrops_add] = {261316},
        },
        [270256] = {
            [itemKeys.name] = "Durgen's Crescent Axe",
            [itemKeys.npcDrops_add] = {261319},
        },
        [270260] = {
            [itemKeys.name] = "Direhammer Leggings",
            [itemKeys.npcDrops_add] = {261319},
        },
        [270261] = {
            [itemKeys.name] = "Robes of the Disgraced Thane",
            [itemKeys.npcDrops_add] = {261319},
        },
        [270302] = {
            [itemKeys.name] = "Chakuyak's Pelt",
            [itemKeys.npcDrops_add] = {268558},
        },
        [270435] = {
            [itemKeys.name] = "Rudolph Gelhardt's Head",
            [itemKeys.npcDrops_add] = {259431},
        },
        [271096] = {
            [itemKeys.name] = "Aetherwisp Bracers",
            [itemKeys.npcDrops_add] = {261306},
        },
        [271097] = {
            [itemKeys.name] = "Spiritwraith Drape",
            [itemKeys.npcDrops_add] = {261306},
        },
        [271098] = {
            [itemKeys.name] = "Golemguard Chest",
            [itemKeys.npcDrops_add] = {261311},
        },
        [271202] = {
            [itemKeys.name] = "Witherbite Bracers",
            [itemKeys.npcDrops_add] = {250483},
        },
        [271203] = {
            [itemKeys.name] = "Segmented Spider Leg",
            [itemKeys.npcDrops_add] = {250483},
        },
        [271204] = {
            [itemKeys.name] = "Meathook Slicer",
            [itemKeys.npcDrops_add] = {250660},
        },
        [271206] = {
            [itemKeys.name] = "Leftover Abomination Skin",
            [itemKeys.npcDrops_add] = {250660},
        },
        [271207] = {
            [itemKeys.name] = "Rotmender's Leggings",
            [itemKeys.npcDrops_add] = {250631},
        },
        [271208] = {
            [itemKeys.name] = "Grip of Fear",
            [itemKeys.npcDrops_add] = {250631},
        },
        [271209] = {
            [itemKeys.name] = "Bonerust Leggings",
            [itemKeys.npcDrops_add] = {256097},
        },
        [271210] = {
            [itemKeys.name] = "Tuskwrap Belt",
            [itemKeys.npcDrops_add] = {256097},
        },
        [271211] = {
            [itemKeys.name] = "Vilewalkers",
            [itemKeys.npcDrops_add] = {256035},
        },
        [271212] = {
            [itemKeys.name] = "Bloodied Chestwraps",
            [itemKeys.npcDrops_add] = {256035},
        },
        [271214] = {
            [itemKeys.name] = "Rotmender's Treads",
            [itemKeys.npcDrops_add] = {250657},
        },
        [271215] = {
            [itemKeys.name] = "Coldspire Staff",
            [itemKeys.npcDrops_add] = {250657},
        },
        [271216] = {
            [itemKeys.name] = "Scepter of the Abandoned",
            [itemKeys.npcDrops_add] = {250631},
        },
        [271217] = {
            [itemKeys.name] = "Corpse Chopper",
            [itemKeys.npcDrops_add] = {256097},
        },
        [271218] = {
            [itemKeys.name] = "Vileblood Scimitar",
            [itemKeys.npcDrops_add] = {256035},
        },
        [271872] = {
            [itemKeys.name] = "Broken Staff of Incinerator Gar'im",
            [itemKeys.npcDrops_add] = {214519},
        },
        [272998] = {
            [itemKeys.name] = "Bone Knuckles",
            [itemKeys.npcDrops_add] = {11517},
        },
        [272999] = {
            [itemKeys.name] = "Barbaric Crossbow",
            [itemKeys.npcDrops_add] = {11517},
        },
        [273003] = {
            [itemKeys.name] = "Searing Dagger",
            [itemKeys.npcDrops_add] = {11519},
        },
        [273005] = {
            [itemKeys.name] = "Satyrskin Cloak",
            [itemKeys.npcDrops_add] = {11519},
        },
        [273007] = {
            [itemKeys.npcDrops_add] = {11519},
        },
        [273084] = {
            [itemKeys.name] = "Cloak of Hermitic Bliss",
            [itemKeys.npcDrops_add] = {3653},
        },
        [273086] = {
            [itemKeys.name] = "Blueprint: Anvil",
            [itemKeys.npcDrops_add] = {1763},
        },
        [273087] = {
            [itemKeys.name] = "Blueprint: Journeyman Campfire",
            [itemKeys.npcDrops_add] = {3673},
        },
        [273089] = {
            [itemKeys.name] = "Slither Cord",
            [itemKeys.npcDrops_add] = {3670},
        },
        [273098] = {
            [itemKeys.name] = "Blueprint: Field Guide",
            [itemKeys.npcDrops_add] = {3671},
        },
        [273137] = {
            [itemKeys.name] = "Skum's Bucket",
            [itemKeys.npcDrops_add] = {3674},
        },
        [273293] = {
            [itemKeys.name] = "Bandsaw Wristbands",
            [itemKeys.npcDrops_add] = {643},
        },
        [273298] = {
            [itemKeys.name] = "Lookie's Spyglass",
            [itemKeys.npcDrops_add] = {645},
        },
        [273456] = {
            [itemKeys.name] = "Cell Keeper's Claws",
            [itemKeys.npcDrops_add] = {3914},
        },
        [273645] = {
            [itemKeys.name] = "Blindwatcher's Sight",
            [itemKeys.npcDrops_add] = {4279},
        },
        [273806] = {
            [itemKeys.name] = "Dark Horde Band",
            [itemKeys.npcDrops_add] = {1696},
        },
        [273807] = {
            [itemKeys.name] = "Demolition Girdle",
            [itemKeys.npcDrops_add] = {1666},
        },
        [273810] = {
            [itemKeys.name] = "Ogre Grips",
            [itemKeys.npcDrops_add] = {1717},
        },
        [273815] = {
            [itemKeys.name] = "Airy Windseeker's Shirt",
            [itemKeys.npcDrops_add] = {252664,252763,252765},
        },
        [273825] = {
            [itemKeys.name] = "Red Wool Cloak",
            [itemKeys.npcDrops_add] = {1716},
        },
        [274268] = {
            [itemKeys.name] = "Dark Iron Map",
            [itemKeys.npcDrops_add] = {6123},
        },
        [274286] = {
            [itemKeys.name] = "Durgen Dirgehammer's Head",
            [itemKeys.npcDrops_add] = {261319},
        },
        [274289] = {
            [itemKeys.name] = "Dwarven Heirloom",
            [itemKeys.objectDrops_add] = {457387,652227,652228},
        },
        [274947] = {
            [itemKeys.name] = "Scroll of Imbue Lesser Flame",
        },
        [275443] = {
            [itemKeys.name] = "Highly Toxic Strain",
            [itemKeys.npcDrops_add] = {250483},
        },
        [275713] = {
            [itemKeys.name] = "Raider's Bow",
            [itemKeys.objectDrops_add] = {656180},
        },
        [275716] = {
            [itemKeys.name] = "Raider's Battleaxe",
            [itemKeys.objectDrops_add] = {656181},
        },
        [275717] = {
            [itemKeys.name] = "Raider's Shield",
            [itemKeys.objectDrops_add] = {656182},
        },
        [275718] = {
            [itemKeys.name] = "Prickly Pear Fruit",
            [itemKeys.objectDrops_add] = {656177},
        },
        [275720] = {
            [itemKeys.name] = "Rough Lizard Hide",
            [itemKeys.npcDrops_add] = {3131},
        },
        [275722] = {
            [itemKeys.name] = "Ukor's Lost Pack",
            [itemKeys.npcDrops_add] = {266851},
        },
        [275723] = {
            [itemKeys.name] = "Halikor's Hoof",
            [itemKeys.npcDrops_add] = {266852},
        },
        [275724] = {
            [itemKeys.name] = "Hexed Pendant",
            [itemKeys.npcDrops_add] = {3206,3207},
        },
        [275851] = {
            [itemKeys.name] = "Necrotic Crystal Fragment",
            [itemKeys.npcDrops_add] = {267006,275437},
            [itemKeys.objectDrops_add] = {656366},
        },
        [275893] = {
            [itemKeys.name] = "Searing Gourd",
            [itemKeys.npcDrops_add] = {263396,263397,263438},
        },
        [275895] = {
            [itemKeys.name] = "Fading Echo",
            [itemKeys.npcDrops_add] = {250620,263389,263390},
        },
        [276070] = {
            [itemKeys.name] = "Chol'aruk's Head",
            [itemKeys.npcDrops_add] = {267307},
        },
        [276561] = {
            [itemKeys.name] = "Black Tome",
            [itemKeys.objectDrops_add] = {659376},
        },
        [276694] = {
            [itemKeys.name] = "Captain Sander's Lucky Shooter",
        },
        [277128] = {
            [itemKeys.name] = "Bloodtalon Martriarch Eggs",
            [itemKeys.npcDrops_add] = {268530},
        },
        [277135] = {
            [itemKeys.name] = "Forgotten Loa Idol",
            [itemKeys.objectDrops_add] = {660647},
        },
        [277190] = {
            [itemKeys.name] = "Fang of Githyiss",
            [itemKeys.npcDrops_add] = {1994},
        },
        [277194] = {
            [itemKeys.name] = "Trollbane Conquests",
            [itemKeys.objectDrops_add] = {660730},
        },
        [277195] = {
            [itemKeys.name] = "The Forsaken Ally",
            [itemKeys.objectDrops_add] = {660729},
        },
        [277196] = {
            [itemKeys.name] = "Field Accounts of Horde Razings",
            [itemKeys.objectDrops_add] = {660731},
        },
        [277197] = {
            [itemKeys.name] = "Cycles of Morality",
            [itemKeys.objectDrops_add] = {660732},
        },
        [277267] = {
            [itemKeys.name] = "Faladiel's Heart",
            [itemKeys.npcDrops_add] = {268602},
        },
        [277269] = {
            [itemKeys.name] = "Kuramaa's Mask",
            [itemKeys.npcDrops_add] = {268605},
        },
        [277278] = {
            [itemKeys.name] = "Handful of Cattails",
            [itemKeys.objectDrops_add] = {661093},
        },
        [277279] = {
            [itemKeys.name] = "Speargrass Cuttings",
            [itemKeys.objectDrops_add] = {661092},
        },
        [277331] = {
            [itemKeys.name] = "Handful of Complicated Parts",
            [itemKeys.objectDrops_add] = {660930},
        },
        [277653] = {
            [itemKeys.name] = "Abandoned Training Weapon",
            [itemKeys.objectDrops_add] = {673476},
        },
        [277661] = {
            [itemKeys.name] = "Dull Storm Orb",
            [itemKeys.npcDrops_add] = {3118},
        },
        [277665] = {
            [itemKeys.name] = "Charged Thunder Lizard Organ",
            [itemKeys.npcDrops_add] = {3130,3131},
        },
        [277936] = {
            [itemKeys.name] = "Glittering Sunstone",
            [itemKeys.npcDrops_add] = {4025},
        },
        [277952] = {
            [itemKeys.name] = "Smooth Boulder",
            [itemKeys.objectDrops_add] = {661446,661448,661449},
        },
        [277976] = {
            [itemKeys.name] = "Gozwin's Mechanic's Log",
            [itemKeys.objectDrops_add] = {664122},
        },
        [278242] = {
            [itemKeys.name] = "Duskbat Wing Membrane",
            [itemKeys.npcDrops_add] = {1553,1554},
        },
        [278243] = {
            [itemKeys.name] = "Darkhound Hide",
            [itemKeys.npcDrops_add] = {1547,1548},
        },
        [278244] = {
            [itemKeys.name] = "Vile Fin Murloc Skin",
            [itemKeys.npcDrops_add] = {1544,1545},
        },
        [279082] = {
            [itemKeys.name] = "Gnarlpine Totem",
            [itemKeys.objectDrops_add] = {668482,668493},
        },
        [279275] = {
            [itemKeys.name] = "Clouded Water Globe",
            [itemKeys.npcDrops_add] = {270294},
        },
        [279276] = {
            [itemKeys.name] = "Mathystral Amulet Fragment",
            [itemKeys.npcDrops_add] = {2181,2182,2183},
        },
        [279279] = {
            [itemKeys.name] = "Peerless Eye",
            [itemKeys.npcDrops_add] = {2338,2339},
        },
        [279537] = {
            [itemKeys.name] = "Rotheap Innards",
            [itemKeys.npcDrops_add] = {270589},
        },
        [279591] = {
            [itemKeys.name] = "Marek's Croc-Hunting Knife",
            [itemKeys.npcDrops_add] = {270693},
        },
        [279821] = {
            [itemKeys.name] = "Khaz Modan Timber",
            [itemKeys.objectDrops_add] = {670771,670773},
        },
        [279822] = {
            [itemKeys.name] = "Khaz Modan Iron",
            [itemKeys.objectDrops_add] = {670774},
        },
        [279991] = {
            [itemKeys.name] = "Dry Branch",
            [itemKeys.objectDrops_add] = {671154},
        },
        [280087] = {
            [itemKeys.name] = "Soft Nightsaber Pelt",
            [itemKeys.npcDrops_add] = {2042},
        },
        [280413] = {
            [itemKeys.name] = "Flintfire's Shipment",
            [itemKeys.objectDrops_add] = {672508},
        },
        [280426] = {
            [itemKeys.name] = "Sack of Fish",
            [itemKeys.npcDrops_add] = {271587},
        },
        [280438] = {
            [itemKeys.npcDrops_add] = {250660},
        },
        [280831] = {
            [itemKeys.name] = "Hatescreech's Amulet",
            [itemKeys.npcDrops_add] = {272034},
        },
        [280832] = {
            [itemKeys.name] = "Windmistress Gaedress' Amulet",
            [itemKeys.npcDrops_add] = {272044},
        },
        [280834] = {
            [itemKeys.name] = "Witchmother Arysa's Amulet",
            [itemKeys.npcDrops_add] = {272046},
        },
        [280839] = {
            [itemKeys.name] = "Stolen Supplies",
            [itemKeys.objectDrops_add] = {673384,673385},
        },
        [280841] = {
            [itemKeys.name] = "Stolen Weapon",
            [itemKeys.objectDrops_add] = {673390,673399},
        },
        [280911] = {
            [itemKeys.name] = "Spiked Collar",
            [itemKeys.npcDrops_add] = {712},
        },
        [281023] = {
            [itemKeys.name] = "Mature Fel Moss",
            [itemKeys.npcDrops_add] = {272116},
        },
        [281031] = {
            [itemKeys.name] = "Mulgore Expansion Plans",
            [itemKeys.npcDrops_add] = {3051},
        },
        [281035] = {
            [itemKeys.name] = "Shredder Operation Instructions",
            [itemKeys.objectDrops_add] = {673494},
        },
        [281036] = {
            [itemKeys.name] = "Barrens Operations Best Practices",
            [itemKeys.objectDrops_add] = {673496},
        },
        [281037] = {
            [itemKeys.name] = "One \"Gerenzo\", of Stonetalon",
            [itemKeys.objectDrops_add] = {673497},
        },
        [281038] = {
            [itemKeys.name] = "Feather of Jai'vhanel",
            [itemKeys.npcDrops_add] = {270196},
        },
        [281046] = {
            [itemKeys.name] = "Raven Hill Tome",
            [itemKeys.objectDrops_add] = {673515},
        },
        [281048] = {
            [itemKeys.name] = "Clearcutter Key",
            [itemKeys.npcDrops_add] = {272173},
        },
        [281350] = {
            [itemKeys.objectDrops_add] = {701788},
        },
        [283460] = {
            [itemKeys.name] = "Decaying Flesh Belt",
            [itemKeys.npcDrops_add] = {271080},
        },
        [284715] = {
            [itemKeys.name] = "First Mate Band",
            [itemKeys.npcDrops_add] = {646},
        },
        [285274] = {
            [itemKeys.name] = "Thendal Watcher's Belt",
            [itemKeys.npcDrops_add] = {256492},
        },
        [285292] = {
            [itemKeys.name] = "Dull Sawblade",
            [itemKeys.npcDrops_add] = {642},
        },
        [286008] = {
            [itemKeys.name] = "Naga Spinefin",
            [itemKeys.npcDrops_add] = {275662,275663},
        },
        [286009] = {
            [itemKeys.name] = "Aggor's Belt",
            [itemKeys.npcDrops_add] = {275666},
        },
        [286010] = {
            [itemKeys.name] = "Broken Bone Trident",
            [itemKeys.objectDrops_add] = {693669},
        },
        [286011] = {
            [itemKeys.name] = "Banner Scrap",
            [itemKeys.objectDrops_add] = {693670},
        },
        [286012] = {
            [itemKeys.name] = "Orcish Dagger",
            [itemKeys.objectDrops_add] = {693674},
        },
        [286017] = {
            [itemKeys.name] = "Dewy Lasher Frond",
            [itemKeys.npcDrops_add] = {275703,275708},
        },
        [286075] = {
            [itemKeys.name] = "Herak's Head",
            [itemKeys.npcDrops_add] = {275767},
        },
        [286204] = {
            [itemKeys.name] = "Tomb Weed",
            [itemKeys.objectDrops_add] = {694732},
        },
        [286205] = {
            [itemKeys.name] = "Half-Eaten Fish",
            [itemKeys.objectDrops_add] = {694772},
        },
        [286209] = {
            [itemKeys.name] = "Shiny Junk",
            [itemKeys.objectDrops_add] = {694785},
        },
        [286214] = {
            [itemKeys.name] = "Duskweed Petal",
            [itemKeys.objectDrops_add] = {694855},
        },
        [286215] = {
            [itemKeys.name] = "Vial of Animal Blood",
            [itemKeys.npcDrops_add] = {113,822},
        },
        [286259] = {
            [itemKeys.name] = "Faintly Glowing Bone",
            [itemKeys.npcDrops_add] = {260428,260430},
        },
        [286269] = {
            [itemKeys.name] = "Glowing Crystal Fragment",
            [itemKeys.objectDrops_add] = {694895},
        },
        [286325] = {
            [itemKeys.name] = "Avala's Core",
            [itemKeys.npcDrops_add] = {276009},
        },
        [286326] = {
            [itemKeys.name] = "Riptear's Heart",
            [itemKeys.npcDrops_add] = {276020},
        },
        [286339] = {
            [itemKeys.name] = "Mostly Dry Firewood",
            [itemKeys.objectDrops_add] = {694934},
        },
        [286358] = {
            [itemKeys.name] = "Coalbeard's Rifle",
            [itemKeys.objectDrops_add] = {695222},
        },
        [286359] = {
            [itemKeys.name] = "Sunhammer's Rifle",
            [itemKeys.objectDrops_add] = {695223},
        },
        [286360] = {
            [itemKeys.name] = "Stoneanvil's Rifle",
            [itemKeys.objectDrops_add] = {695277},
        },
        [286746] = {
            [itemKeys.name] = "Shal'ma's Shawl",
            [itemKeys.npcDrops_add] = {276198},
        },
        [286748] = {
            [itemKeys.name] = "Bristlebark Bow",
            [itemKeys.npcDrops_add] = {276189},
        },
        [286752] = {
            [itemKeys.name] = "Igleggings",
            [itemKeys.npcDrops_add] = {276108},
        },
        [286753] = {
            [itemKeys.name] = "Snarlsnout Shooter",
            [itemKeys.npcDrops_add] = {276109},
        },
    }
end