---@class ForeverItemTraces
local ForeverItemTraces = QuestieLoader:CreateModule("ForeverItemTraces")

---@type QuestieDB
local QuestieDB = QuestieLoader:ImportModule("QuestieDB")

-- Generated by QuestieTrace extract (tools/corrections-extractor)
-- Source trace files: 7277
-- Sessions aggregated: 20659
-- Generated at: 2026-10-09T07:31:37.826Z
function ForeverItemTraces:Load()
    local itemKeys = QuestieDB.itemKeys

    return {
        [190180] = {
            [itemKeys.name] = "Isaac's Heart",
            [itemKeys.npcDrops_add] = {185334},
        },
        [190232] = {
            [itemKeys.name] = "Withered Scarf",
            [itemKeys.npcDrops_add] = {3784},
        },
        [203754] = {
            [itemKeys.name] = "Archmage Antonidas: The Unabridged Autobiography",
            [itemKeys.objectDrops_add] = {386691},
        },
        [203755] = {
            [itemKeys.name] = "Archmage Theocritus' Research Journal",
            [itemKeys.objectDrops_add] = {386759},
        },
        [208185] = {
            [itemKeys.name] = "The Apothecary's Metaphysical Primer",
            [itemKeys.objectDrops_add] = {405879},
        },
        [208800] = {
            [itemKeys.name] = "Baxtan: On Destructive Magics",
            [itemKeys.objectDrops_add] = {407566},
        },
        [208860] = {
            [itemKeys.name] = "Rumi of Gnomeregan: The Collected Works",
            [itemKeys.objectDrops_add] = {408014},
        },
        [209843] = {
            [itemKeys.name] = "Nar'thalas Almanac, Vol. 74",
            [itemKeys.objectDrops_add] = {409496},
        },
        [209844] = {
            [itemKeys.name] = "The Dalaran Digest, Vol. 23",
            [itemKeys.objectDrops_add] = {409501},
        },
        [209845] = {
            [itemKeys.name] = "Bewitchments and Glamours",
            [itemKeys.objectDrops_add] = {409562},
        },
        [209846] = {
            [itemKeys.name] = "Secrets of the Dreamers",
            [itemKeys.objectDrops_add] = {409692},
        },
        [209847] = {
            [itemKeys.name] = "Arcanic Systems Manual",
            [itemKeys.objectDrops_add] = {409700},
        },
        [209848] = {
            [itemKeys.name] = "Goaz Scrolls",
            [itemKeys.objectDrops_add] = {409717},
        },
        [209849] = {
            [itemKeys.name] = "Crimes Against Anatomy",
            [itemKeys.objectDrops_add] = {409735},
        },
        [209850] = {
            [itemKeys.name] = "Runes of the Sorcerer-Kings",
            [itemKeys.objectDrops_add] = {409731},
        },
        [209851] = {
            [itemKeys.name] = "Fury of the Land",
            [itemKeys.objectDrops_add] = {409711},
        },
        [210183] = {
            [itemKeys.name] = "Horn of Xelthos",
            [itemKeys.objectDrops_add] = {410528},
        },
        [210187] = {
            [itemKeys.name] = "Venture Co. Work Order",
            [itemKeys.npcDrops_add] = {3989},
        },
        [210188] = {
            [itemKeys.name] = "Shredded Work Order",
            [itemKeys.npcDrops_add] = {3989},
        },
        [210212] = {
            [itemKeys.name] = "Brother's Half-Key",
            [itemKeys.npcDrops_add] = {211764},
        },
        [210213] = {
            [itemKeys.name] = "Sister's Half-Key",
            [itemKeys.npcDrops_add] = {211765},
        },
        [211269] = {
            [itemKeys.name] = "Primitive Drawing",
            [itemKeys.npcDrops_add] = {2893,2894},
        },
        [211780] = {
            [itemKeys.name] = "Scroll: KWYJIBO",
            [itemKeys.npcDrops_add] = {36,40,43,95,97,114,116,117,118,123,157,423,442,448,454,456,471,474,476,478,480,504,589,590,712,732,735,822,1109,1115,1116,1120,1121,1122,1123,1127,1131,1135,1161,1162,1163,1164,1166,1172,1186,1190,1195,1196,1202,1211,1236,1426,1522,1523,1526,1529,1532,1534,1535,1536,1537,1538,1543,1544,1545,1548,1553,1554,1555,1656,1693,1766,1767,1769,1779,1782,1797,1867,1869,1922,1941,2010,2018,2019,2025,2029,2030,2038,2065,2070,2152,2164,2190,2202,2232,2234,2324,2962,2964,2965,2978,2990,3035,3099,3104,3107,3110,3116,3118,3119,3122,3127,3129,3131,3197,3198,3206,3241,3242,3244,3246,3254,3255,3265,3267,3268,3272,3273,3274,3276,3284,3285,3382,3383,3397,3415,3425,3461,5837,6123,6866,7235,11318,248474,250282,250622,251245,251284,251291,251622,251661,251662,251676,251707,251918,252068,252664,252762,252763,252764,252765,252820,253282,254588,254596,254626,256092,257532,259434,263396,263397,263438,267006,270201,271486,271530,272096,275437,275703,275708},
            [itemKeys.objectDrops_add] = {106318,106319,626752},
        },
        [211784] = {
            [itemKeys.name] = "Scroll: WUBBA WUBBA",
            [itemKeys.npcDrops_add] = {122,171,202,205,212,423,424,426,428,435,440,441,458,485,505,517,547,548,565,578,580,604,615,623,624,628,703,787,898,909,948,1007,1011,1018,1023,1024,1028,1032,1165,1270,1400,1417,1707,1715,1725,1888,1913,1924,1954,1958,1974,2089,2165,2170,2180,2235,2260,2261,2267,2336,2339,2351,2384,2427,2451,3235,3239,3240,3245,3256,3258,3261,3263,3278,3283,3286,3374,3385,3386,3454,3456,3461,3467,3631,3640,3763,3816,3840,3851,3861,3862,3863,3917,3921,3922,3925,3928,3947,3988,4005,4007,4024,4026,4036,4057,4097,4100,4127,4416,4463,4812,4825,4969,5048,5053,5761,5762,9523,9524,11913,11915,12856,250618,250622,250623,250624,250627,250735,267314},
            [itemKeys.objectDrops_add] = {2849,2850,3715},
        },
        [211785] = {
            [itemKeys.name] = "Scroll: CWAL",
            [itemKeys.npcDrops_add] = {36,40,46,95,97,114,117,118,123,126,157,285,327,423,442,454,456,474,476,478,480,500,504,515,524,590,732,735,822,834,1116,1121,1122,1127,1135,1161,1162,1166,1172,1173,1174,1186,1196,1201,1202,1211,1236,1397,1426,1520,1522,1526,1535,1537,1544,1548,1553,1657,1674,1675,1693,1766,1779,1781,1782,1797,1866,1891,1912,1914,2004,2008,2009,2010,2012,2069,2070,2177,2185,2190,2324,2959,2960,2963,2964,3099,3104,3111,3112,3113,3119,3120,3121,3122,3126,3127,3129,3130,3131,3197,3207,3241,3242,3244,3246,3255,3268,3272,3273,3274,3275,3276,3284,3381,3382,3383,3385,3425,3461,4263,6123,6846,6909,6927,7319,11910,11911,12320,250283,250618,250625,250626,251245,251284,251291,251622,251661,251662,251676,251707,251918,252068,252664,252665,252666,252764,252802,252820,253195,253282,253511,254596,256092,260157,260428,260430,263389,263397,267006,270201,271530,271712,275437,275703},
            [itemKeys.objectDrops_add] = {106318,106319,626752},
        },
        [211786] = {
            [itemKeys.name] = "Scroll: CHAP BALK WELLES",
            [itemKeys.npcDrops_add] = {36,40,46,95,97,114,116,117,118,123,126,157,171,285,454,471,474,476,478,500,502,504,590,712,732,735,824,834,1109,1115,1116,1121,1127,1135,1138,1161,1162,1172,1184,1196,1201,1202,1211,1236,1380,1397,1426,1526,1535,1537,1538,1544,1548,1553,1674,1689,1693,1766,1778,1779,1869,1912,1922,1934,1941,1996,2004,2008,2027,2029,2033,2152,2163,2167,2189,2203,2205,2235,2321,2950,2959,2960,2971,2978,3103,3104,3112,3113,3118,3119,3120,3127,3130,3198,3206,3207,3242,3244,3246,3254,3255,3265,3266,3268,3272,3273,3276,3284,3381,3382,3385,3397,3415,3425,4127,6123,6846,6866,6927,7235,11322,250283,250623,250626,251245,251284,251291,251661,251662,251676,251707,251918,251966,252068,252664,252665,252762,252763,252765,252802,252820,253195,254626,255534,256092,256966,260157,260428,260430,263389,263390,263396,263397,263438,263466,263470,267006,269075,270201,271486,271530,271587,272096,275703},
            [itemKeys.objectDrops_add] = {106318,106319,626752},
        },
        [211787] = {
            [itemKeys.name] = "Scroll: LOWER PING WHOMEVER",
            [itemKeys.npcDrops_add] = {36,40,46,95,97,114,116,117,118,126,285,423,454,456,474,478,480,500,504,515,589,590,712,735,822,824,834,1109,1116,1117,1118,1126,1127,1135,1162,1166,1172,1173,1174,1175,1176,1195,1196,1201,1202,1211,1236,1380,1426,1522,1527,1535,1536,1538,1544,1548,1553,1554,1555,1689,1693,1765,1770,1778,1779,1782,1922,1941,2001,2008,2009,2010,2011,2152,2163,2167,2177,2179,2185,2189,2321,2959,2964,2965,2978,2979,3100,3103,3107,3110,3112,3117,3119,3121,3122,3126,3127,3129,3130,3197,3198,3203,3206,3207,3242,3243,3244,3246,3265,3268,3272,3273,3274,3275,3276,3277,3284,3285,3380,3381,3382,3384,3397,3415,3425,3461,3566,6123,6494,6866,6909,11319,11322,11324,11910,11912,250282,250626,251245,251284,251291,251661,251662,251676,251707,251918,252068,252664,252665,252762,252764,252765,252802,252820,253195,253511,254588,254596,254626,255534,256092,257532,260428,260430,263389,263390,263396,263397,263438,263466,263470,267006,269075,270201,272116,275767},
            [itemKeys.objectDrops_add] = {106318,106319,626752},
        },
        [211853] = {
            [itemKeys.name] = "Scroll: VOCE WELL",
            [itemKeys.npcDrops_add] = {48,121,202,205,218,423,426,428,430,432,434,441,442,449,485,505,531,547,548,565,578,580,604,615,622,624,626,657,1007,1010,1011,1022,1024,1034,1083,1110,1167,1224,1708,1732,1763,1915,1940,1943,1974,2102,2170,2182,2183,2235,2248,2261,2336,2350,2351,2368,2384,2428,3238,3240,3241,3245,3249,3260,3261,3277,3278,3282,3283,3374,3377,3386,3434,3436,3457,3458,3461,3636,3638,3712,3717,3750,3765,3767,3771,3817,3840,3859,3863,3925,3989,4008,4065,4093,4127,4418,4463,5048,7603,250484,250623,250627,250630,268624},
            [itemKeys.objectDrops_add] = {2849,2850,3715},
        },
        [211854] = {
            [itemKeys.name] = "Scroll: OMIT KESA",
            [itemKeys.npcDrops_add] = {48,127,202,205,212,345,422,423,426,428,432,434,440,441,442,445,446,449,452,485,505,531,547,569,598,604,615,622,625,626,657,824,948,1007,1010,1011,1018,1020,1022,1023,1024,1032,1040,1051,1111,1164,1197,1205,1417,1706,1708,1715,1731,1732,1940,2180,2181,2182,2208,2237,2248,2261,2269,2360,2384,2529,3250,3256,3257,3258,3260,3261,3263,3275,3277,3278,3282,3374,3377,3394,3457,3459,3461,3463,3467,3631,3636,3637,3641,3667,3713,3748,3789,3820,3840,3853,3857,3877,3917,3921,3922,3924,3947,3999,4006,4007,4013,4021,4022,4042,4067,4114,4124,4147,4416,4805,4807,4810,4825,5048,5756,5763,12677,250622,250624,250735,268624},
            [itemKeys.objectDrops_add] = {2849,2850,3715},
        },
        [211855] = {
            [itemKeys.name] = "Scroll: STHENIC LUNATE",
            [itemKeys.npcDrops_add] = {122,202,213,217,422,428,430,432,433,435,437,440,441,442,446,458,485,517,531,533,539,547,548,578,598,657,1019,1021,1023,1027,1034,1069,1083,1158,1164,1167,1179,1192,1197,1400,1417,1708,1727,1732,1888,1939,1940,1942,1973,2103,2171,2260,2261,2266,2268,2323,2332,2336,2354,2372,2384,3238,3239,3240,3245,3256,3260,3261,3263,3278,3283,3286,3376,3458,3459,3461,3475,3631,3711,3733,3743,3750,3840,3851,3853,3872,3925,3947,3989,3999,4005,4007,4022,4023,4026,4128,4416,4463,4798,4799,4802,4807,4809,4811,5056,5755,5761,8886,9524,11858,11912,11913,12759,250618,250627,267307},
            [itemKeys.objectDrops_add] = {2849,2850},
        },
        [212792] = {
            [itemKeys.name] = "Eye of the Tempest",
            [itemKeys.npcDrops_add] = {216474},
        },
        [213165] = {
            [itemKeys.name] = "Basilisks: Should Petrification be Feared?",
            [itemKeys.objectDrops_add] = {421526},
        },
        [213543] = {
            [itemKeys.name] = "Scroll: UPDOG",
            [itemKeys.npcDrops_add] = {2371,12676},
        },
        [213544] = {
            [itemKeys.name] = "Scroll: TOPAZ YORAK",
            [itemKeys.npcDrops_add] = {2893},
        },
        [213545] = {
            [itemKeys.name] = "Scroll: PEATCHY ATTAX",
            [itemKeys.npcDrops_add] = {2377},
        },
        [213547] = {
            [itemKeys.name] = "Scroll: THAW WORDS",
            [itemKeys.npcDrops_add] = {2248},
        },
        [213562] = {
            [itemKeys.name] = "Bug Catching Net",
        },
        [213563] = {
            [itemKeys.name] = "Field Guide",
        },
        [213564] = {
            [itemKeys.name] = "Scroll of Minor Evocation",
        },
        [215257] = {
            [itemKeys.name] = "Scroll of Comprehension",
        },
        [215369] = {
            [itemKeys.name] = "Pattern: Invoker's Cord",
            [itemKeys.npcDrops_add] = {531},
        },
        [215370] = {
            [itemKeys.name] = "Pattern: Invoker's Mantle",
            [itemKeys.npcDrops_add] = {429},
        },
        [215683] = {
            [itemKeys.name] = "Geomancy: The Stone-Cold Truth",
            [itemKeys.objectDrops_add] = {423895},
        },
        [215815] = {
            [itemKeys.name] = "Defensive Magics 101",
            [itemKeys.objectDrops_add] = {423896},
        },
        [215816] = {
            [itemKeys.name] = "A Web of Lies: Debunking Myths and Legends",
            [itemKeys.objectDrops_add] = {423897},
        },
        [215820] = {
            [itemKeys.name] = "Mummies: A Guide to the Unsavory Undead",
            [itemKeys.objectDrops_add] = {423899},
        },
        [215822] = {
            [itemKeys.name] = "RwlRwlRwlRwl!",
            [itemKeys.objectDrops_add] = {423900},
        },
        [220345] = {
            [itemKeys.name] = "Sanguine Sorcery",
            [itemKeys.objectDrops_add] = {441247},
        },
        [220348] = {
            [itemKeys.name] = "Everyday Etiquette",
            [itemKeys.objectDrops_add] = {441250},
        },
        [220349] = {
            [itemKeys.name] = "Stonewrought Design",
            [itemKeys.objectDrops_add] = {441251},
        },
        [220350] = {
            [itemKeys.name] = "Venomous Journeys",
            [itemKeys.objectDrops_add] = {441252},
        },
        [220352] = {
            [itemKeys.name] = "A Mind of Metal",
            [itemKeys.objectDrops_add] = {441253},
        },
        [220353] = {
            [itemKeys.name] = "Conjurer's Codex",
            [itemKeys.objectDrops_add] = {441254},
        },
        [221324] = {
            [itemKeys.name] = "Brittle Key",
            [itemKeys.objectDrops_add] = {674126},
        },
        [228132] = {
            [itemKeys.name] = "Undead Potatoes",
            [itemKeys.objectDrops_add] = {463213},
        },
        [228133] = {
            [itemKeys.name] = "Magma or Lava?",
            [itemKeys.objectDrops_add] = {463206},
        },
        [228134] = {
            [itemKeys.name] = "Northern Kalimdor - A Comprehensive Guide",
            [itemKeys.objectDrops_add] = {463209},
        },
        [228135] = {
            [itemKeys.name] = "A Study of the Light",
            [itemKeys.objectDrops_add] = {463207},
        },
        [228136] = {
            [itemKeys.name] = "Ka-Boom!",
            [itemKeys.objectDrops_add] = {463214},
        },
        [228141] = {
            [itemKeys.name] = "Necromancy 101",
            [itemKeys.objectDrops_add] = {463211},
        },
        [246213] = {
            [itemKeys.name] = "Sturdy Lumber",
            [itemKeys.objectDrops_add] = {554626},
        },
        [247805] = {
            [itemKeys.name] = "Stolen Enchanting Supplies",
            [itemKeys.objectDrops_add] = {561159},
        },
        [247813] = {
            [itemKeys.name] = "Waterlogged Saw",
            [itemKeys.objectDrops_add] = {562103},
        },
        [247816] = {
            [itemKeys.name] = "Mining Tools",
            [itemKeys.objectDrops_add] = {562114},
        },
        [247817] = {
            [itemKeys.name] = "Waterlogged Axe",
            [itemKeys.objectDrops_add] = {562105},
        },
        [247818] = {
            [itemKeys.name] = "Waterlogged Toolbox",
            [itemKeys.objectDrops_add] = {562106},
        },
        [247826] = {
            [itemKeys.name] = "Croaky's Head",
            [itemKeys.npcDrops_add] = {248278},
        },
        [247834] = {
            [itemKeys.name] = "Nibbled-On Book",
            [itemKeys.npcDrops_add] = {6,257},
        },
        [247839] = {
            [itemKeys.name] = "Stolen Book",
            [itemKeys.npcDrops_add] = {6,80,257},
        },
        [247862] = {
            [itemKeys.name] = "Elmpaw's Head",
            [itemKeys.npcDrops_add] = {248299},
        },
        [247877] = {
            [itemKeys.name] = "Rough Wolf Pelt",
            [itemKeys.npcDrops_add] = {118,1922},
        },
        [247883] = {
            [itemKeys.name] = "Crude Wax Effigy",
            [itemKeys.npcDrops_add] = {476},
        },
        [247884] = {
            [itemKeys.name] = "Luminous Residue",
        },
        [247886] = {
            [itemKeys.name] = "Sack of \"Picture\" Books",
            [itemKeys.npcDrops_add] = {248362},
        },
        [248001] = {
            [itemKeys.name] = "Lost Book",
            [itemKeys.npcDrops_add] = {40,475},
        },
        [248002] = {
            [itemKeys.name] = "Picture Book: Fun with Elementals",
            [itemKeys.npcDrops_add] = {248464},
        },
        [248003] = {
            [itemKeys.name] = "Geomancy for Curious Young Wizards",
            [itemKeys.npcDrops_add] = {248474},
        },
        [248004] = {
            [itemKeys.name] = "Arcane Explainer: Magical Stuff in Simple Words",
            [itemKeys.npcDrops_add] = {471},
        },
        [248682] = {
            [itemKeys.name] = "Waylaid Crate: Apprentice Herbs",
            [itemKeys.npcDrops_add] = {97,114,422,428,433,440,441,454,474,517,539,565,589,712,1031,1426,1768,1781,1870,1888,1909,1940,2069,2165,2179,2181,2235,2237,2261,2336,2350,2384,3240,3241,3244,3256,3258,3260,3261,3273,3277,3278,3282,3283,3284,3286,3374,3461,3474,3713,3715,3739,3809,3819,3928,3988,4007,4127,4416,4627,9523,12856},
        },
        [248683] = {
            [itemKeys.name] = "Waylaid Crate: Apprentice Ore",
            [itemKeys.npcDrops_add] = {115,122,171,423,424,428,442,456,502,547,578,598,1165,1166,1417,1888,1889,1939,1942,1974,2164,2165,2203,2336,2338,2354,3242,3245,3250,3256,3258,3261,3273,3276,3277,3278,3280,3283,3285,3385,3395,3425,3445,3717,3989,4005,4006,4007,4018,4025,4263,6020,267308,267314,271898},
        },
        [248684] = {
            [itemKeys.name] = "Waylaid Crate: Apprentice Textiles",
            [itemKeys.npcDrops_add] = {114,118,124,217,423,428,446,449,453,545,547,569,589,712,824,1007,1008,1165,1184,1191,1417,1888,1914,1923,1943,1955,1974,2053,2069,2205,2261,2338,2351,3240,3241,3245,3246,3255,3256,3257,3258,3260,3263,3273,3277,3278,3282,3284,3382,3385,3394,3424,3457,3717,3928,4007,11917},
        },
        [248685] = {
            [itemKeys.name] = "Waylaid Crate: Apprentice Curiosities",
            [itemKeys.npcDrops_add] = {114,213,422,423,440,441,485,505,517,565,589,1020,1693,1924,2012,2158,2164,2181,3241,3245,3256,3258,3260,3261,3273,3276,3277,3280,3283,3285,3375,3384,3385,3458,3712,3728,3824,4007,4044,4263,4416,11912,12897,209797,267006,267314,268622},
        },
        [248686] = {
            [itemKeys.name] = "Waylaid Crate: Journeyman Herbs",
            [itemKeys.npcDrops_add] = {202,432,615,923,1021,1150,1417,1973,2089,2102,2356,2384,3238,3374,3436,3727,3820,4026,4053,4249},
        },
        [248687] = {
            [itemKeys.name] = "Waylaid Crate: Journeyman Ore",
            [itemKeys.npcDrops_add] = {48,205,218,434,435,531,568,590,1015,1021,1034,1069,1258,1658,2267,2369,2384,3272,3376,3746,3770,3921,3925,4093,4128},
        },
        [248688] = {
            [itemKeys.name] = "Waylaid Crate: Journeyman Textiles",
            [itemKeys.npcDrops_add] = {122,345,431,533,604,628,1019,1022,1035,1038,1417,1666,2268,2271,2349,2384,3376,3377,3378,3392,3833,3925,3932,3999,4020,4147,12856},
        },
        [248689] = {
            [itemKeys.name] = "Waylaid Crate: Journeyman Curiosities",
            [itemKeys.npcDrops_add] = {202,430,441,785,920,1018,1021,1032,1034,1110,2356,2387,3238,3459,3743,3824,3921,4022,4096},
        },
        [248690] = {
            [itemKeys.name] = "Waylaid Crate: Earthly Expert Herbs",
            [itemKeys.npcDrops_add] = {212,2375,2413},
        },
        [248692] = {
            [itemKeys.name] = "Waylaid Crate: Expert Ore",
            [itemKeys.npcDrops_add] = {2248,2359},
        },
        [248693] = {
            [itemKeys.name] = "Waylaid Crate: Expert Textiles",
            [itemKeys.npcDrops_add] = {2369},
        },
        [248702] = {
            [itemKeys.name] = "Waylaid Crate: Apprentice Fabrics",
            [itemKeys.npcDrops_add] = {122,440,450,598,1197,1426,1554,1974,3250,3260,3273,3283,3667,6124,267314},
        },
        [248703] = {
            [itemKeys.name] = "Waylaid Crate: Apprentice Ingots",
            [itemKeys.npcDrops_add] = {3,117,122,213,458,589,590,598,1523,1532,1693,1974,2261,2266,3250,3260,3261,3273,3274,3276,3385,3386,3455,3503,3713,3715,6123,9336},
        },
        [248704] = {
            [itemKeys.name] = "Waylaid Crate: Apprentice Parts",
            [itemKeys.npcDrops_add] = {157,213,217,445,550,590,1197,1889,1912,2181,2203,3245,3263,3385,3715,3944,4005,4007,4463},
        },
        [248705] = {
            [itemKeys.name] = "Waylaid Crate: Journeyman Fabrics",
            [itemKeys.npcDrops_add] = {205,210,431,531,570,3239,3374,3926,4096},
        },
        [248706] = {
            [itemKeys.name] = "Waylaid Crate: Journeyman Ingots",
            [itemKeys.npcDrops_add] = {2384,2408,3917,4067},
        },
        [248707] = {
            [itemKeys.name] = "Waylaid Crate: Journeyman Parts",
            [itemKeys.npcDrops_add] = {615,2183,2375,3459,3924,4097},
        },
        [248708] = {
            [itemKeys.name] = "Waylaid Crate: Expert Fabrics",
            [itemKeys.npcDrops_add] = {2371},
        },
        [248709] = {
            [itemKeys.name] = "Waylaid Crate: Expert Ingots",
            [itemKeys.npcDrops_add] = {2893},
        },
        [249391] = {
            [itemKeys.name] = "Pyrite",
            [itemKeys.objectDrops_add] = {1667,1731,1732,1733,1735,2054,2055,3763,3764,103711,656333},
        },
        [249399] = {
            [itemKeys.name] = "Frilled Lichen",
            [itemKeys.objectDrops_add] = {1619,1620,1621,1622,1623,1624,2045,3726,3727,3729,3730,657383},
        },
        [249424] = {
            [itemKeys.name] = "Rosecap",
            [itemKeys.objectDrops_add] = {2041},
        },
        [249425] = {
            [itemKeys.name] = "Bauxite",
            [itemKeys.objectDrops_add] = {1734},
        },
        [249427] = {
            [itemKeys.name] = "Pristine Leather",
            [itemKeys.npcDrops_add] = {213,441,454,547,565,833,1186,1400,1417,1693,1766,1770,1778,1779,1924,2069,2071,2089,2163,2164,2237,2351,2354,2356,2384,2529,3231,3239,3240,3241,3242,3244,3245,3246,3247,3249,3255,3256,3415,3425,3461,3463,3630,3632,3634,3636,3637,3674,3809,3859,4018,4067,4127,4128,4279,5048,5053,5056,5755,5756,8886,263470,270693},
        },
        [249428] = {
            [itemKeys.name] = "Pristine Hide",
            [itemKeys.npcDrops_add] = {205,533,1018,2248,2408,4248,4249,4538,4825},
        },
        [249865] = {
            [itemKeys.name] = "Peace Tea",
            [itemKeys.npcDrops_add] = {2962},
        },
        [249879] = {
            [itemKeys.name] = "Recipe: Peace Tea",
            [itemKeys.npcDrops_add] = {1397},
        },
        [249880] = {
            [itemKeys.name] = "Recipe: Royal Tea",
            [itemKeys.npcDrops_add] = {4003},
        },
        [250182] = {
            [itemKeys.name] = "Recipe: Bear Brisket",
            [itemKeys.npcDrops_add] = {3809},
        },
        [250187] = {
            [itemKeys.name] = "Recipe: Tasty Raptor Bites",
            [itemKeys.npcDrops_add] = {1020,3255},
        },
        [250188] = {
            [itemKeys.name] = "Recipe: Breakfast Omelette",
            [itemKeys.npcDrops_add] = {428},
        },
        [250366] = {
            [itemKeys.name] = "Recipe: Minor Cleric's Elixir",
            [itemKeys.npcDrops_add] = {46,1545,250283},
        },
        [250375] = {
            [itemKeys.name] = "Recipe: Minor Mageblood Elixir",
            [itemKeys.npcDrops_add] = {1134},
        },
        [250380] = {
            [itemKeys.name] = "Recipe: Elixir of Minor Spirit",
            [itemKeys.npcDrops_add] = {3128},
        },
        [250976] = {
            [itemKeys.name] = "Recipe: Minor Spellblasting Potion",
            [itemKeys.npcDrops_add] = {476,3115},
        },
        [250977] = {
            [itemKeys.name] = "Recipe: Lesser Spellblasting Potion",
            [itemKeys.npcDrops_add] = {2169,3280},
        },
        [250982] = {
            [itemKeys.name] = "Recipe: Minor Frenzy Potion",
            [itemKeys.npcDrops_add] = {2015,2963},
        },
        [250983] = {
            [itemKeys.name] = "Recipe: Lesser Frenzy Potion",
            [itemKeys.npcDrops_add] = {1943},
        },
        [250989] = {
            [itemKeys.name] = "Recipe: Lesser Mender's Potion",
            [itemKeys.npcDrops_add] = {2180,3386},
        },
        [251335] = {
            [itemKeys.name] = "Plans: Sterling Silver Boots",
            [itemKeys.npcDrops_add] = {2261},
        },
        [251336] = {
            [itemKeys.name] = "Plans: Sterling Silver Leggings",
            [itemKeys.npcDrops_add] = {48},
        },
        [251337] = {
            [itemKeys.name] = "Plans: Sterling Silver Gauntlet",
            [itemKeys.npcDrops_add] = {3711},
        },
        [251338] = {
            [itemKeys.name] = "Plans: Sterling Silver Shoulders",
            [itemKeys.npcDrops_add] = {433},
        },
        [251341] = {
            [itemKeys.name] = "Plans: Guard's Chain Shirt",
            [itemKeys.npcDrops_add] = {3864},
        },
        [251360] = {
            [itemKeys.name] = "Plans: Veteran's Gloves",
            [itemKeys.npcDrops_add] = {643,644,3653,3669},
        },
        [251361] = {
            [itemKeys.name] = "Plans: Guard's Gloves",
            [itemKeys.npcDrops_add] = {3653,3864},
        },
        [251362] = {
            [itemKeys.name] = "Plans: Protector's Gloves",
            [itemKeys.npcDrops_add] = {11517},
        },
        [251364] = {
            [itemKeys.name] = "Plans: Crusader's Gloves",
            [itemKeys.npcDrops_add] = {645,3669,11520},
        },
        [251376] = {
            [itemKeys.name] = "Plans: Guard's Silvered Chain Leggings",
            [itemKeys.npcDrops_add] = {4424,12902},
        },
        [251378] = {
            [itemKeys.name] = "Plans: Acolyte's Silvered Chain Leggings",
            [itemKeys.npcDrops_add] = {4829,4830},
        },
        [251379] = {
            [itemKeys.name] = "Plans: Crusader's Silvered Chain Leggings",
            [itemKeys.npcDrops_add] = {4832},
        },
        [251380] = {
            [itemKeys.name] = "Plans: Veteran's Silvered Chain Helm",
            [itemKeys.npcDrops_add] = {1696,3673,4831},
        },
        [251381] = {
            [itemKeys.name] = "Plans: Guard's Silvered Chain Helm",
            [itemKeys.npcDrops_add] = {3887,4274,4831},
        },
        [251382] = {
            [itemKeys.name] = "Plans: Protector's Silvered Chain Helm",
            [itemKeys.npcDrops_add] = {3927,4274},
        },
        [251384] = {
            [itemKeys.name] = "Plans: Crusader's Silvered Chain Helm",
            [itemKeys.npcDrops_add] = {5775},
        },
        [251394] = {
            [itemKeys.name] = "Plans: Shining Mithril Boots",
            [itemKeys.npcDrops_add] = {2894},
        },
        [251459] = {
            [itemKeys.name] = "Plans: Mithril Shortsword",
            [itemKeys.npcDrops_add] = {4362},
        },
        [251461] = {
            [itemKeys.name] = "Plans: Mithril Claws",
            [itemKeys.npcDrops_add] = {2893},
        },
        [251524] = {
            [itemKeys.name] = "Whimsyfin",
            [itemKeys.objectDrops_add] = {35591},
        },
        [251526] = {
            [itemKeys.name] = "Recipe: Savory Whimsyfin Delight",
            [itemKeys.npcDrops_add] = {428,441},
        },
        [251918] = {
            [itemKeys.name] = "Scrawny Ursera Claw",
            [itemKeys.npcDrops_add] = {250926},
        },
        [251924] = {
            [itemKeys.name] = "Signet of Akir",
            [itemKeys.npcDrops_add] = {251160,251448},
        },
        [251925] = {
            [itemKeys.name] = "Tattered Ursera Feather",
            [itemKeys.npcDrops_add] = {250926,250937,251115},
        },
        [251927] = {
            [itemKeys.name] = "Chipped Cirrusfly Stinger",
            [itemKeys.npcDrops_add] = {251169,251402,251404},
        },
        [251928] = {
            [itemKeys.name] = "Torn Insect Wing",
            [itemKeys.npcDrops_add] = {251169,251402,251404},
        },
        [251930] = {
            [itemKeys.name] = "Minor Essence of the Four Winds",
            [itemKeys.npcDrops_add] = {251143},
        },
        [251931] = {
            [itemKeys.name] = "Depleted Windstone",
            [itemKeys.npcDrops_add] = {251143},
        },
        [251932] = {
            [itemKeys.name] = "Sharpened Cirrusfly Stinger",
            [itemKeys.npcDrops_add] = {251402},
        },
        [251961] = {
            [itemKeys.name] = "Arcane Mote",
            [itemKeys.npcDrops_add] = {246020},
        },
        [252022] = {
            [itemKeys.name] = "Galestrider Jerky",
            [itemKeys.npcDrops_add] = {251918,251966,252068,252664,252665,252762,252763,252764,252765,252767,252802,252820,253195,253511,253622,254596,254626,255534,256966,270201},
            [itemKeys.objectDrops_add] = {626718,626752},
        },
        [252023] = {
            [itemKeys.name] = "Zaalanarr Sharp",
            [itemKeys.objectDrops_add] = {626718},
        },
        [252028] = {
            [itemKeys.name] = "Fresh Gustberry Bread",
            [itemKeys.npcDrops_add] = {251918,251966,252068,252664,252665,252762,252763,252764,252765,252767,252802,252820,253195,253511,253622,254596,254626,255534,256966,270201},
            [itemKeys.objectDrops_add] = {626718,626752},
        },
        [252030] = {
            [itemKeys.name] = "Pungent Skycheddar",
            [itemKeys.npcDrops_add] = {251918,251966,252068,252664,252665,252762,252763,252764,252765,252767,252802,252820,253195,253511,253622,254596,254626,255534,256966,259398,270201},
            [itemKeys.objectDrops_add] = {626752},
        },
        [252031] = {
            [itemKeys.name] = "Crisp Spring Water",
            [itemKeys.npcDrops_add] = {251918,251966,252068,252664,252665,252762,252763,252764,252765,252767,252802,252820,253195,253511,253622,254596,254626,255534,256966,257196,259385,270201},
            [itemKeys.objectDrops_add] = {626718,626752},
        },
        [252032] = {
            [itemKeys.name] = "Red Delicious Stormapple",
            [itemKeys.npcDrops_add] = {251918,251966,252068,252664,252665,252762,252763,252764,252765,252767,252802,252820,253195,253511,253622,254596,254626,255534,256966,257196,270201},
            [itemKeys.objectDrops_add] = {626718,626752},
        },
        [252455] = {
            [itemKeys.name] = "Defender's Leather Helm",
            [itemKeys.npcDrops_add] = {1663},
        },
        [252512] = {
            [itemKeys.npcDrops_add] = {4829},
        },
        [252514] = {
            [itemKeys.name] = "Stormrider's Leather Helm",
            [itemKeys.npcDrops_add] = {1716,4428,4829,7361},
        },
        [252515] = {
            [itemKeys.name] = "Wisdom's Leather Helm",
            [itemKeys.npcDrops_add] = {4832},
        },
        [252661] = {
            [itemKeys.name] = "Commander Cyclas's Head",
            [itemKeys.npcDrops_add] = {251966},
        },
        [252665] = {
            [itemKeys.name] = "Head of Urs'anah",
            [itemKeys.npcDrops_add] = {251115},
        },
        [252670] = {
            [itemKeys.name] = "Prideclaw Pelt",
            [itemKeys.npcDrops_add] = {251245},
        },
        [252671] = {
            [itemKeys.name] = "Hoarder's Foot",
            [itemKeys.npcDrops_add] = {251245,256092},
        },
        [252760] = {
            [itemKeys.name] = "Stolen Shen'dar Supplies",
            [itemKeys.npcDrops_add] = {252068},
            [itemKeys.objectDrops_add] = {576179},
        },
        [252777] = {
            [itemKeys.name] = "Pattern: Brawler's Leather Gloves",
            [itemKeys.npcDrops_add] = {647},
        },
        [252778] = {
            [itemKeys.npcDrops_add] = {647},
        },
        [252779] = {
            [itemKeys.name] = "Pattern: Defender's Leather Gloves",
            [itemKeys.npcDrops_add] = {643,646,3653},
        },
        [252780] = {
            [itemKeys.name] = "Pattern: Totemic Leather Gloves",
            [itemKeys.npcDrops_add] = {11519},
        },
        [252781] = {
            [itemKeys.name] = "Pattern: Stormrider's Leather Gloves",
            [itemKeys.npcDrops_add] = {645,3864},
        },
        [252782] = {
            [itemKeys.name] = "Pattern: Wisdom's Leather Gloves",
            [itemKeys.npcDrops_add] = {3669,3671},
        },
        [252798] = {
            [itemKeys.name] = "Pattern: Brawler's Leather Hood",
            [itemKeys.npcDrops_add] = {3670,3674},
        },
        [252799] = {
            [itemKeys.name] = "Pattern: Trapper's Leather Hood",
            [itemKeys.npcDrops_add] = {3887},
        },
        [252800] = {
            [itemKeys.name] = "Pattern: Defender's Leather Hood",
            [itemKeys.npcDrops_add] = {4887,5775},
        },
        [252801] = {
            [itemKeys.name] = "Pattern: Totemic Leather Hood",
            [itemKeys.npcDrops_add] = {3670,3872,3927,5775},
        },
        [252802] = {
            [itemKeys.name] = "Pattern: Stormrider's Leather Hood",
            [itemKeys.npcDrops_add] = {4887},
        },
        [252803] = {
            [itemKeys.name] = "Pattern: Wisdom's Leather Hood",
            [itemKeys.npcDrops_add] = {4278,4831,4887,5775},
        },
        [252820] = {
            [itemKeys.name] = "Pattern: Brawler's Leather Legguards",
            [itemKeys.npcDrops_add] = {1716,4832,6243},
        },
        [252821] = {
            [itemKeys.name] = "Pattern: Trapper's Leather Legguards",
            [itemKeys.npcDrops_add] = {4832,12902},
        },
        [252822] = {
            [itemKeys.name] = "Pattern: Defender's Leather Kilt",
            [itemKeys.npcDrops_add] = {1716},
        },
        [252823] = {
            [itemKeys.name] = "Pattern: Totemic Leather Leggings",
            [itemKeys.npcDrops_add] = {4829,6243},
        },
        [252824] = {
            [itemKeys.name] = "Pattern: Stormrider's Leather Kilt",
            [itemKeys.npcDrops_add] = {4428},
        },
        [252825] = {
            [itemKeys.name] = "Pattern: Wisdom's Leather Leggings",
            [itemKeys.npcDrops_add] = {1716,6243},
        },
        [253591] = {
            [itemKeys.name] = "Ripe Stormapple",
            [itemKeys.objectDrops_add] = {578937},
        },
        [253595] = {
            [itemKeys.name] = "Flutterfly Dust",
            [itemKeys.objectDrops_add] = {578959},
        },
        [253596] = {
            [itemKeys.name] = "Blood-Stained Bandit Mask",
            [itemKeys.npcDrops_add] = {252820},
        },
        [253597] = {
            [itemKeys.name] = "Lowlands Galestrider Tenderloin",
            [itemKeys.npcDrops_add] = {251707},
        },
        [253710] = {
            [itemKeys.name] = "Bruuz's Dorsal Fin",
            [itemKeys.npcDrops_add] = {209797},
        },
        [253902] = {
            [itemKeys.name] = "Pattern: Filigreed Pristine Gown",
            [itemKeys.npcDrops_add] = {643,3914},
        },
        [253904] = {
            [itemKeys.name] = "Pattern: Filigreed Silky Gown",
            [itemKeys.npcDrops_add] = {3864,11518},
        },
        [253906] = {
            [itemKeys.npcDrops_add] = {646},
        },
        [253908] = {
            [itemKeys.name] = "Pattern: Filigreed Shadow Gown",
            [itemKeys.npcDrops_add] = {3586,3864,3865,3914},
        },
        [253912] = {
            [itemKeys.npcDrops_add] = {11519},
        },
        [253938] = {
            [itemKeys.name] = "Pattern: Filigreed Pristine Leggings",
            [itemKeys.npcDrops_add] = {639,1696,3670,4274,4279},
        },
        [253940] = {
            [itemKeys.name] = "Pattern: Filigreed Silky Leggings",
            [itemKeys.npcDrops_add] = {4887},
        },
        [253942] = {
            [itemKeys.name] = "Pattern: Filigreed Flame Leggings",
            [itemKeys.npcDrops_add] = {3670,3887},
        },
        [253946] = {
            [itemKeys.name] = "Pattern: Filigreed Pearly Leggings",
            [itemKeys.npcDrops_add] = {3886},
        },
        [253948] = {
            [itemKeys.name] = "Pattern: Filigreed Shining Leggings",
            [itemKeys.npcDrops_add] = {639,3654,3674,4275,5775},
        },
        [253982] = {
            [itemKeys.name] = "Pattern: Filigreed Shadow Circlet",
            [itemKeys.npcDrops_add] = {4832},
        },
        [253984] = {
            [itemKeys.name] = "Pattern: Filigreed Pearly Circlet",
            [itemKeys.npcDrops_add] = {1717},
        },
        [253986] = {
            [itemKeys.name] = "Pattern: Filigreed Shining Circlet",
            [itemKeys.npcDrops_add] = {1663,4830},
        },
        [254000] = {
            [itemKeys.name] = "Pattern: Earthen Leggings",
            [itemKeys.npcDrops_add] = {4116},
        },
        [254378] = {
            [itemKeys.name] = "Shriekling Talons",
            [itemKeys.npcDrops_add] = {256092},
        },
        [254432] = {
            [itemKeys.name] = "Carved Centaur Totem",
            [itemKeys.npcDrops_add] = {4654,4655,4656,4657,4659},
        },
        [254548] = {
            [itemKeys.name] = "Longshore Murloc Gill",
            [itemKeys.npcDrops_add] = {126,127,171,456,458,513,515,517},
        },
        [254676] = {
            [itemKeys.name] = "Suspicious Industrial Supplies",
            [itemKeys.objectDrops_add] = {581777},
        },
        [255007] = {
            [itemKeys.name] = "Golem Isospring",
            [itemKeys.npcDrops_add] = {36,114,115,480,276061},
        },
        [255010] = {
            [itemKeys.name] = "Harvester Gyrostabilizer",
            [itemKeys.npcDrops_add] = {36,114,115},
        },
        [255154] = {
            [itemKeys.name] = "Ruined Gyrostabilizer",
            [itemKeys.npcDrops_add] = {480},
        },
        [255155] = {
            [itemKeys.name] = "Precessive Autocognition Assembly",
            [itemKeys.npcDrops_add] = {36,114,480},
        },
        [255658] = {
            [itemKeys.name] = "Al'Aketh Windstone Charm",
            [itemKeys.npcDrops_add] = {252664,252665,252762,252763,252765,253195,253511,270201},
        },
        [255663] = {
            [itemKeys.name] = "Windstone",
            [itemKeys.npcDrops_add] = {251662,251676,251918,251966,252068,252664,252665,252762,252763,252764,252765,252767,252802,252820,253195,253511,253622,254596,254626,255534,256935,256966,256996,257196,257521,257532,270201,276415},
            [itemKeys.objectDrops_add] = {616907,626718},
        },
        [255724] = {
            [itemKeys.name] = "Manual: Clever Poultice",
            [itemKeys.npcDrops_add] = {910},
        },
        [255728] = {
            [itemKeys.name] = "Manual: Potent Anti-Venom",
            [itemKeys.npcDrops_add] = {760},
        },
        [257107] = {
            [itemKeys.name] = "Shriekling Matriarch's Head",
            [itemKeys.npcDrops_add] = {253283},
        },
        [257128] = {
            [itemKeys.name] = "Zephyrseed",
            [itemKeys.objectDrops_add] = {613238},
        },
        [257224] = {
            [itemKeys.name] = "Cracked Windstone",
            [itemKeys.npcDrops_add] = {251662,251676},
        },
        [257226] = {
            [itemKeys.name] = "Lesser Essence of the Four Winds",
            [itemKeys.npcDrops_add] = {251662,251676},
        },
        [257941] = {
            [itemKeys.name] = "Windsong Crawler Meat",
            [itemKeys.npcDrops_add] = {254588},
        },
        [257942] = {
            [itemKeys.name] = "Vulgara's Head",
            [itemKeys.npcDrops_add] = {254589},
        },
        [257945] = {
            [itemKeys.name] = "Pilfered Windstone",
            [itemKeys.npcDrops_add] = {251918,255534},
        },
        [258530] = {
            [itemKeys.name] = "Lucky Lure",
            [itemKeys.npcDrops_add] = {757},
        },
        [258771] = {
            [itemKeys.name] = "Al'Alketh Cultist's Ear",
            [itemKeys.npcDrops_add] = {252664,252665,252762,252763,252764,252765,252767,253195,253511,253622,256966,270201},
        },
        [258772] = {
            [itemKeys.name] = "Windstone Cluster",
            [itemKeys.objectDrops_add] = {613286},
        },
        [260880] = {
            [itemKeys.name] = "Air Construct Core",
            [itemKeys.objectDrops_add] = {616467},
        },
        [260881] = {
            [itemKeys.name] = "Crystallized Lightning",
            [itemKeys.objectDrops_add] = {616468},
        },
        [260883] = {
            [itemKeys.name] = "Enchanted Gyrozephyr",
            [itemKeys.objectDrops_add] = {616466},
        },
        [260927] = {
            [itemKeys.name] = "Rusted Construct Parts",
            [itemKeys.objectDrops_add] = {616466,616467,616468},
        },
        [262357] = {
            [itemKeys.name] = "Wind Hollow Essence",
            [itemKeys.npcDrops_add] = {251676},
        },
        [262668] = {
            [itemKeys.name] = "Wind-Infused Bough",
            [itemKeys.objectDrops_add] = {616860},
        },
        [262888] = {
            [itemKeys.name] = "Sealed Journeyman's Writ",
            [itemKeys.npcDrops_add] = {205,531,1018,1020,1042,1417,2268,3252,3374,3378,3392,3809,3820},
        },
        [262889] = {
            [itemKeys.name] = "Sealed Expert's Writ",
            [itemKeys.npcDrops_add] = {2893},
        },
        [263006] = {
            [itemKeys.name] = "Scout Ranger's Tunic",
            [itemKeys.npcDrops_add] = {256028},
        },
        [263415] = {
            [itemKeys.name] = "Raani's Lucky Feather",
            [itemKeys.objectDrops_add] = {617675},
        },
        [263418] = {
            [itemKeys.name] = "Shadowsong Family Signet",
            [itemKeys.objectDrops_add] = {617674},
        },
        [263493] = {
            [itemKeys.name] = "Hippogryph Down",
            [itemKeys.objectDrops_add] = {617839},
        },
        [263935] = {
            [itemKeys.name] = "Elunar Longstaff",
            [itemKeys.npcDrops_add] = {250936},
        },
        [263936] = {
            [itemKeys.npcDrops_add] = {250936},
        },
        [263993] = {
            [itemKeys.name] = "Skybreaker Bulwark",
            [itemKeys.npcDrops_add] = {257196},
        },
        [264356] = {
            [itemKeys.name] = "Iceclaw Bear Pendant",
            [itemKeys.npcDrops_add] = {706},
        },
        [264693] = {
            [itemKeys.name] = "Scarlet Crusade Attack Plans",
            [itemKeys.npcDrops_add] = {1537,1538},
        },
        [265105] = {
            [itemKeys.name] = "Lady's Tear Moss",
            [itemKeys.objectDrops_add] = {619450},
        },
        [265140] = {
            [itemKeys.name] = "Pristine Shriekling Feather",
            [itemKeys.npcDrops_add] = {256092},
        },
        [265141] = {
            [itemKeys.name] = "Bloody Heirloom",
            [itemKeys.npcDrops_add] = {252664,252665},
        },
        [265475] = {
            [itemKeys.name] = "Commander Haalien's Severed Head",
            [itemKeys.npcDrops_add] = {253622},
        },
        [265476] = {
            [itemKeys.name] = "Ripped Missive",
            [itemKeys.npcDrops_add] = {253622},
        },
        [266433] = {
            [itemKeys.name] = "Abandoned Belongings",
            [itemKeys.objectDrops_add] = {623295},
        },
        [267361] = {
            [itemKeys.name] = "Enchanted Silver Ingot",
            [itemKeys.objectDrops_add] = {629065},
        },
        [267412] = {
            [itemKeys.name] = "Fenris Isle Key",
            [itemKeys.npcDrops_add] = {1942,1943},
        },
        [267413] = {
            [itemKeys.name] = "Gnomeregan Archival Data",
            [itemKeys.objectDrops_add] = {629596},
        },
        [267414] = {
            [itemKeys.name] = "Pristine Leopard Pelt",
            [itemKeys.npcDrops_add] = {260157},
        },
        [267415] = {
            [itemKeys.name] = "Stolen Blasting Powder",
            [itemKeys.npcDrops_add] = {1116,1118},
        },
        [267416] = {
            [itemKeys.name] = "Toughened Boar Hide",
            [itemKeys.npcDrops_add] = {1689},
        },
        [267474] = {
            [itemKeys.name] = "Galeswept Forestshroom",
            [itemKeys.npcDrops_add] = {251918,251966,252068,252664,252665,252762,252763,252764,252765,252767,252802,252820,253195,253511,253622,254596,254626,255534,256966,257196,270201},
            [itemKeys.objectDrops_add] = {626752},
        },
        [268415] = {
            [itemKeys.name] = "Commonplace Herb Seeds",
            [itemKeys.objectDrops_add] = {1617,1618,1619},
        },
        [268416] = {
            [itemKeys.name] = "Uncommon Herb Seeds",
            [itemKeys.objectDrops_add] = {1620,1621,1622,1623,1624,1628,2045},
        },
        [268518] = {
            [itemKeys.name] = "Head of the Baron",
            [itemKeys.npcDrops_add] = {250660},
        },
        [268535] = {
            [itemKeys.name] = "Bloodied Insignia",
            [itemKeys.npcDrops_add] = {250622,250623,250624,250626,250627,250656,250689},
        },
        [268540] = {
            [itemKeys.name] = "Bloodied Insignia",
            [itemKeys.npcDrops_add] = {250618,250622,250623,250624,250626,250627,250630,250656,250689,255109,255964},
        },
        [268548] = {
            [itemKeys.name] = "Empty Powder Keg",
            [itemKeys.npcDrops_add] = {1116,1118},
        },
        [268579] = {
            [itemKeys.name] = "Crest of Lordaeron",
            [itemKeys.objectDrops_add] = {614679},
        },
        [268580] = {
            [itemKeys.name] = "Intact Limbs",
            [itemKeys.npcDrops_add] = {250618,250622,250623,250624,250626,250627,250630,250656,250689,255109,255964},
        },
        [268801] = {
            [itemKeys.name] = "Bottle of Whispering Elixir",
            [itemKeys.objectDrops_add] = {630871,630885},
        },
        [268812] = {
            [itemKeys.name] = "Whispering Horror Residue",
            [itemKeys.npcDrops_add] = {260396},
        },
        [269715] = {
            [itemKeys.name] = "Savannah Lion Hide",
            [itemKeys.npcDrops_add] = {3241,3416},
        },
        [269719] = {
            [itemKeys.name] = "Trapped Game",
            [itemKeys.objectDrops_add] = {640104},
        },
        [269739] = {
            [itemKeys.name] = "Bloody Tuft of Fur",
            [itemKeys.objectDrops_add] = {640104},
        },
        [270001] = {
            [itemKeys.name] = "Rusty Cutlass",
        },
        [270002] = {
            [itemKeys.name] = "Midshipman's Worn Boots",
        },
        [270151] = {
            [itemKeys.name] = "Benedict's Orders",
            [itemKeys.npcDrops_add] = {262119},
        },
        [270180] = {
            [itemKeys.name] = "Horrible Rootcore",
            [itemKeys.npcDrops_add] = {260808},
        },
        [270227] = {
            [itemKeys.name] = "Ephemeral Choker",
            [itemKeys.npcDrops_add] = {261306},
        },
        [270228] = {
            [itemKeys.name] = "Golemheart Stave",
            [itemKeys.npcDrops_add] = {261311},
        },
        [270229] = {
            [itemKeys.name] = "Treads of the Protector Golem",
            [itemKeys.npcDrops_add] = {261311},
        },
        [270230] = {
            [itemKeys.name] = "Kindlegem Girdle",
            [itemKeys.npcDrops_add] = {261316},
        },
        [270231] = {
            [itemKeys.name] = "Flamefist Grips",
            [itemKeys.npcDrops_add] = {261316},
        },
        [270256] = {
            [itemKeys.name] = "Durgen's Crescent Axe",
            [itemKeys.npcDrops_add] = {261319},
        },
        [270260] = {
            [itemKeys.name] = "Direhammer Leggings",
            [itemKeys.npcDrops_add] = {261319},
        },
        [270261] = {
            [itemKeys.name] = "Robes of the Disgraced Thane",
            [itemKeys.npcDrops_add] = {261319},
        },
        [270302] = {
            [itemKeys.name] = "Chakuyak's Pelt",
            [itemKeys.npcDrops_add] = {268558},
        },
        [270435] = {
            [itemKeys.name] = "Rudolph Gelhardt's Head",
            [itemKeys.npcDrops_add] = {259431},
        },
        [270865] = {
            [itemKeys.name] = "Titan Relic",
            [itemKeys.npcDrops_add] = {260326},
        },
        [270866] = {
            [itemKeys.name] = "Titan Relic",
            [itemKeys.npcDrops_add] = {260326},
        },
        [271095] = {
            [itemKeys.name] = "Fang of Magmatus",
            [itemKeys.npcDrops_add] = {261316},
        },
        [271096] = {
            [itemKeys.name] = "Aetherwisp Bracers",
            [itemKeys.npcDrops_add] = {261306},
        },
        [271097] = {
            [itemKeys.name] = "Spiritwraith Drape",
            [itemKeys.npcDrops_add] = {261306},
        },
        [271098] = {
            [itemKeys.name] = "Golemguard Chest",
            [itemKeys.npcDrops_add] = {261311},
        },
        [271100] = {
            [itemKeys.name] = "Thicket Raptor Meat",
            [itemKeys.npcDrops_add] = {260325,260800,260801},
        },
        [271201] = {
            [itemKeys.name] = "Atrophic Girdle",
            [itemKeys.npcDrops_add] = {250483},
        },
        [271202] = {
            [itemKeys.name] = "Witherbite Bracers",
            [itemKeys.npcDrops_add] = {250483},
        },
        [271203] = {
            [itemKeys.name] = "Segmented Spider Leg",
            [itemKeys.npcDrops_add] = {250483},
        },
        [271204] = {
            [itemKeys.name] = "Meathook Slicer",
            [itemKeys.npcDrops_add] = {250660},
        },
        [271205] = {
            [itemKeys.name] = "Abomination Bones",
            [itemKeys.npcDrops_add] = {250660},
        },
        [271206] = {
            [itemKeys.name] = "Leftover Abomination Skin",
            [itemKeys.npcDrops_add] = {250660},
        },
        [271207] = {
            [itemKeys.name] = "Rotmender's Leggings",
            [itemKeys.npcDrops_add] = {250631},
        },
        [271208] = {
            [itemKeys.name] = "Grip of Fear",
            [itemKeys.npcDrops_add] = {250631},
        },
        [271209] = {
            [itemKeys.name] = "Bonerust Leggings",
            [itemKeys.npcDrops_add] = {256097},
        },
        [271210] = {
            [itemKeys.name] = "Tuskwrap Belt",
            [itemKeys.npcDrops_add] = {256097},
        },
        [271211] = {
            [itemKeys.name] = "Vilewalkers",
            [itemKeys.npcDrops_add] = {256035},
        },
        [271212] = {
            [itemKeys.name] = "Bloodied Chestwraps",
            [itemKeys.npcDrops_add] = {256035},
        },
        [271213] = {
            [itemKeys.name] = "Mirror of Rath'mael",
            [itemKeys.npcDrops_add] = {250657},
        },
        [271214] = {
            [itemKeys.name] = "Rotmender's Treads",
            [itemKeys.npcDrops_add] = {250657},
        },
        [271215] = {
            [itemKeys.name] = "Coldspire Staff",
            [itemKeys.npcDrops_add] = {250657},
        },
        [271216] = {
            [itemKeys.name] = "Scepter of the Abandoned",
            [itemKeys.npcDrops_add] = {250631},
        },
        [271217] = {
            [itemKeys.name] = "Corpse Chopper",
            [itemKeys.npcDrops_add] = {256097},
        },
        [271218] = {
            [itemKeys.name] = "Vileblood Scimitar",
            [itemKeys.npcDrops_add] = {256035},
        },
        [271343] = {
            [itemKeys.name] = "Note Scrap",
            [itemKeys.npcDrops_add] = {1973,1974},
        },
        [271350] = {
            [itemKeys.name] = "Tortured Soul",
            [itemKeys.npcDrops_add] = {1973,1974},
        },
        [271872] = {
            [itemKeys.name] = "Broken Staff of Incinerator Gar'im",
            [itemKeys.npcDrops_add] = {214519},
        },
        [272996] = {
            [itemKeys.name] = "Trogg Scepter",
            [itemKeys.npcDrops_add] = {11517},
        },
        [272998] = {
            [itemKeys.name] = "Bone Knuckles",
            [itemKeys.npcDrops_add] = {11517},
        },
        [272999] = {
            [itemKeys.name] = "Barbaric Crossbow",
            [itemKeys.npcDrops_add] = {11517},
        },
        [273001] = {
            [itemKeys.name] = "Gloomrise Toxin Sample",
            [itemKeys.npcDrops_add] = {264096},
        },
        [273003] = {
            [itemKeys.name] = "Searing Dagger",
            [itemKeys.npcDrops_add] = {11519},
        },
        [273005] = {
            [itemKeys.name] = "Satyrskin Cloak",
            [itemKeys.npcDrops_add] = {11519},
        },
        [273007] = {
            [itemKeys.name] = "Chasm Walkers",
            [itemKeys.npcDrops_add] = {11519},
        },
        [273022] = {
            [itemKeys.name] = "Supple Bellyskin Leggings",
            [itemKeys.npcDrops_add] = {260322},
        },
        [273023] = {
            [itemKeys.name] = "Saltscale Girdle",
            [itemKeys.npcDrops_add] = {260322},
        },
        [273024] = {
            [itemKeys.name] = "Glinteye Slippers",
            [itemKeys.npcDrops_add] = {260322},
        },
        [273025] = {
            [itemKeys.name] = "Raptorclaw Greaves",
            [itemKeys.npcDrops_add] = {260325},
        },
        [273026] = {
            [itemKeys.name] = "Garb of Florid Feathers",
            [itemKeys.npcDrops_add] = {260325},
        },
        [273027] = {
            [itemKeys.name] = "Raptor's Gaze",
            [itemKeys.npcDrops_add] = {260325},
        },
        [273028] = {
            [itemKeys.name] = "Reliquary Mantle",
            [itemKeys.npcDrops_add] = {260326},
        },
        [273029] = {
            [itemKeys.name] = "Golemsight Long Gun",
            [itemKeys.npcDrops_add] = {260326},
        },
        [273030] = {
            [itemKeys.name] = "Ring of Power Regulation",
            [itemKeys.npcDrops_add] = {260326},
        },
        [273032] = {
            [itemKeys.name] = "Bonebinder's Signet",
            [itemKeys.npcDrops_add] = {247126},
        },
        [273034] = {
            [itemKeys.name] = "Ephemeral Grips",
            [itemKeys.npcDrops_add] = {245999},
        },
        [273035] = {
            [itemKeys.name] = "Mana-Warped Chain Shirt",
            [itemKeys.npcDrops_add] = {245999},
        },
        [273036] = {
            [itemKeys.name] = "Graveweave Bindings",
            [itemKeys.npcDrops_add] = {247126},
        },
        [273037] = {
            [itemKeys.name] = "Felbough Arm",
            [itemKeys.npcDrops_add] = {246003},
        },
        [273038] = {
            [itemKeys.name] = "Garb of Fallen Felbark",
            [itemKeys.npcDrops_add] = {246003},
        },
        [273039] = {
            [itemKeys.name] = "Blightleaf Rope",
            [itemKeys.npcDrops_add] = {246003},
        },
        [273040] = {
            [itemKeys.name] = "Spine of the Devourer",
            [itemKeys.npcDrops_add] = {246008},
        },
        [273041] = {
            [itemKeys.name] = "Slitherwrap Girdle",
            [itemKeys.npcDrops_add] = {246008},
        },
        [273042] = {
            [itemKeys.name] = "Manascale Treads",
            [itemKeys.npcDrops_add] = {246008},
        },
        [273044] = {
            [itemKeys.name] = "Violet Sorcerer's Robes",
            [itemKeys.npcDrops_add] = {246016},
        },
        [273045] = {
            [itemKeys.name] = "Drape of Shifting Energy",
            [itemKeys.npcDrops_add] = {246016},
        },
        [273046] = {
            [itemKeys.name] = "Guardian's Dualblade",
            [itemKeys.npcDrops_add] = {246017},
        },
        [273051] = {
            [itemKeys.name] = "Violet Sorcerer's Mantle",
            [itemKeys.npcDrops_add] = {246020},
        },
        [273053] = {
            [itemKeys.name] = "Tendonscraper Dagger",
            [itemKeys.npcDrops_add] = {247032},
        },
        [273084] = {
            [itemKeys.name] = "Cloak of Hermitic Bliss",
            [itemKeys.npcDrops_add] = {3653},
        },
        [273085] = {
            [itemKeys.name] = "Blueprint: Fermenter",
            [itemKeys.npcDrops_add] = {250657},
        },
        [273086] = {
            [itemKeys.name] = "Blueprint: Anvil",
            [itemKeys.npcDrops_add] = {1763},
        },
        [273087] = {
            [itemKeys.name] = "Blueprint: Journeyman Campfire",
            [itemKeys.npcDrops_add] = {3673},
        },
        [273088] = {
            [itemKeys.name] = "Snake Eye Kaleidoscope",
            [itemKeys.npcDrops_add] = {3671},
        },
        [273089] = {
            [itemKeys.name] = "Slither Cord",
            [itemKeys.npcDrops_add] = {3670},
        },
        [273092] = {
            [itemKeys.name] = "Blueprint: Repair Bot",
            [itemKeys.npcDrops_add] = {643},
        },
        [273096] = {
            [itemKeys.name] = "Blueprint: Tanning Rack",
            [itemKeys.npcDrops_add] = {3886},
        },
        [273097] = {
            [itemKeys.name] = "Blueprint: Rock Garden",
            [itemKeys.npcDrops_add] = {260326},
        },
        [273098] = {
            [itemKeys.name] = "Blueprint: Field Guide",
            [itemKeys.npcDrops_add] = {3671},
        },
        [273103] = {
            [itemKeys.name] = "Blueprint: Arcane Salvager",
            [itemKeys.npcDrops_add] = {250657},
        },
        [273105] = {
            [itemKeys.name] = "Blueprint: Toxin Study",
            [itemKeys.npcDrops_add] = {4278},
        },
        [273137] = {
            [itemKeys.name] = "Skum's Bucket",
            [itemKeys.npcDrops_add] = {3674},
        },
        [273141] = {
            [itemKeys.name] = "Blueprint: Fishing Rack",
            [itemKeys.npcDrops_add] = {6243},
        },
        [273181] = {
            [itemKeys.name] = "Crystalline Silk",
            [itemKeys.npcDrops_add] = {264081},
        },
        [273289] = {
            [itemKeys.name] = "Ogre Loincloth",
            [itemKeys.npcDrops_add] = {644},
        },
        [273293] = {
            [itemKeys.name] = "Bandsaw Wristbands",
            [itemKeys.npcDrops_add] = {643},
        },
        [273297] = {
            [itemKeys.name] = "Goblin Hammer",
            [itemKeys.npcDrops_add] = {1763},
        },
        [273298] = {
            [itemKeys.name] = "Lookie's Spyglass",
            [itemKeys.npcDrops_add] = {645},
        },
        [273456] = {
            [itemKeys.name] = "Cell Keeper's Claws",
            [itemKeys.npcDrops_add] = {3914},
        },
        [273457] = {
            [itemKeys.name] = "Sorcerer Collar",
            [itemKeys.npcDrops_add] = {3914},
        },
        [273637] = {
            [itemKeys.name] = "Blade of Silverlaine",
            [itemKeys.npcDrops_add] = {3887},
        },
        [273643] = {
            [itemKeys.name] = "Worgenbane Talisman",
            [itemKeys.npcDrops_add] = {4278},
        },
        [273645] = {
            [itemKeys.name] = "Blindwatcher's Sight",
            [itemKeys.npcDrops_add] = {4279},
        },
        [273646] = {
            [itemKeys.name] = "Half-Eaten Boots",
            [itemKeys.npcDrops_add] = {4274},
        },
        [273647] = {
            [itemKeys.name] = "Worgpelt Leggings",
            [itemKeys.npcDrops_add] = {3927},
        },
        [273658] = {
            [itemKeys.name] = "Bloody Parchment",
            [itemKeys.npcDrops_add] = {264082},
        },
        [273804] = {
            [itemKeys.name] = "Executioner Mantle",
            [itemKeys.npcDrops_add] = {1696},
        },
        [273805] = {
            [itemKeys.name] = "Blackrock Harness",
            [itemKeys.npcDrops_add] = {1696},
        },
        [273806] = {
            [itemKeys.name] = "Dark Horde Band",
            [itemKeys.npcDrops_add] = {1696},
        },
        [273807] = {
            [itemKeys.name] = "Demolition Girdle",
            [itemKeys.npcDrops_add] = {1666},
        },
        [273808] = {
            [itemKeys.name] = "Bridgebreaker Bindings",
            [itemKeys.npcDrops_add] = {1666},
        },
        [273809] = {
            [itemKeys.name] = "Hamhock's Cleaver",
            [itemKeys.npcDrops_add] = {1717},
        },
        [273810] = {
            [itemKeys.name] = "Ogre Grips",
            [itemKeys.npcDrops_add] = {1717},
        },
        [273811] = {
            [itemKeys.name] = "Repurposed Rack",
            [itemKeys.npcDrops_add] = {1717},
        },
        [273815] = {
            [itemKeys.name] = "Airy Windseeker's Shirt",
            [itemKeys.npcDrops_add] = {252664,252665,252762,252763,252765,252767,256966,270201},
        },
        [273817] = {
            [itemKeys.name] = "Graverobber's Shovel",
            [itemKeys.npcDrops_add] = {1663},
        },
        [273819] = {
            [itemKeys.name] = "Boneslicer",
            [itemKeys.npcDrops_add] = {1663},
        },
        [273820] = {
            [itemKeys.name] = "Nightskulker Ring",
            [itemKeys.npcDrops_add] = {1663},
        },
        [273824] = {
            [itemKeys.name] = "Defias Jailbreakers",
            [itemKeys.npcDrops_add] = {1716},
        },
        [273825] = {
            [itemKeys.name] = "Red Wool Cloak",
            [itemKeys.npcDrops_add] = {1716},
        },
        [273827] = {
            [itemKeys.name] = "Debt Collector",
            [itemKeys.npcDrops_add] = {1716},
        },
        [273829] = {
            [itemKeys.name] = "Concealed Hand Crossbow",
            [itemKeys.npcDrops_add] = {1716},
        },
        [273839] = {
            [itemKeys.name] = "Spiked Shell Band",
            [itemKeys.npcDrops_add] = {4887},
        },
        [273840] = {
            [itemKeys.name] = "Cursed Murloc Eye",
            [itemKeys.npcDrops_add] = {6243},
        },
        [273841] = {
            [itemKeys.name] = "Twilight Maul",
            [itemKeys.npcDrops_add] = {12902},
        },
        [273842] = {
            [itemKeys.name] = "Treacherous Treads",
            [itemKeys.npcDrops_add] = {12902},
        },
        [273843] = {
            [itemKeys.name] = "Fallenroot Longbow",
            [itemKeys.npcDrops_add] = {12902},
        },
        [273846] = {
            [itemKeys.name] = "Twilight Lord Girdle",
            [itemKeys.npcDrops_add] = {4832},
        },
        [274042] = {
            [itemKeys.name] = "Skullduggery Belt",
            [itemKeys.npcDrops_add] = {7361},
        },
        [274043] = {
            [itemKeys.name] = "Irradiated Shield",
            [itemKeys.npcDrops_add] = {7361},
        },
        [274044] = {
            [itemKeys.name] = "Twisted Fire Totem",
            [itemKeys.npcDrops_add] = {2893},
        },
        [274045] = {
            [itemKeys.name] = "Twisted Earth Totem",
            [itemKeys.npcDrops_add] = {755,757,760},
        },
        [274046] = {
            [itemKeys.name] = "Twisted Water Totem",
            [itemKeys.npcDrops_add] = {4358,4359,4360,4361,4362},
        },
        [274047] = {
            [itemKeys.name] = "Twisted Air Totem",
            [itemKeys.npcDrops_add] = {4655,4656,4657,4658},
        },
        [274068] = {
            [itemKeys.name] = "Thermaplugg Medal of Honor",
            [itemKeys.npcDrops_add] = {6229},
        },
        [274092] = {
            [itemKeys.name] = "Sharpened Cutlery",
            [itemKeys.npcDrops_add] = {1706,1707,1708},
        },
        [274155] = {
            [itemKeys.name] = "Geomancer Headdress",
            [itemKeys.npcDrops_add] = {6168},
        },
        [274158] = {
            [itemKeys.name] = "Death Prophet Spine",
            [itemKeys.npcDrops_add] = {4424},
        },
        [274159] = {
            [itemKeys.name] = "Thorncursed Grips",
            [itemKeys.npcDrops_add] = {4424},
        },
        [274160] = {
            [itemKeys.name] = "Quilrager Throwing Axe",
            [itemKeys.npcDrops_add] = {4422},
        },
        [274268] = {
            [itemKeys.name] = "Dark Iron Map",
            [itemKeys.npcDrops_add] = {6123,6124},
        },
        [274286] = {
            [itemKeys.name] = "Durgen Dirgehammer's Head",
            [itemKeys.npcDrops_add] = {261319},
        },
        [274289] = {
            [itemKeys.name] = "Dwarven Heirloom",
            [itemKeys.objectDrops_add] = {457387,652227,652228},
        },
        [274290] = {
            [itemKeys.name] = "Painwalker Buckler",
            [itemKeys.npcDrops_add] = {3983},
        },
        [274463] = {
            [itemKeys.name] = "Tattered Note",
            [itemKeys.npcDrops_add] = {4421},
        },
        [274947] = {
            [itemKeys.name] = "Scroll of Imbue Lesser Flame",
        },
        [275067] = {
            [itemKeys.name] = "Scroll of Imbue Chillknife",
        },
        [275069] = {
            [itemKeys.name] = "Scroll of Rat Familiar",
        },
        [275443] = {
            [itemKeys.name] = "Highly Toxic Strain",
            [itemKeys.npcDrops_add] = {250483},
        },
        [275521] = {
            [itemKeys.name] = "Crest of Lordaeron",
            [itemKeys.objectDrops_add] = {614679},
        },
        [275713] = {
            [itemKeys.name] = "Raider's Bow",
            [itemKeys.objectDrops_add] = {656180},
        },
        [275716] = {
            [itemKeys.name] = "Raider's Battleaxe",
            [itemKeys.objectDrops_add] = {656181},
        },
        [275717] = {
            [itemKeys.name] = "Raider's Shield",
            [itemKeys.objectDrops_add] = {656182},
        },
        [275718] = {
            [itemKeys.name] = "Prickly Pear Fruit",
            [itemKeys.objectDrops_add] = {656177},
        },
        [275719] = {
            [itemKeys.name] = "Weathered Spine",
            [itemKeys.npcDrops_add] = {3130,3131},
        },
        [275720] = {
            [itemKeys.name] = "Rough Lizard Hide",
            [itemKeys.npcDrops_add] = {3130,3131},
        },
        [275722] = {
            [itemKeys.name] = "Ukor's Lost Pack",
            [itemKeys.npcDrops_add] = {266851},
        },
        [275723] = {
            [itemKeys.name] = "Halikor's Hoof",
            [itemKeys.npcDrops_add] = {266852},
        },
        [275724] = {
            [itemKeys.name] = "Hexed Pendant",
            [itemKeys.npcDrops_add] = {3206,3207},
        },
        [275842] = {
            [itemKeys.name] = "Fossilized Insect",
            [itemKeys.objectDrops_add] = {656332,656333},
        },
        [275843] = {
            [itemKeys.name] = "Tuft of Hair",
            [itemKeys.objectDrops_add] = {656332,656333},
        },
        [275851] = {
            [itemKeys.name] = "Necrotic Crystal Fragment",
            [itemKeys.npcDrops_add] = {267006,275437},
            [itemKeys.objectDrops_add] = {656366},
        },
        [275891] = {
            [itemKeys.name] = "Dwarven Skull",
            [itemKeys.npcDrops_add] = {263396,263397},
        },
        [275892] = {
            [itemKeys.name] = "Short Stout",
            [itemKeys.npcDrops_add] = {263396,263438},
        },
        [275893] = {
            [itemKeys.name] = "Searing Gourd",
            [itemKeys.npcDrops_add] = {263396,263397,263438},
        },
        [275894] = {
            [itemKeys.name] = "Ghastly Cloth",
            [itemKeys.npcDrops_add] = {250620,263389,263390},
        },
        [275895] = {
            [itemKeys.name] = "Fading Echo",
            [itemKeys.npcDrops_add] = {250620,250650,250651,263389,263390},
        },
        [275996] = {
            [itemKeys.name] = "The Founding of Dalaran",
            [itemKeys.objectDrops_add] = {656681},
        },
        [275997] = {
            [itemKeys.name] = "Cracked Sentry Core",
            [itemKeys.npcDrops_add] = {246664},
        },
        [276070] = {
            [itemKeys.name] = "Chol'aruk's Head",
            [itemKeys.npcDrops_add] = {267307},
        },
        [276158] = {
            [itemKeys.name] = "Crystallized Shard",
            [itemKeys.npcDrops_add] = {246664,247001},
        },
        [276160] = {
            [itemKeys.name] = "Mana Fragment",
            [itemKeys.npcDrops_add] = {246600,246664,246888,246990,247001,247003},
        },
        [276561] = {
            [itemKeys.name] = "Black Tome",
            [itemKeys.objectDrops_add] = {659376},
        },
        [276694] = {
            [itemKeys.name] = "Captain Sander's Lucky Shooter",
        },
        [277128] = {
            [itemKeys.name] = "Bloodtalon Martriarch Eggs",
            [itemKeys.npcDrops_add] = {268530},
        },
        [277135] = {
            [itemKeys.name] = "Forgotten Loa Idol",
            [itemKeys.objectDrops_add] = {660647},
        },
        [277190] = {
            [itemKeys.name] = "Fang of Githyiss",
            [itemKeys.npcDrops_add] = {1994},
        },
        [277194] = {
            [itemKeys.name] = "Trollbane Conquests",
            [itemKeys.objectDrops_add] = {660730},
        },
        [277195] = {
            [itemKeys.name] = "The Forsaken Ally",
            [itemKeys.objectDrops_add] = {660729},
        },
        [277196] = {
            [itemKeys.name] = "Field Accounts of Horde Razings",
            [itemKeys.objectDrops_add] = {660731},
        },
        [277197] = {
            [itemKeys.name] = "Cycles of Morality",
            [itemKeys.objectDrops_add] = {660732},
        },
        [277267] = {
            [itemKeys.name] = "Faladiel's Heart",
            [itemKeys.npcDrops_add] = {268602},
        },
        [277269] = {
            [itemKeys.name] = "Kuramaa's Mask",
            [itemKeys.npcDrops_add] = {268605},
        },
        [277277] = {
            [itemKeys.name] = "Olgra's Adornments",
            [itemKeys.npcDrops_add] = {268624},
        },
        [277278] = {
            [itemKeys.name] = "Handful of Cattails",
            [itemKeys.objectDrops_add] = {661093},
        },
        [277279] = {
            [itemKeys.name] = "Speargrass Cuttings",
            [itemKeys.objectDrops_add] = {661092},
        },
        [277331] = {
            [itemKeys.name] = "Handful of Complicated Parts",
            [itemKeys.objectDrops_add] = {660930},
        },
        [277470] = {
            [itemKeys.name] = "Schematic: Harvester Override Signalcaster",
            [itemKeys.npcDrops_add] = {276061},
        },
        [277653] = {
            [itemKeys.name] = "Abandoned Training Weapon",
            [itemKeys.objectDrops_add] = {673476},
        },
        [277661] = {
            [itemKeys.name] = "Dull Storm Orb",
            [itemKeys.npcDrops_add] = {3118},
        },
        [277665] = {
            [itemKeys.name] = "Charged Thunder Lizard Organ",
            [itemKeys.npcDrops_add] = {3130,3131},
        },
        [277917] = {
            [itemKeys.name] = "Stonetalon Supply Bundle",
            [itemKeys.npcDrops_add] = {4012,4014},
        },
        [277936] = {
            [itemKeys.name] = "Glittering Sunstone",
            [itemKeys.npcDrops_add] = {4022,4023,4024,4025,4026,4027,12579},
        },
        [277952] = {
            [itemKeys.name] = "Smooth Boulder",
            [itemKeys.objectDrops_add] = {661446,661448,661449},
        },
        [277976] = {
            [itemKeys.name] = "Gozwin's Mechanic's Log",
            [itemKeys.objectDrops_add] = {664122},
        },
        [278049] = {
            [itemKeys.name] = "Excavation Tools",
            [itemKeys.objectDrops_add] = {665282},
        },
        [278201] = {
            [itemKeys.name] = "Mirkweed Pods",
            [itemKeys.objectDrops_add] = {667362,667364},
        },
        [278242] = {
            [itemKeys.name] = "Duskbat Wing Membrane",
            [itemKeys.npcDrops_add] = {1553,1554},
        },
        [278243] = {
            [itemKeys.name] = "Darkhound Hide",
            [itemKeys.npcDrops_add] = {1547,1548},
        },
        [278244] = {
            [itemKeys.name] = "Vile Fin Murloc Skin",
            [itemKeys.npcDrops_add] = {1544,1545},
        },
        [278398] = {
            [itemKeys.name] = "Excavation Tools",
            [itemKeys.objectDrops_add] = {665282},
        },
        [279082] = {
            [itemKeys.name] = "Gnarlpine Totem",
            [itemKeys.objectDrops_add] = {668482,668493},
        },
        [279186] = {
            [itemKeys.name] = "Stormheart's Still-beating Heart",
            [itemKeys.npcDrops_add] = {270094},
        },
        [279275] = {
            [itemKeys.name] = "Clouded Water Globe",
            [itemKeys.npcDrops_add] = {270294},
        },
        [279276] = {
            [itemKeys.name] = "Mathystral Amulet Fragment",
            [itemKeys.npcDrops_add] = {2181,2182,2183,271903},
        },
        [279279] = {
            [itemKeys.name] = "Peerless Eye",
            [itemKeys.npcDrops_add] = {2338,2339},
        },
        [279383] = {
            [itemKeys.name] = "Stolen Freewind Supplies",
            [itemKeys.objectDrops_add] = {670338},
        },
        [279385] = {
            [itemKeys.name] = "Pristine Crimson Scale",
            [itemKeys.npcDrops_add] = {1042,1043,1044,1069},
        },
        [279389] = {
            [itemKeys.name] = "Sack of Homebrew Hops",
            [itemKeys.objectDrops_add] = {670348},
        },
        [279469] = {
            [itemKeys.name] = "Grimy Key",
            [itemKeys.objectDrops_add] = {670427},
        },
        [279505] = {
            [itemKeys.name] = "Jagged Orcish Sword",
            [itemKeys.npcDrops_add] = {11682},
        },
        [279507] = {
            [itemKeys.name] = "Curved Orcish Dagger",
            [itemKeys.npcDrops_add] = {11680},
        },
        [279537] = {
            [itemKeys.name] = "Rotheap Innards",
            [itemKeys.npcDrops_add] = {270589},
        },
        [279591] = {
            [itemKeys.name] = "Marek's Croc-Hunting Knife",
            [itemKeys.npcDrops_add] = {270693},
        },
        [279821] = {
            [itemKeys.name] = "Khaz Modan Timber",
            [itemKeys.objectDrops_add] = {670771,670773},
        },
        [279822] = {
            [itemKeys.name] = "Khaz Modan Iron",
            [itemKeys.objectDrops_add] = {670774},
        },
        [279915] = {
            [itemKeys.name] = "Nord'el",
            [itemKeys.objectDrops_add] = {670962},
        },
        [279991] = {
            [itemKeys.name] = "Dry Branch",
            [itemKeys.objectDrops_add] = {671154},
        },
        [279993] = {
            [itemKeys.name] = "Titanic Keystone",
            [itemKeys.npcDrops_add] = {270892},
        },
        [280087] = {
            [itemKeys.name] = "Soft Nightsaber Pelt",
            [itemKeys.npcDrops_add] = {2042},
        },
        [280103] = {
            [itemKeys.name] = "Razormaw Incisor",
            [itemKeys.npcDrops_add] = {1018,1019},
        },
        [280132] = {
            [itemKeys.name] = "Perfect Razormaw Egg",
            [itemKeys.objectDrops_add] = {671892,671931},
        },
        [280319] = {
            [itemKeys.name] = "Unruptured Stalker Gland",
            [itemKeys.npcDrops_add] = {1111,4040},
        },
        [280330] = {
            [itemKeys.name] = "Carnage's Head",
            [itemKeys.npcDrops_add] = {271336},
        },
        [280331] = {
            [itemKeys.name] = "Malignant Rotclaw Flesh",
            [itemKeys.npcDrops_add] = {271334},
        },
        [280369] = {
            [itemKeys.name] = "Dragonmaw Armaments",
            [itemKeys.objectDrops_add] = {672334,672336,672337},
        },
        [280375] = {
            [itemKeys.name] = "Worgen Bits",
            [itemKeys.npcDrops_add] = {1924},
        },
        [280395] = {
            [itemKeys.name] = "Heart of Ados",
            [itemKeys.npcDrops_add] = {271338},
        },
        [280396] = {
            [itemKeys.name] = "Heart of Modr",
            [itemKeys.npcDrops_add] = {271460},
        },
        [280397] = {
            [itemKeys.name] = "Heart of Golm",
            [itemKeys.npcDrops_add] = {271462},
        },
        [280398] = {
            [itemKeys.name] = "Heart of Neru",
            [itemKeys.npcDrops_add] = {271458},
        },
        [280413] = {
            [itemKeys.name] = "Flintfire's Shipment",
            [itemKeys.objectDrops_add] = {672508},
        },
        [280426] = {
            [itemKeys.name] = "Sack of Fish",
            [itemKeys.npcDrops_add] = {271587},
        },
        [280438] = {
            [itemKeys.name] = "Abominable Head",
            [itemKeys.npcDrops_add] = {250660},
        },
        [280502] = {
            [itemKeys.name] = "Relic of the Fang",
            [itemKeys.objectDrops_add] = {672821},
        },
        [280679] = {
            [itemKeys.name] = "Relic of the Claw",
            [itemKeys.objectDrops_add] = {673093},
        },
        [280680] = {
            [itemKeys.name] = "Relic of the Silent Shadow",
            [itemKeys.objectDrops_add] = {673094},
        },
        [280686] = {
            [itemKeys.name] = "Rod of Deep Dominion",
            [itemKeys.npcDrops_add] = {271903},
        },
        [280806] = {
            [itemKeys.name] = "Stolen Explosives",
            [itemKeys.objectDrops_add] = {673206},
        },
        [280831] = {
            [itemKeys.name] = "Hatescreech's Amulet",
            [itemKeys.npcDrops_add] = {272034},
        },
        [280832] = {
            [itemKeys.name] = "Windmistress Gaedress' Amulet",
            [itemKeys.npcDrops_add] = {272044},
        },
        [280834] = {
            [itemKeys.name] = "Witchmother Arysa's Amulet",
            [itemKeys.npcDrops_add] = {272046},
        },
        [280839] = {
            [itemKeys.name] = "Blackrock Supplies",
            [itemKeys.objectDrops_add] = {673376,673384,673385},
        },
        [280841] = {
            [itemKeys.name] = "Stolen Weapon",
            [itemKeys.objectDrops_add] = {673390,673399},
        },
        [280911] = {
            [itemKeys.name] = "Spiked Collar",
            [itemKeys.npcDrops_add] = {712},
        },
        [281014] = {
            [itemKeys.name] = "Vine-Wrapped Scroll",
            [itemKeys.objectDrops_add] = {673431},
        },
        [281023] = {
            [itemKeys.name] = "Mature Fel Moss",
            [itemKeys.npcDrops_add] = {272116},
        },
        [281031] = {
            [itemKeys.name] = "Mulgore Expansion Plans",
            [itemKeys.npcDrops_add] = {3051},
        },
        [281035] = {
            [itemKeys.name] = "Shredder Operation Instructions",
            [itemKeys.objectDrops_add] = {673494},
        },
        [281036] = {
            [itemKeys.name] = "Barrens Operations Best Practices",
            [itemKeys.objectDrops_add] = {673496},
        },
        [281037] = {
            [itemKeys.name] = "One \"Gerenzo\", of Stonetalon",
            [itemKeys.objectDrops_add] = {673497},
        },
        [281038] = {
            [itemKeys.name] = "Feather of Jai'vhanel",
            [itemKeys.npcDrops_add] = {270196},
        },
        [281046] = {
            [itemKeys.name] = "Raven Hill Tome",
            [itemKeys.objectDrops_add] = {673515},
        },
        [281048] = {
            [itemKeys.name] = "Clearcutter Key",
            [itemKeys.npcDrops_add] = {272173},
        },
        [281142] = {
            [itemKeys.name] = "Merrick's Bow",
            [itemKeys.npcDrops_add] = {272273},
        },
        [281143] = {
            [itemKeys.name] = "Ira's Dagger",
            [itemKeys.npcDrops_add] = {272260},
        },
        [281145] = {
            [itemKeys.name] = "Silvia's Sword",
            [itemKeys.npcDrops_add] = {272284},
        },
        [281146] = {
            [itemKeys.name] = "Grant's Mace",
            [itemKeys.npcDrops_add] = {202,531,787},
        },
        [281147] = {
            [itemKeys.name] = "Grant's Shield",
            [itemKeys.npcDrops_add] = {272291},
        },
        [281300] = {
            [itemKeys.name] = "Blisterweed",
            [itemKeys.objectDrops_add] = {673933},
        },
        [281347] = {
            [itemKeys.name] = "Torn Page",
            [itemKeys.objectDrops_add] = {674124},
        },
        [281350] = {
            [itemKeys.name] = "Keystone Fragment",
            [itemKeys.objectDrops_add] = {701788},
        },
        [281358] = {
            [itemKeys.name] = "Stone Key",
            [itemKeys.objectDrops_add] = {702301},
        },
        [281925] = {
            [itemKeys.name] = "Whelpfire Wand",
            [itemKeys.npcDrops_add] = {14272},
        },
        [282637] = {
            [itemKeys.name] = "Shaking Egg",
            [itemKeys.npcDrops_add] = {14268},
        },
        [283460] = {
            [itemKeys.name] = "Decaying Flesh Belt",
            [itemKeys.npcDrops_add] = {271080},
        },
        [283462] = {
            [itemKeys.name] = "Bayne's Bite",
            [itemKeys.npcDrops_add] = {10356},
        },
        [283471] = {
            [itemKeys.name] = "Fellicent's Bindings",
            [itemKeys.npcDrops_add] = {10358},
        },
        [284146] = {
            [itemKeys.name] = "Essene's Waterskin",
            [itemKeys.objectDrops_add] = {678585},
        },
        [284150] = {
            [itemKeys.name] = "Essene's Spellbook",
            [itemKeys.objectDrops_add] = {678590},
        },
        [284167] = {
            [itemKeys.name] = "Blackmoss Robes",
            [itemKeys.npcDrops_add] = {3535},
        },
        [284173] = {
            [itemKeys.name] = "Impcaster's Staff",
            [itemKeys.npcDrops_add] = {2191},
        },
        [284174] = {
            [itemKeys.name] = "Serrated Shadowclaw",
            [itemKeys.npcDrops_add] = {2175},
        },
        [284192] = {
            [itemKeys.name] = "Furbolg Loincloth",
            [itemKeys.npcDrops_add] = {2186},
        },
        [284193] = {
            [itemKeys.name] = "Moongazer's Wand",
            [itemKeys.npcDrops_add] = {2184},
        },
        [284287] = {
            [itemKeys.name] = "Felweaver's Staff",
            [itemKeys.npcDrops_add] = {5822},
        },
        [284321] = {
            [itemKeys.name] = "Centaur Raider's Axe",
            [itemKeys.npcDrops_add] = {5808},
        },
        [284323] = {
            [itemKeys.name] = "Geolord's Mitts",
            [itemKeys.npcDrops_add] = {5826},
        },
        [284361] = {
            [itemKeys.npcDrops_add] = {5787},
        },
        [284705] = {
            [itemKeys.name] = "Essene's Necklace",
            [itemKeys.objectDrops_add] = {687845},
        },
        [284715] = {
            [itemKeys.name] = "First Mate Band",
            [itemKeys.npcDrops_add] = {646},
        },
        [284844] = {
            [itemKeys.name] = "Dragonmaw Dispatch",
            [itemKeys.npcDrops_add] = {275046},
        },
        [284845] = {
            [itemKeys.name] = "Thicket Raptor Hide",
            [itemKeys.npcDrops_add] = {260325,260800,260801,260802},
        },
        [285269] = {
            [itemKeys.name] = "Thendal Watcher's Boots",
            [itemKeys.npcDrops_add] = {259394},
        },
        [285272] = {
            [itemKeys.name] = "Skyseer's Belt",
            [itemKeys.npcDrops_add] = {256492},
        },
        [285274] = {
            [itemKeys.name] = "Thendal Watcher's Belt",
            [itemKeys.npcDrops_add] = {256492},
        },
        [285292] = {
            [itemKeys.name] = "Dull Sawblade",
            [itemKeys.npcDrops_add] = {642},
        },
        [285329] = {
            [itemKeys.name] = "Raptor Hide Cloak",
            [itemKeys.npcDrops_add] = {5842},
        },
        [285330] = {
            [itemKeys.name] = "Signet of the Zhevra",
            [itemKeys.npcDrops_add] = {5831},
        },
        [285346] = {
            [itemKeys.name] = "Alliance Outrunner's Sword",
            [itemKeys.npcDrops_add] = {5798},
        },
        [285347] = {
            [itemKeys.name] = "Alliance Outrunner Bow",
            [itemKeys.npcDrops_add] = {5797},
        },
        [285348] = {
            [itemKeys.name] = "Alliance Outrunner Healing Rod",
            [itemKeys.npcDrops_add] = {5799},
        },
        [285350] = {
            [itemKeys.name] = "Alliance Outrunner Staff",
            [itemKeys.npcDrops_add] = {5800},
        },
        [286008] = {
            [itemKeys.name] = "Naga Spinefin",
            [itemKeys.npcDrops_add] = {275662,275663},
        },
        [286009] = {
            [itemKeys.name] = "Aggor's Belt",
            [itemKeys.npcDrops_add] = {275666},
        },
        [286010] = {
            [itemKeys.name] = "Broken Bone Trident",
            [itemKeys.objectDrops_add] = {693669},
        },
        [286011] = {
            [itemKeys.name] = "Banner Scrap",
            [itemKeys.objectDrops_add] = {693670},
        },
        [286012] = {
            [itemKeys.name] = "Orcish Dagger",
            [itemKeys.objectDrops_add] = {693674},
        },
        [286017] = {
            [itemKeys.name] = "Dewy Lasher Frond",
            [itemKeys.npcDrops_add] = {275703,275708,276099},
        },
        [286075] = {
            [itemKeys.name] = "Herak's Head",
            [itemKeys.npcDrops_add] = {275767},
        },
        [286153] = {
            [itemKeys.name] = "Recipe: Plated Armorfish",
            [itemKeys.objectDrops_add] = {694054},
        },
        [286204] = {
            [itemKeys.name] = "Tomb Weed",
            [itemKeys.objectDrops_add] = {694732},
        },
        [286205] = {
            [itemKeys.name] = "Half-Eaten Fish",
            [itemKeys.objectDrops_add] = {694772},
        },
        [286209] = {
            [itemKeys.name] = "Shiny Junk",
            [itemKeys.objectDrops_add] = {694785},
        },
        [286214] = {
            [itemKeys.name] = "Duskweed Petal",
            [itemKeys.objectDrops_add] = {694855},
        },
        [286215] = {
            [itemKeys.name] = "Vial of Animal Blood",
            [itemKeys.npcDrops_add] = {113,822},
        },
        [286259] = {
            [itemKeys.name] = "Faintly Glowing Bone",
            [itemKeys.npcDrops_add] = {260428,260430,260432},
        },
        [286269] = {
            [itemKeys.name] = "Glowing Crystal Fragment",
            [itemKeys.objectDrops_add] = {694895},
        },
        [286325] = {
            [itemKeys.name] = "Avala's Core",
            [itemKeys.npcDrops_add] = {276009},
        },
        [286326] = {
            [itemKeys.name] = "Riptear's Heart",
            [itemKeys.npcDrops_add] = {276020},
        },
        [286339] = {
            [itemKeys.name] = "Mostly Dry Firewood",
            [itemKeys.objectDrops_add] = {694934},
        },
        [286358] = {
            [itemKeys.name] = "Coalbeard's Rifle",
            [itemKeys.objectDrops_add] = {695222},
        },
        [286359] = {
            [itemKeys.name] = "Sunhammer's Rifle",
            [itemKeys.objectDrops_add] = {695223},
        },
        [286360] = {
            [itemKeys.name] = "Stoneanvil's Rifle",
            [itemKeys.objectDrops_add] = {695277},
        },
        [286533] = {
            [itemKeys.name] = "Cheetah Hide Grips",
            [itemKeys.npcDrops_add] = {5865},
        },
        [286534] = {
            [itemKeys.name] = "Silithid Piercer",
            [itemKeys.npcDrops_add] = {3253},
        },
        [286541] = {
            [itemKeys.name] = "Bael'dun Tankard",
            [itemKeys.npcDrops_add] = {5848},
        },
        [286745] = {
            [itemKeys.name] = "Furlfeather Ring",
            [itemKeys.npcDrops_add] = {276194},
        },
        [286746] = {
            [itemKeys.name] = "Shal'ma's Shawl",
            [itemKeys.npcDrops_add] = {276198},
        },
        [286748] = {
            [itemKeys.name] = "Bristlebark Bow",
            [itemKeys.npcDrops_add] = {276189},
        },
        [286749] = {
            [itemKeys.name] = "Wrathroot",
            [itemKeys.npcDrops_add] = {276099},
        },
        [286750] = {
            [itemKeys.name] = "Wisesight Wand",
            [itemKeys.npcDrops_add] = {276101},
        },
        [286751] = {
            [itemKeys.name] = "Ghostfang's Steps",
            [itemKeys.npcDrops_add] = {276111},
        },
        [286752] = {
            [itemKeys.name] = "Igleggings",
            [itemKeys.npcDrops_add] = {276108},
        },
        [286753] = {
            [itemKeys.name] = "Snarlsnout Shooter",
            [itemKeys.npcDrops_add] = {276109},
        },
        [286754] = {
            [itemKeys.name] = "Ukta's Conduit",
            [itemKeys.npcDrops_add] = {276105},
        },
        [286755] = {
            [itemKeys.name] = "Helm Splitter",
            [itemKeys.npcDrops_add] = {276089},
        },
        [286977] = {
            [itemKeys.name] = "Sword of the Fallen",
            [itemKeys.npcDrops_add] = {250622,250627,250630},
        },
        [286978] = {
            [itemKeys.name] = "Rotmender's Garb",
            [itemKeys.npcDrops_add] = {255109},
        },
        [286981] = {
            [itemKeys.name] = "Death Bindings",
            [itemKeys.npcDrops_add] = {250618,250624,250626,255964},
        },
        [287505] = {
            [itemKeys.name] = "Tender Strider Meat",
            [itemKeys.npcDrops_add] = {2956,2957},
        },
    }
end