---@class ForeverObjectTraces
local ForeverObjectTraces = QuestieLoader:CreateModule("ForeverObjectTraces")

---@type QuestieDB
local QuestieDB = QuestieLoader:ImportModule("QuestieDB")

-- Generated by QuestieTrace extract (tools/trace-analyzer)
-- Source trace files: 1548
-- Sessions aggregated: 3405
-- Generated at: 2026-09-28T05:47:27.623Z
function ForeverObjectTraces:Load()
    local objectKeys = QuestieDB.objectKeys

    return {
        [406918] = {
            [objectKeys.name] = "Messenger Bag",
            [objectKeys.spawns] = {[45]={{22.48,24.23}}},
            [objectKeys.zoneID] = 45,
            [objectKeys.questStarts_add] = {79976},
            [objectKeys.questEnds_add] = {79975},
        },
        [415106] = {
            [objectKeys.name] = "Burned-Out Remains",
            [objectKeys.spawns] = {[17]={{46.34,73.86},{46.34,73.96},{46.41,73.96}}},
            [objectKeys.zoneID] = 17,
            [objectKeys.questStarts_add] = {79007,79192},
            [objectKeys.questEnds_add] = {79008},
        },
        [415107] = {
            [objectKeys.name] = "Burned-Out Remains",
            [objectKeys.spawns] = {[40]={{37.27,50.7},{37.33,50.86},{37.37,50.79},{37.4,50.85},{37.45,50.71},{37.45,50.86},{37.46,50.59},{37.46,50.92},{37.54,50.8}}},
            [objectKeys.zoneID] = 40,
            [objectKeys.questStarts_add] = {79008,79192},
            [objectKeys.questEnds_add] = {79007},
        },
        [424005] = {
            [objectKeys.name] = "Pocket Litter",
            [objectKeys.spawns] = {[406]={{40.79,52.61}}},
            [objectKeys.zoneID] = 406,
            [objectKeys.questStarts_add] = {79980},
            [objectKeys.questEnds_add] = {79192},
        },
        [424006] = {
            [objectKeys.name] = "Hastily Rolled-Up Satchel",
            [objectKeys.spawns] = {[45]={{22.47,24.23}}},
            [objectKeys.zoneID] = 45,
            [objectKeys.questEnds_add] = {79976},
        },
        [424007] = {
            [objectKeys.name] = "Carved Figurine",
            [objectKeys.spawns] = {[38]={{49.35,12.92},{49.42,12.78},{49.55,12.75}}},
            [objectKeys.zoneID] = 38,
            [objectKeys.questStarts_add] = {79975},
            [objectKeys.questEnds_add] = {79974},
        },
        [424010] = {
            [objectKeys.name] = "Nailed Plank",
            [objectKeys.spawns] = {[40]={{37.44,50.86}}},
            [objectKeys.zoneID] = 40,
            [objectKeys.questStarts_add] = {79192},
            [objectKeys.questEnds_add] = {79007},
        },
        [424012] = {
            [objectKeys.name] = "Mound of Dirt",
            [objectKeys.spawns] = {[406]={{39.6,49.91},{39.64,49.86}}},
            [objectKeys.zoneID] = 406,
            [objectKeys.questStarts_add] = {79974},
            [objectKeys.questEnds_add] = {79980},
        },
        [562131] = {
            [objectKeys.name] = "Applejack Still",
            [objectKeys.spawns] = {[12]={{24.5,58.23},{24.51,58.06}}},
            [objectKeys.zoneID] = 12,
        },
        [581822] = {
            [objectKeys.name] = "Bloodstained Satchel",
            [objectKeys.spawns] = {[16593]={{53.25,72.17},{53.31,72.1},{53.36,72.22}}},
            [objectKeys.zoneID] = 16593,
            [objectKeys.questStarts_add] = {92849},
            [objectKeys.questEnds_add] = {92727},
        },
        [610954] = {
            [objectKeys.name] = "Bounty Available: Vulgara the Insatiable!",
            [objectKeys.spawns] = {[16593]={{43.37,45.82}}},
            [objectKeys.zoneID] = 16593,
            [objectKeys.questStarts_add] = {93318},
        },
        [619896] = {
            [objectKeys.name] = "Forgotten Shrine",
            [objectKeys.spawns] = {[40]={{45.45,59.89}}},
            [objectKeys.zoneID] = 40,
        },
        [630865] = {
            [objectKeys.name] = "Guild Vault",
            [objectKeys.spawns] = {[1519]={{64.18,80.47}}},
            [objectKeys.zoneID] = 1519,
        },
        [644437] = {
            [objectKeys.name] = "Mailbox",
            [objectKeys.spawns] = {[1497]={{69.18,51.46},{69.68,52.32},{70.01,51.78},{70.08,51.17}}},
            [objectKeys.zoneID] = 1497,
        },
        [644438] = {
            [objectKeys.name] = "Mailbox",
            [objectKeys.spawns] = {[1497]={{61.71,51.1},{61.84,51.28},{61.86,51.18},{61.92,51.08},{61.95,51.77},{62,50.95},{62.09,51.96},{62.11,51.05},{62.26,51.47},{62.27,51.21},{62.32,51.52},{62.32,52.11},{62.35,52.2},{62.45,51.63},{62.49,51.67}}},
            [objectKeys.zoneID] = 1497,
        },
        [644439] = {
            [objectKeys.name] = "Mailbox",
            [objectKeys.spawns] = {[1497]={{61.91,36.81},{61.93,36.72},{62.01,36.8},{62.11,36.87},{62.12,36.47},{62.14,36.15}}},
            [objectKeys.zoneID] = 1497,
        },
        [644440] = {
            [objectKeys.name] = "Mailbox",
            [objectKeys.spawns] = {[1497]={{69.79,36.21},{69.91,36.31},{69.98,36.6},{69.99,36.78},{70,37.05},{70.03,37.17},{70.05,36.99},{70.15,36.41}}},
            [objectKeys.zoneID] = 1497,
        },
        [644441] = {
            [objectKeys.name] = "Mailbox",
            [objectKeys.spawns] = {[1497]={{66.4,50.05},{66.44,49.92},{66.66,50.25},{66.91,50.28}}},
            [objectKeys.zoneID] = 1497,
        },
        [644488] = {
            [objectKeys.name] = "Mailbox",
            [objectKeys.spawns] = {[1497]={{67.74,38.3},{67.93,38.25},{67.94,38.39},{67.98,38.24},{68.05,38.64},{68.09,38.58}}},
            [objectKeys.zoneID] = 1497,
        },
        [650428] = {
            [objectKeys.name] = "Mailbox",
            [objectKeys.spawns] = {[1537]={{70.58,72.33},{70.96,72.37},{71.43,71.48}}},
            [objectKeys.zoneID] = 1537,
        },
        [650577] = {
            [objectKeys.name] = "Mailbox",
            [objectKeys.spawns] = {[1537]={{21.23,53.02},{21.28,53.2},{21.32,52.73}}},
            [objectKeys.zoneID] = 1537,
        },
        [650593] = {
            [objectKeys.name] = "Mailbox",
            [objectKeys.spawns] = {[1537]={{32.62,64.85},{32.65,65.39},{32.67,65.25},{32.71,65.02},{32.8,64.22},{32.81,65.01},{32.81,65.16},{32.85,65.62},{32.86,64.04},{32.86,64.24},{32.91,64.33},{32.95,64.27},{32.95,65.24},{32.97,64.59},{32.97,64.84},{32.97,65.18},{32.99,65.89},{33.04,64.65},{33.05,64.72},{33.07,64.16},{33.09,64.89},{33.1,64.47},{33.12,64.76},{33.17,64.24},{33.25,63.94},{33.38,65.17},{33.41,65.66},{33.43,65.58}}},
            [objectKeys.zoneID] = 1537,
        },
        [650666] = {
            [objectKeys.name] = "Mailbox",
            [objectKeys.spawns] = {[1537]={{71.38,48.84},{71.91,49.17},{72.05,49.49},{72.27,48.73}}},
            [objectKeys.zoneID] = 1537,
        },
        [651604] = {
            [objectKeys.name] = "Mailbox",
            [objectKeys.spawns] = {[36]={{12.7,52.63},{12.76,52.77}}},
            [objectKeys.zoneID] = 36,
        },
        [652323] = {
            [objectKeys.name] = "Mailbox",
            [objectKeys.spawns] = {[16593]={{43.24,44.24},{43.26,44.15},{43.28,44.2},{43.38,44.18}}},
            [objectKeys.zoneID] = 16593,
        },
        [652324] = {
            [objectKeys.name] = "Mailbox",
            [objectKeys.spawns] = {[16593]={{62.24,73.76},{62.27,73.59},{62.28,73.93}}},
            [objectKeys.zoneID] = 16593,
        },
        [654846] = {
            [objectKeys.name] = "Lost Journal",
            [objectKeys.spawns] = {[141]={{59.1,39.49}}},
            [objectKeys.zoneID] = 141,
            [objectKeys.questStarts_add] = {96630},
        },
        [654925] = {
            [objectKeys.name] = "Lost Journal",
            [objectKeys.spawns] = {[14]={{42.82,69.14}}},
            [objectKeys.zoneID] = 14,
            [objectKeys.questStarts_add] = {96652},
        },
        [658827] = {
            [objectKeys.name] = "Mailbox",
            [objectKeys.spawns] = {[215]={{33.78,21.88}}},
            [objectKeys.zoneID] = 215,
        },
        [658838] = {
            [objectKeys.name] = "The Rebellion In Eldre'Thalas, Part 1",
            [objectKeys.spawns] = {[16593]={{49.77,56.59},{49.81,56.41},{49.81,56.48}}},
            [objectKeys.zoneID] = 16593,
        },
        [658840] = {
            [objectKeys.name] = "The Rebellion In Eldre'Thalas, Part 3",
            [objectKeys.spawns] = {[16593]={{64.59,35.12}}},
            [objectKeys.zoneID] = 16593,
        },
        [658919] = {
            [objectKeys.name] = "Mailbox",
            [objectKeys.spawns] = {[1637]={{53.31,65.94},{53.35,65.6},{53.36,65.72},{53.36,65.91},{53.42,65.57},{53.42,65.93},{53.43,65.75},{53.43,65.82},{53.44,65.64},{53.47,66.16},{53.51,65.88},{53.55,66.14}}},
            [objectKeys.zoneID] = 1637,
        },
        [658921] = {
            [objectKeys.name] = "Mailbox",
            [objectKeys.spawns] = {[1637]={{81.38,21.24},{81.47,21.07}}},
            [objectKeys.zoneID] = 1637,
        },
        [658922] = {
            [objectKeys.name] = "Mailbox",
            [objectKeys.spawns] = {[1637]={{48.18,38.06},{48.2,37.74}}},
            [objectKeys.zoneID] = 1637,
        },
        [658923] = {
            [objectKeys.name] = "Mailbox",
            [objectKeys.spawns] = {[1637]={{51.29,59.63},{51.49,59.5},{51.6,59.19},{51.62,59.06},{51.69,58.86},{51.85,58.68},{51.91,58.68}}},
            [objectKeys.zoneID] = 1637,
        },
        [658926] = {
            [objectKeys.name] = "Mailbox",
            [objectKeys.spawns] = {[1637]={{51.76,46.69}}},
            [objectKeys.zoneID] = 1637,
        },
        [658927] = {
            [objectKeys.name] = "Mailbox",
            [objectKeys.spawns] = {[1637]={{49.37,71.41},{49.41,71.45},{49.76,71.06}}},
            [objectKeys.zoneID] = 1637,
        },
        [658970] = {
            [objectKeys.name] = "Mailbox",
            [objectKeys.spawns] = {[1637]={{61.95,40.82},{62,40.6},{62.04,40.49},{62.04,40.71},{62.36,40.1},{62.37,40.21},{62.47,40.11}}},
            [objectKeys.zoneID] = 1637,
        },
        [659159] = {
            [objectKeys.name] = "Mailbox",
            [objectKeys.spawns] = {[1637]={{50.59,70.76},{50.61,70.71},{50.67,70.25},{50.68,70.66},{50.7,70.57},{50.71,70.11},{50.74,70.28},{50.76,70.75},{50.79,70.92},{50.84,70.34},{50.85,70.51},{50.86,70.07},{50.86,70.43},{50.91,69.85},{50.93,70},{50.93,70.34},{50.94,70.25},{50.97,69.8},{50.99,70.16},{51,69.89}}},
            [objectKeys.zoneID] = 1637,
        },
        [659816] = {
            [objectKeys.name] = "Mailbox",
            [objectKeys.spawns] = {[16591]={{78.55,53.73},{78.58,53.66}}},
            [objectKeys.zoneID] = 16591,
        },
        [660739] = {
            [objectKeys.name] = "Ritual Fire",
            [objectKeys.spawns] = {[215]={{56.57,88.69}}},
            [objectKeys.zoneID] = 215,
        },
        [660964] = {
            [objectKeys.name] = "Misplaced Packages",
            [objectKeys.spawns] = {[1537]={{72.16,48.88},{72.22,49.23},{72.32,48.76},{72.38,48.76},{72.38,49},{72.51,48.23},{72.57,48.25}}},
            [objectKeys.zoneID] = 1537,
            [objectKeys.questStarts_add] = {97263},
        },
        [665289] = {
            [objectKeys.name] = "Discarded Fishing Toolbox",
            [objectKeys.spawns] = {[38]={{48.06,39.76},{50.58,53.29},{50.69,53.33}}},
            [objectKeys.zoneID] = 38,
            [objectKeys.questStarts_add] = {86614},
        },
        [671479] = {
            [objectKeys.name] = "On The Windlord",
            [objectKeys.spawns] = {[16593]={{56,58.71}}},
            [objectKeys.zoneID] = 16593,
        },
        [678602] = {
            [objectKeys.spawns] = {[1497]={{22.95,36.21}}},
            [objectKeys.zoneID] = 1497,
        },
        [696264] = {
            [objectKeys.name] = "Mailbox",
            [objectKeys.spawns] = {[1519]={{61.45,70.56},{61.55,70.33},{61.56,70.46},{61.64,70.48},{61.64,70.78},{61.67,70.62},{61.68,70.44},{61.7,70.18},{61.71,70.5},{61.75,70.83},{61.76,70.31},{61.78,70.38},{61.79,70.66},{61.8,70.52},{61.8,70.98},{61.84,70.86}}},
            [objectKeys.zoneID] = 1519,
        },
        [696265] = {
            [objectKeys.name] = "Mailbox",
            [objectKeys.spawns] = {[1519]={{62.27,74.61},{62.33,74.75},{62.34,74.93},{62.4,74.48},{62.48,75.06}}},
            [objectKeys.zoneID] = 1519,
        },
        [696267] = {
            [objectKeys.name] = "Mailbox",
            [objectKeys.spawns] = {[1519]={{75.74,64.3}}},
            [objectKeys.zoneID] = 1519,
        },
        [696268] = {
            [objectKeys.name] = "Mailbox",
            [objectKeys.spawns] = {[1519]={{64.55,37.23},{64.6,37.12},{64.68,37.12},{64.74,37.34}}},
            [objectKeys.zoneID] = 1519,
        },
        [696276] = {
            [objectKeys.name] = "Mailbox",
            [objectKeys.spawns] = {[1519]={{57.28,71.61}}},
            [objectKeys.zoneID] = 1519,
        },
        [696279] = {
            [objectKeys.name] = "Mailbox",
            [objectKeys.spawns] = {[1519]={{67.63,49.75}}},
            [objectKeys.zoneID] = 1519,
        },
        [696281] = {
            [objectKeys.name] = "Mailbox",
            [objectKeys.spawns] = {[1519]={{66.57,65.01},{66.71,65.11},{66.77,65.37}}},
            [objectKeys.zoneID] = 1519,
        },
        [696374] = {
            [objectKeys.name] = "Mailbox",
            [objectKeys.spawns] = {[1519]={{74.17,55.49},{74.56,55.56},{74.87,55.44}}},
            [objectKeys.zoneID] = 1519,
        },
        [696376] = {
            [objectKeys.name] = "Alliance Military Ranks",
            [objectKeys.spawns] = {[1519]={{75.73,66.58}}},
            [objectKeys.zoneID] = 1519,
        },
        [696751] = {
            [objectKeys.name] = "Mailbox",
            [objectKeys.spawns] = {[1519]={{61.64,75.58},{61.67,75.74},{61.7,75.96},{61.72,76.08},{61.77,75.6},{61.77,75.72},{61.77,75.87},{61.77,76.03},{61.79,76.12},{61.82,76.21},{61.84,75.85},{61.85,75.74},{61.85,76.08},{61.85,76.14},{61.85,76.28},{61.86,75.47},{61.94,76.3}}},
            [objectKeys.zoneID] = 1519,
        },
    }
end