-- Offline half of the CBOR transport probe. Lua 5.1.
-- Extracts the Classic quest table from QuestieDB source data, encodes it with the
-- verified BlizzardCBOR encoder, and writes: quests.cbor (raw bytes) and data.lua
-- (the same table as a Lua literal, the ground truth the client compares against).
local OUT = assert(arg[1], "usage: lua5.1 tools/probe-addon/gen-cbor-probe.lua <output-dir>")
local CBOR = dofile("generator/vendor/BlizzardCBOR.lua")

local f = assert(io.open("data/Classic/classicQuestDB.lua", "rb"))
local src = f:read("*a"); f:close()
local literal = src:match("QuestieDB%.questData = %[%[(.-)%]%]")
assert(literal and literal:sub(1, 7) == "return ", "questData payload not found")

local rows = assert(loadstring(literal))()
local n = 0 for _ in pairs(rows) do n = n + 1 end

local bytes = CBOR.SerializeCBOR(rows)
local o = assert(io.open(OUT .. "/quests.cbor", "wb")); o:write(bytes); o:close()

local d = assert(io.open(OUT .. "/data.lua", "wb"))
d:write("-- GENERATED by gen-cbor-probe.lua: the Classic quest table as ground truth.\n")
d:write("TDBProbe_Quests = (function() ", literal, " end)()\n")
d:close()
print(string.format("quests=%d literal=%dB cbor=%dB", n, #literal, #bytes))
