# This is a basic workflow that is manually triggered

name: Release QuestieDB (Main branch)

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build_release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Check out ${{ github.repository }} code
      uses: actions/checkout@v4

    - name: Install Lua 5.1.5
      uses: leafo/gh-actions-lua@v10
      with:
        luaVersion: "5.1.5"

    - name: Install LuaRocks
      uses: leafo/gh-actions-luarocks@v4.3.0

    # Install LuaRocks packages
    - name: Install Lua Packages
      run: |
        luarocks install bit32
        luarocks install argparse
        luarocks install luafilesystem
        luarocks install luasocket
        luarocks install luasec

    - name: Generate l10n Translations
      run: sh ./.generate_database/generate_l10n.sh

    # Runs a single command using the runners shell
    - name: Generate HTML
      run: sh ./.database_generator/generate_database.sh ./.lua/bin/lua


    - name: Run Era Tests
      run: lua ./.tests/runTests.lua Era

    - name: Run Tbc Tests
      run: lua ./.tests/runTests.lua Tbc

    - name: Run Wotlk Tests
      run: lua ./.tests/runTests.lua Wotlk

    - name: Run Cata Tests
      run: lua ./.tests/runTests.lua Cata

    # Create the QuestieDB build, will output toc_version
    - name: Build QuestieDB
      id: build
      run: python build.py build QuestieDB
      env:
        GITHUB_ACTIONS: "true"

    - name: Create QuestieDB.zip
      uses: TheDoctor0/zip-release@0.7.6
      with:
        type: 'zip'
        directory: './.build/'
        path: './QuestieDB'
        filename: './QuestieDB-v${{ steps.build.outputs.toc_version }}.zip'

    - name: Publish release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "./.build/QuestieDB-v${{ steps.build.outputs.toc_version }}.zip"
        name: "Release version ${{ steps.build.outputs.toc_version }}"
        body: "Release body"
        commit: "${{ github.sha }}"
        tag: "v${{ steps.build.outputs.toc_version }}"
        allowUpdates: true
        # Remove all artifacts on release
        removeArtifacts: true
