name: CI

on:
  # push:
  #   branches:
  #     - "**"
  #   tags:
  #     - "*"
  pull_request:


jobs:
  lua-check:
    runs-on: ubuntu-latest

    steps:
    - name: Check out ${{ github.repository }} code
      uses: actions/checkout@v4

    - name: Install Lua 5.1.5
      uses: leafo/gh-actions-lua@v10
      with:
        luaVersion: "5.1.5"

    - name: Install LuaRocks
      uses: leafo/gh-actions-luarocks@v4.3.0

    # Install LuaRocks packages
    - name: Install Lua Packages
      run: |
        luarocks install bit32
        luarocks install argparse
        luarocks install luafilesystem
        luarocks install luasocket
        luarocks install luasec

    # Runs a single command using the runners shell
    - name: Generate HTML
      run: sh ./.database_generator/generate_database.sh ./.lua/bin/lua

    - name: Run Era Tests
      run: lua ./.tests/runTests.lua Era

    - name: Run Tbc Tests
      run: lua ./.tests/runTests.lua Tbc

    - name: Run Wotlk Tests
      run: lua ./.tests/runTests.lua Wotlk

    - name: Run Cata Tests
      run: lua ./.tests/runTests.lua Cata